/* FakeServer.vala.c generated by valac, the Vala compiler
 * generated from FakeServer.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gio/gio.h>
#include <glib/gstdio.h>
#include <webkit2/webkit2.h>


#define TYPE_FAKE_SERVER_CACHE (fake_server_cache_get_type ())
#define FAKE_SERVER_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FAKE_SERVER_CACHE, FakeServerCache))
#define FAKE_SERVER_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FAKE_SERVER_CACHE, FakeServerCacheClass))
#define IS_FAKE_SERVER_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FAKE_SERVER_CACHE))
#define IS_FAKE_SERVER_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FAKE_SERVER_CACHE))
#define FAKE_SERVER_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FAKE_SERVER_CACHE, FakeServerCacheClass))

typedef struct _FakeServerCache FakeServerCache;
typedef struct _FakeServerCacheClass FakeServerCacheClass;
typedef struct _FakeServerCachePrivate FakeServerCachePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_FAKE_SERVER (fake_server_get_type ())
#define FAKE_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FAKE_SERVER, FakeServer))
#define FAKE_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FAKE_SERVER, FakeServerClass))
#define IS_FAKE_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FAKE_SERVER))
#define IS_FAKE_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FAKE_SERVER))
#define FAKE_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FAKE_SERVER, FakeServerClass))

typedef struct _FakeServer FakeServer;
typedef struct _FakeServerClass FakeServerClass;
typedef struct _FakeServerPrivate FakeServerPrivate;

/**
 * Originally this was supposed to intercept http calls and redirect them
 * but that is not supported in webkit2 (without using the extension api)
 * 
 * so for now we have modified our server to serve use a base url of xhttp:
 * 
 * so all relative urls are based on that 
 * 
 * Idea is to serve the files from the file system, so no need to setup apache etc...
 * This should work for the static content like css / javascript etc.. but 
 * will cause issues with 'dynamic' xhr files (eg. the php stuff)
 *
 * the idea is nicked from geary.
 * 
 * At present this serves from ~/gitlive/****  - that probably needs more thought..
 * 
 * 
 */
typedef enum  {
	FAKE_SERVER_ERROR_FILE_DOES_NOT_EXIST
} FakeServerError;
#define FAKE_SERVER_ERROR fake_server_error_quark ()
struct _FakeServerCache {
	GObject parent_instance;
	FakeServerCachePrivate * priv;
	gchar* fname;
	guint8* data;
	gint data_length1;
	gchar* content_type;
	gint64 size;
};

struct _FakeServerCacheClass {
	GObjectClass parent_class;
};

struct _FakeServer {
	GObject parent_instance;
	FakeServerPrivate * priv;
};

struct _FakeServerClass {
	GObjectClass parent_class;
};

struct _FakeServerPrivate {
	WebKitWebView* view;
};


static gpointer fake_server_cache_parent_class = NULL;
extern GeeHashMap* fake_server_cache_cache;
GeeHashMap* fake_server_cache_cache = NULL;
static gpointer fake_server_parent_class = NULL;

GQuark fake_server_error_quark (void);
GType fake_server_cache_get_type (void) G_GNUC_CONST;
enum  {
	FAKE_SERVER_CACHE_DUMMY_PROPERTY
};
FakeServerCache* fake_server_cache_factory (const gchar* fname, const gchar* scheme);
FakeServerCache* fake_server_cache_new_from_resource (const gchar* fname);
FakeServerCache* fake_server_cache_construct_from_resource (GType object_type, const gchar* fname);
FakeServerCache* fake_server_cache_new (const gchar* fname);
FakeServerCache* fake_server_cache_construct (GType object_type, const gchar* fname);
void fake_server_cache_remove (const gchar* fname);
void fake_server_cache_clear (void);
FakeServerCache* fake_server_cache_factory_with_data (const gchar* data);
FakeServerCache* fake_server_cache_new_with_data (const gchar* data);
FakeServerCache* fake_server_cache_construct_with_data (GType object_type, const gchar* data);
static guint8* _vala_array_dup1 (guint8* self, int length);
gchar* builder_application_configDirectory (void);
static guint8* _vala_array_dup2 (guint8* self, int length);
static guint8* _vala_array_dup3 (guint8* self, int length);
static guint8* _vala_array_dup4 (guint8* self, int length);
static guint8* _vala_array_dup5 (guint8* self, int length);
static guint8* _vala_array_dup6 (guint8* self, int length);
static guint8* _vala_array_dup7 (guint8* self, int length);
void fake_server_cache_run (FakeServerCache* self, WebKitURISchemeRequest* request, GCancellable* cancellable);
static guint8* _vala_array_dup8 (guint8* self, int length);
static void _g_free_gdestroy_notify (void* data);
static void fake_server_cache_finalize (GObject* obj);
GType fake_server_get_type (void) G_GNUC_CONST;
#define FAKE_SERVER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_FAKE_SERVER, FakeServerPrivate))
enum  {
	FAKE_SERVER_DUMMY_PROPERTY
};
FakeServer* fake_server_new (WebKitWebView* wkview);
FakeServer* fake_server_construct (GType object_type, WebKitWebView* wkview);
void fake_server_serve (FakeServer* self, WebKitURISchemeRequest* request);
static void _fake_server_serve_web_kit_uri_scheme_request_callback (WebKitURISchemeRequest* request, gpointer self);
static void fake_server_finalize (GObject* obj);


GQuark fake_server_error_quark (void) {
	return g_quark_from_static_string ("fake_server_error-quark");
}


FakeServerCache* fake_server_cache_factory (const gchar* fname, const gchar* scheme) {
	FakeServerCache* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp2_ = NULL;
	GeeHashMap* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gboolean _tmp7_ = FALSE;
	const gchar* _tmp12_ = NULL;
	FakeServerCache* el = NULL;
	const gchar* _tmp13_ = NULL;
	FakeServerCache* _tmp14_ = NULL;
	GeeHashMap* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	FakeServerCache* _tmp17_ = NULL;
#line 34 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0_ = fake_server_cache_cache;
#line 34 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (_tmp0_ == NULL) {
#line 158 "FakeServer.vala.c"
		GeeHashMap* _tmp1_ = NULL;
#line 35 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, TYPE_FAKE_SERVER_CACHE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 35 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (fake_server_cache_cache);
#line 35 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		fake_server_cache_cache = _tmp1_;
#line 166 "FakeServer.vala.c"
	}
#line 39 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp2_ = scheme;
#line 39 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (g_strcmp0 (_tmp2_, "resources") == 0) {
#line 172 "FakeServer.vala.c"
		const gchar* _tmp3_ = NULL;
		FakeServerCache* _tmp4_ = NULL;
#line 40 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp3_ = fname;
#line 40 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp4_ = fake_server_cache_new_from_resource (_tmp3_);
#line 40 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		result = _tmp4_;
#line 40 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return result;
#line 183 "FakeServer.vala.c"
	}
#line 43 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp5_ = fake_server_cache_cache;
#line 43 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp6_ = fname;
#line 43 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp7_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp5_, _tmp6_);
#line 43 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (_tmp7_) {
#line 193 "FakeServer.vala.c"
		const gchar* _tmp8_ = NULL;
		GeeHashMap* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		gpointer _tmp11_ = NULL;
#line 44 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp8_ = fname;
#line 44 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		g_print ("CACHE got  %s\n", _tmp8_);
#line 45 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp9_ = fake_server_cache_cache;
#line 45 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp10_ = fname;
#line 45 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp11_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp9_, _tmp10_);
#line 45 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		result = (FakeServerCache*) _tmp11_;
#line 45 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return result;
#line 212 "FakeServer.vala.c"
	}
#line 47 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp12_ = fname;
#line 47 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	g_print ("CACHE create %s\n", _tmp12_);
#line 49 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp13_ = fname;
#line 49 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp14_ = fake_server_cache_new (_tmp13_);
#line 49 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	el = _tmp14_;
#line 51 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp15_ = fake_server_cache_cache;
#line 51 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp16_ = fname;
#line 51 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp17_ = el;
#line 51 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp15_, _tmp16_, _tmp17_);
#line 52 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	result = el;
#line 52 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return result;
#line 236 "FakeServer.vala.c"
}


void fake_server_cache_remove (const gchar* fname) {
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	FakeServerCache* v = NULL;
	GeeHashMap* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
#line 56 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0_ = fake_server_cache_cache;
#line 56 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (_tmp0_ == NULL) {
#line 57 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return;
#line 255 "FakeServer.vala.c"
	}
#line 59 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp1_ = fake_server_cache_cache;
#line 59 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp2_ = fname;
#line 59 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp3_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp1_, _tmp2_);
#line 59 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (!_tmp3_) {
#line 60 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return;
#line 267 "FakeServer.vala.c"
	}
#line 66 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp4_ = fake_server_cache_cache;
#line 66 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp5_ = fname;
#line 66 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	gee_abstract_map_unset ((GeeAbstractMap*) _tmp4_, _tmp5_, &_tmp6_);
#line 66 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_object_unref0 (v);
#line 66 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	v = _tmp6_;
#line 55 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_object_unref0 (v);
#line 281 "FakeServer.vala.c"
}


void fake_server_cache_clear (void) {
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
#line 73 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0_ = fake_server_cache_cache;
#line 73 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (_tmp0_ == NULL) {
#line 74 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return;
#line 294 "FakeServer.vala.c"
	}
#line 76 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp1_ = fake_server_cache_cache;
#line 76 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	gee_abstract_map_clear ((GeeAbstractMap*) _tmp1_);
#line 300 "FakeServer.vala.c"
}


FakeServerCache* fake_server_cache_factory_with_data (const gchar* data) {
	FakeServerCache* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	FakeServerCache* el = NULL;
	const gchar* _tmp2_ = NULL;
	FakeServerCache* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	GeeHashMap* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
#line 80 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0_ = fake_server_cache_cache;
#line 80 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (_tmp0_ == NULL) {
#line 317 "FakeServer.vala.c"
		GeeHashMap* _tmp1_ = NULL;
#line 81 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, TYPE_FAKE_SERVER_CACHE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 81 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (fake_server_cache_cache);
#line 81 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		fake_server_cache_cache = _tmp1_;
#line 325 "FakeServer.vala.c"
	}
#line 83 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp2_ = data;
#line 83 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp3_ = fake_server_cache_new_with_data (_tmp2_);
#line 83 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	el = _tmp3_;
#line 84 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp4_ = el->fname;
#line 84 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	g_print ("CACHE - store %s\n", _tmp4_);
#line 85 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp5_ = fake_server_cache_cache;
#line 85 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp6_ = el->fname;
#line 85 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp5_, _tmp6_, el);
#line 86 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	result = el;
#line 86 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return result;
#line 347 "FakeServer.vala.c"
}


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res = NULL;
	gint res_length1 = 0;
	gint _res_size_ = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	guint8* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	guint8* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
#line 1399 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	res = (guint8*) self;
#line 1399 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	res_length1 = -1;
#line 1399 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_res_size_ = res_length1;
#line 1400 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp0_ = strlen (self);
#line 1400 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 1400 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	res_length1 = (gint) _tmp1_;
#line 1400 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp2_ = res_length1;
#line 1401 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp3_ = res;
#line 1401 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp3__length1 = res_length1;
#line 1401 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp4_ = _tmp3_;
#line 1401 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp4__length1 = _tmp3__length1;
#line 1401 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	if (result_length1) {
#line 1401 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		*result_length1 = _tmp4__length1;
#line 389 "FakeServer.vala.c"
	}
#line 1401 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	result = _tmp4_;
#line 1401 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	return result;
#line 395 "FakeServer.vala.c"
}


static guint8* _vala_array_dup1 (guint8* self, int length) {
#line 95 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return g_memdup (self, length * sizeof (guint8));
#line 402 "FakeServer.vala.c"
}


FakeServerCache* fake_server_cache_construct_with_data (GType object_type, const gchar* data) {
	FakeServerCache * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	guint8* _tmp10_ = NULL;
	gint _tmp10__length1 = 0;
	guint8* _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	guint8* _tmp12_ = NULL;
	gint _tmp12__length1 = 0;
	gchar* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
#line 92 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self = (FakeServerCache*) g_object_new (object_type, NULL);
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0_ = data;
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp1_ = data;
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp2_ = strlen (_tmp1_);
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp3_ = _tmp2_;
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp4_ = g_compute_checksum_for_string (G_CHECKSUM_MD5, _tmp0_, (gsize) _tmp3_);
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp5_ = _tmp4_;
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp6_ = g_strconcat ("/", _tmp5_, NULL);
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp7_ = _tmp6_;
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp8_ = g_strconcat (_tmp7_, ".js", NULL);
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (self->fname);
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->fname = _tmp8_;
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (_tmp7_);
#line 94 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (_tmp5_);
#line 95 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp9_ = data;
#line 95 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp10_ = string_get_data (_tmp9_, &_tmp10__length1);
#line 95 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp11_ = _tmp10_;
#line 95 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp11__length1 = _tmp10__length1;
#line 95 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp12_ = (_tmp11_ != NULL) ? _vala_array_dup1 (_tmp11_, _tmp11__length1) : ((gpointer) _tmp11_);
#line 95 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp12__length1 = _tmp11__length1;
#line 95 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->data = (g_free (self->data), NULL);
#line 95 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->data = _tmp12_;
#line 95 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->data_length1 = _tmp12__length1;
#line 96 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp13_ = g_strdup ("text/javascript");
#line 96 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (self->content_type);
#line 96 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->content_type = _tmp13_;
#line 97 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp14_ = data;
#line 97 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp15_ = strlen (_tmp14_);
#line 97 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp16_ = _tmp15_;
#line 97 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->size = (gint64) _tmp16_;
#line 92 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return self;
#line 490 "FakeServer.vala.c"
}


FakeServerCache* fake_server_cache_new_with_data (const gchar* data) {
#line 92 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return fake_server_cache_construct_with_data (TYPE_FAKE_SERVER_CACHE, data);
#line 497 "FakeServer.vala.c"
}


static guint8* _vala_array_dup2 (guint8* self, int length) {
#line 110 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return g_memdup (self, length * sizeof (guint8));
#line 504 "FakeServer.vala.c"
}


static guint8* _vala_array_dup3 (guint8* self, int length) {
#line 127 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return g_memdup (self, length * sizeof (guint8));
#line 511 "FakeServer.vala.c"
}


static guint8* _vala_array_dup4 (guint8* self, int length) {
#line 129 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return g_memdup (self, length * sizeof (guint8));
#line 518 "FakeServer.vala.c"
}


FakeServerCache* fake_server_cache_construct_from_resource (GType object_type, const gchar* fname) {
	FakeServerCache * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GFile* file = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	GFile* _tmp9_ = NULL;
	GFile* _tmp10_ = NULL;
	GFile* _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	GError * _inner_error_ = NULL;
#line 101 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self = (FakeServerCache*) g_object_new (object_type, NULL);
#line 106 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0_ = fname;
#line 106 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 106 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (self->fname);
#line 106 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->fname = _tmp1_;
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp2_ = builder_application_configDirectory ();
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp3_ = _tmp2_;
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp4_ = g_strconcat (_tmp3_, "/resources/", NULL);
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp5_ = _tmp4_;
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp6_ = fname;
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp7_ = g_strconcat (_tmp5_, _tmp6_, NULL);
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp8_ = _tmp7_;
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp9_ = g_file_new_for_path (_tmp8_);
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp10_ = _tmp9_;
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (_tmp8_);
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (_tmp5_);
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (_tmp3_);
#line 108 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	file = _tmp10_;
#line 109 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp11_ = file;
#line 109 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp12_ = g_file_query_exists (_tmp11_, NULL);
#line 109 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (!_tmp12_) {
#line 581 "FakeServer.vala.c"
		guint8* _tmp13_ = NULL;
		gint _tmp13__length1 = 0;
		guint8* _tmp14_ = NULL;
		gint _tmp14__length1 = 0;
		guint8* _tmp15_ = NULL;
		gint _tmp15__length1 = 0;
		gchar* _tmp16_ = NULL;
#line 110 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp13_ = string_get_data ("", &_tmp13__length1);
#line 110 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp14_ = _tmp13_;
#line 110 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp14__length1 = _tmp13__length1;
#line 110 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp15_ = (_tmp14_ != NULL) ? _vala_array_dup2 (_tmp14_, _tmp14__length1) : ((gpointer) _tmp14_);
#line 110 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp15__length1 = _tmp14__length1;
#line 110 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 110 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = _tmp15_;
#line 110 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data_length1 = _tmp15__length1;
#line 111 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp16_ = g_strdup ("");
#line 111 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_free0 (self->content_type);
#line 111 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->content_type = _tmp16_;
#line 112 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->size = (gint64) 0;
#line 113 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (file);
#line 113 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return self;
#line 617 "FakeServer.vala.c"
	}
	{
		GFileInfo* info = NULL;
		GFile* _tmp17_ = NULL;
		GFileInfo* _tmp18_ = NULL;
		GFileInfo* _tmp19_ = NULL;
		const gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		GFileInfo* _tmp22_ = NULL;
		gint64 _tmp23_ = 0LL;
		guint8* data = NULL;
		gint data_length1 = 0;
		gint _data_size_ = 0;
		GFile* _tmp24_ = NULL;
		gchar* _tmp25_ = NULL;
		gchar* _tmp26_ = NULL;
		guint8* _tmp27_ = NULL;
		size_t _tmp28_;
		guint8* _tmp29_ = NULL;
		gint _tmp29__length1 = 0;
		guint8* _tmp30_ = NULL;
		gint _tmp30__length1 = 0;
#line 116 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp17_ = file;
#line 116 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp18_ = g_file_query_info (_tmp17_, "standard::*", G_FILE_QUERY_INFO_NONE, NULL, &_inner_error_);
#line 116 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		info = _tmp18_;
#line 116 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 648 "FakeServer.vala.c"
			goto __catch11_g_error;
		}
#line 121 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp19_ = info;
#line 121 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp20_ = g_file_info_get_content_type (_tmp19_);
#line 121 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp21_ = g_strdup (_tmp20_);
#line 121 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_free0 (self->content_type);
#line 121 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->content_type = _tmp21_;
#line 122 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp22_ = info;
#line 122 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp23_ = g_file_info_get_size (_tmp22_);
#line 122 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->size = _tmp23_;
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp24_ = file;
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp25_ = g_file_get_path (_tmp24_);
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp26_ = _tmp25_;
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		g_file_get_contents (_tmp26_, (gchar**) (&_tmp27_), &_tmp28_, &_inner_error_);
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		data = (g_free (data), NULL);
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		data = _tmp27_;
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		data_length1 = _tmp28_;
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_data_size_ = data_length1;
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_free0 (_tmp26_);
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
			data = (g_free (data), NULL);
#line 126 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
			_g_object_unref0 (info);
#line 691 "FakeServer.vala.c"
			goto __catch11_g_error;
		}
#line 127 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp29_ = data;
#line 127 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp29__length1 = data_length1;
#line 127 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp30_ = (_tmp29_ != NULL) ? _vala_array_dup3 (_tmp29_, _tmp29__length1) : ((gpointer) _tmp29_);
#line 127 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp30__length1 = _tmp29__length1;
#line 127 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 127 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = _tmp30_;
#line 127 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data_length1 = _tmp30__length1;
#line 115 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		data = (g_free (data), NULL);
#line 115 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (info);
#line 712 "FakeServer.vala.c"
	}
	goto __finally11;
	__catch11_g_error:
	{
		GError* e = NULL;
		guint8* _tmp31_ = NULL;
		gint _tmp31__length1 = 0;
		guint8* _tmp32_ = NULL;
		gint _tmp32__length1 = 0;
		guint8* _tmp33_ = NULL;
		gint _tmp33__length1 = 0;
		gchar* _tmp34_ = NULL;
#line 115 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		e = _inner_error_;
#line 115 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_inner_error_ = NULL;
#line 129 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp31_ = string_get_data ("", &_tmp31__length1);
#line 129 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp32_ = _tmp31_;
#line 129 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp32__length1 = _tmp31__length1;
#line 129 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp33_ = (_tmp32_ != NULL) ? _vala_array_dup4 (_tmp32_, _tmp32__length1) : ((gpointer) _tmp32_);
#line 129 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp33__length1 = _tmp32__length1;
#line 129 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 129 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = _tmp33_;
#line 129 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data_length1 = _tmp33__length1;
#line 130 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->size = (gint64) 0;
#line 131 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp34_ = g_strdup ("");
#line 131 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_free0 (self->content_type);
#line 131 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->content_type = _tmp34_;
#line 132 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_error_free0 (e);
#line 132 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (file);
#line 132 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return self;
#line 759 "FakeServer.vala.c"
	}
	__finally11:
#line 115 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 115 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (file);
#line 115 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 115 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		g_clear_error (&_inner_error_);
#line 115 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return NULL;
#line 772 "FakeServer.vala.c"
	}
#line 101 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_object_unref0 (file);
#line 101 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return self;
#line 778 "FakeServer.vala.c"
}


FakeServerCache* fake_server_cache_new_from_resource (const gchar* fname) {
#line 101 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return fake_server_cache_construct_from_resource (TYPE_FAKE_SERVER_CACHE, fname);
#line 785 "FakeServer.vala.c"
}


static guint8* _vala_array_dup5 (guint8* self, int length) {
#line 144 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return g_memdup (self, length * sizeof (guint8));
#line 792 "FakeServer.vala.c"
}


static guint8* _vala_array_dup6 (guint8* self, int length) {
#line 160 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return g_memdup (self, length * sizeof (guint8));
#line 799 "FakeServer.vala.c"
}


static guint8* _vala_array_dup7 (guint8* self, int length) {
#line 162 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return g_memdup (self, length * sizeof (guint8));
#line 806 "FakeServer.vala.c"
}


FakeServerCache* fake_server_cache_construct (GType object_type, const gchar* fname) {
	FakeServerCache * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GFile* file = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	GFile* _tmp8_ = NULL;
	GFile* _tmp9_ = NULL;
	GFile* _tmp10_ = NULL;
	gboolean _tmp11_ = FALSE;
	const gchar* _tmp34_ = NULL;
	const gchar* _tmp35_ = NULL;
	gint64 _tmp36_ = 0LL;
	gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
	guint8* _tmp39_ = NULL;
	gint _tmp39__length1 = 0;
	GError * _inner_error_ = NULL;
#line 138 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self = (FakeServerCache*) g_object_new (object_type, NULL);
#line 140 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0_ = fname;
#line 140 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 140 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (self->fname);
#line 140 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->fname = _tmp1_;
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp2_ = g_get_home_dir ();
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp3_ = g_strconcat (_tmp2_, "/gitlive", NULL);
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp4_ = _tmp3_;
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp5_ = fname;
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp6_ = g_strconcat (_tmp4_, _tmp5_, NULL);
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp7_ = _tmp6_;
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp8_ = g_file_new_for_path (_tmp7_);
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp9_ = _tmp8_;
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (_tmp7_);
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (_tmp4_);
#line 142 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	file = _tmp9_;
#line 143 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp10_ = file;
#line 143 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp11_ = g_file_query_exists (_tmp10_, NULL);
#line 143 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (!_tmp11_) {
#line 871 "FakeServer.vala.c"
		guint8* _tmp12_ = NULL;
		gint _tmp12__length1 = 0;
		guint8* _tmp13_ = NULL;
		gint _tmp13__length1 = 0;
		guint8* _tmp14_ = NULL;
		gint _tmp14__length1 = 0;
		gchar* _tmp15_ = NULL;
#line 144 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp12_ = string_get_data ("", &_tmp12__length1);
#line 144 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp13_ = _tmp12_;
#line 144 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp13__length1 = _tmp12__length1;
#line 144 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp14_ = (_tmp13_ != NULL) ? _vala_array_dup5 (_tmp13_, _tmp13__length1) : ((gpointer) _tmp13_);
#line 144 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp14__length1 = _tmp13__length1;
#line 144 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 144 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = _tmp14_;
#line 144 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data_length1 = _tmp14__length1;
#line 145 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp15_ = g_strdup ("");
#line 145 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_free0 (self->content_type);
#line 145 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->content_type = _tmp15_;
#line 146 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->size = (gint64) 0;
#line 147 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (file);
#line 147 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return self;
#line 907 "FakeServer.vala.c"
	}
	{
		GFileInfo* info = NULL;
		GFile* _tmp16_ = NULL;
		GFileInfo* _tmp17_ = NULL;
		GFileInfo* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
		gchar* _tmp20_ = NULL;
		GFileInfo* _tmp21_ = NULL;
		gint64 _tmp22_ = 0LL;
		guint8* data = NULL;
		gint data_length1 = 0;
		gint _data_size_ = 0;
		GFile* _tmp23_ = NULL;
		gchar* _tmp24_ = NULL;
		gchar* _tmp25_ = NULL;
		guint8* _tmp26_ = NULL;
		size_t _tmp27_;
		guint8* _tmp28_ = NULL;
		gint _tmp28__length1 = 0;
		guint8* _tmp29_ = NULL;
		gint _tmp29__length1 = 0;
#line 150 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp16_ = file;
#line 150 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp17_ = g_file_query_info (_tmp16_, "standard::*", G_FILE_QUERY_INFO_NONE, NULL, &_inner_error_);
#line 150 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		info = _tmp17_;
#line 150 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 938 "FakeServer.vala.c"
			goto __catch12_g_error;
		}
#line 154 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp18_ = info;
#line 154 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp19_ = g_file_info_get_content_type (_tmp18_);
#line 154 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp20_ = g_strdup (_tmp19_);
#line 154 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_free0 (self->content_type);
#line 154 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->content_type = _tmp20_;
#line 155 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp21_ = info;
#line 155 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp22_ = g_file_info_get_size (_tmp21_);
#line 155 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->size = _tmp22_;
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp23_ = file;
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp24_ = g_file_get_path (_tmp23_);
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp25_ = _tmp24_;
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		g_file_get_contents (_tmp25_, (gchar**) (&_tmp26_), &_tmp27_, &_inner_error_);
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		data = (g_free (data), NULL);
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		data = _tmp26_;
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		data_length1 = _tmp27_;
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_data_size_ = data_length1;
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_free0 (_tmp25_);
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
			data = (g_free (data), NULL);
#line 159 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
			_g_object_unref0 (info);
#line 981 "FakeServer.vala.c"
			goto __catch12_g_error;
		}
#line 160 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp28_ = data;
#line 160 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp28__length1 = data_length1;
#line 160 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp29_ = (_tmp28_ != NULL) ? _vala_array_dup6 (_tmp28_, _tmp28__length1) : ((gpointer) _tmp28_);
#line 160 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp29__length1 = _tmp28__length1;
#line 160 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 160 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = _tmp29_;
#line 160 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data_length1 = _tmp29__length1;
#line 149 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		data = (g_free (data), NULL);
#line 149 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (info);
#line 1002 "FakeServer.vala.c"
	}
	goto __finally12;
	__catch12_g_error:
	{
		GError* e = NULL;
		guint8* _tmp30_ = NULL;
		gint _tmp30__length1 = 0;
		guint8* _tmp31_ = NULL;
		gint _tmp31__length1 = 0;
		guint8* _tmp32_ = NULL;
		gint _tmp32__length1 = 0;
		gchar* _tmp33_ = NULL;
#line 149 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		e = _inner_error_;
#line 149 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_inner_error_ = NULL;
#line 162 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp30_ = string_get_data ("", &_tmp30__length1);
#line 162 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp31_ = _tmp30_;
#line 162 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp31__length1 = _tmp30__length1;
#line 162 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp32_ = (_tmp31_ != NULL) ? _vala_array_dup7 (_tmp31_, _tmp31__length1) : ((gpointer) _tmp31_);
#line 162 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp32__length1 = _tmp31__length1;
#line 162 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 162 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data = _tmp32_;
#line 162 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->data_length1 = _tmp32__length1;
#line 163 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->size = (gint64) 0;
#line 164 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp33_ = g_strdup ("");
#line 164 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_free0 (self->content_type);
#line 164 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		self->content_type = _tmp33_;
#line 165 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_error_free0 (e);
#line 165 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (file);
#line 165 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return self;
#line 1049 "FakeServer.vala.c"
	}
	__finally12:
#line 149 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 149 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (file);
#line 149 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 149 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		g_clear_error (&_inner_error_);
#line 149 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return NULL;
#line 1062 "FakeServer.vala.c"
	}
#line 170 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp34_ = fname;
#line 170 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp35_ = self->content_type;
#line 170 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp36_ = self->size;
#line 170 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp37_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp36_);
#line 170 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp38_ = _tmp37_;
#line 170 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp39_ = self->data;
#line 170 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp39__length1 = self->data_length1;
#line 170 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	g_print ("FakeServerCache :%s, %s (%s/%d)\n", _tmp34_, _tmp35_, _tmp38_, _tmp39__length1);
#line 170 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (_tmp38_);
#line 138 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_object_unref0 (file);
#line 138 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return self;
#line 1086 "FakeServer.vala.c"
}


FakeServerCache* fake_server_cache_new (const gchar* fname) {
#line 138 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return fake_server_cache_construct (TYPE_FAKE_SERVER_CACHE, fname);
#line 1093 "FakeServer.vala.c"
}


static guint8* _vala_array_dup8 (guint8* self, int length) {
#line 179 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return g_memdup (self, length * sizeof (guint8));
#line 1100 "FakeServer.vala.c"
}


static void _g_free_gdestroy_notify (void* data) {
#line 179 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	g_free (data);
#line 1107 "FakeServer.vala.c"
}


void fake_server_cache_run (FakeServerCache* self, WebKitURISchemeRequest* request, GCancellable* cancellable) {
	GMemoryInputStream* stream = NULL;
	guint8* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	guint8* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	GMemoryInputStream* _tmp2_ = NULL;
	gint64 _tmp3_ = 0LL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	WebKitURISchemeRequest* _tmp6_ = NULL;
	gint64 _tmp7_ = 0LL;
	const gchar* _tmp8_ = NULL;
#line 179 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0_ = self->data;
#line 179 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0__length1 = self->data_length1;
#line 179 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup8 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
#line 179 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp1__length1 = _tmp0__length1;
#line 179 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp2_ = (GMemoryInputStream*) g_memory_input_stream_new_from_data (_tmp1_, _tmp1__length1, _g_free_gdestroy_notify);
#line 179 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	stream = _tmp2_;
#line 180 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp3_ = self->size;
#line 180 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp4_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp3_);
#line 180 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp5_ = _tmp4_;
#line 180 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	g_print ("SEND %s\nwe", _tmp5_);
#line 180 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (_tmp5_);
#line 182 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp6_ = request;
#line 182 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp7_ = self->size;
#line 182 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp8_ = self->content_type;
#line 182 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	webkit_uri_scheme_request_finish (_tmp6_, (GInputStream*) stream, _tmp7_, _tmp8_);
#line 188 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_object_unref0 (stream);
#line 188 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return;
#line 1158 "FakeServer.vala.c"
}


static void fake_server_cache_class_init (FakeServerCacheClass * klass) {
#line 23 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	fake_server_cache_parent_class = g_type_class_peek_parent (klass);
#line 23 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	G_OBJECT_CLASS (klass)->finalize = fake_server_cache_finalize;
#line 1167 "FakeServer.vala.c"
}


static void fake_server_cache_instance_init (FakeServerCache * self) {
}


static void fake_server_cache_finalize (GObject* obj) {
	FakeServerCache * self;
#line 23 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_FAKE_SERVER_CACHE, FakeServerCache);
#line 25 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (self->fname);
#line 26 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->data = (g_free (self->data), NULL);
#line 27 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (self->content_type);
#line 23 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	G_OBJECT_CLASS (fake_server_cache_parent_class)->finalize (obj);
#line 1187 "FakeServer.vala.c"
}


GType fake_server_cache_get_type (void) {
	static volatile gsize fake_server_cache_type_id__volatile = 0;
	if (g_once_init_enter (&fake_server_cache_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FakeServerCacheClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fake_server_cache_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FakeServerCache), 0, (GInstanceInitFunc) fake_server_cache_instance_init, NULL };
		GType fake_server_cache_type_id;
		fake_server_cache_type_id = g_type_register_static (G_TYPE_OBJECT, "FakeServerCache", &g_define_type_info, 0);
		g_once_init_leave (&fake_server_cache_type_id__volatile, fake_server_cache_type_id);
	}
	return fake_server_cache_type_id__volatile;
}


static gpointer _g_object_ref0 (gpointer self) {
#line 201 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return self ? g_object_ref (self) : NULL;
#line 1206 "FakeServer.vala.c"
}


static void _fake_server_serve_web_kit_uri_scheme_request_callback (WebKitURISchemeRequest* request, gpointer self) {
#line 206 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	fake_server_serve ((FakeServer*) self, request);
#line 1213 "FakeServer.vala.c"
}


FakeServer* fake_server_construct (GType object_type, WebKitWebView* wkview) {
	FakeServer * self = NULL;
	WebKitWebView* _tmp0_ = NULL;
	WebKitWebView* _tmp1_ = NULL;
	WebKitWebContext* cx = NULL;
	WebKitWebContext* _tmp2_ = NULL;
	WebKitWebContext* _tmp3_ = NULL;
#line 199 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self = (FakeServer*) g_object_new (object_type, NULL);
#line 201 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0_ = wkview;
#line 201 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 201 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_object_unref0 (self->priv->view);
#line 201 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->priv->view = _tmp1_;
#line 204 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp2_ = webkit_web_context_get_default ();
#line 204 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 204 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	cx = _tmp3_;
#line 206 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	webkit_web_context_register_uri_scheme (cx, "xhttp", _fake_server_serve_web_kit_uri_scheme_request_callback, g_object_ref (self), g_object_unref);
#line 207 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	webkit_web_context_register_uri_scheme (cx, "resources", _fake_server_serve_web_kit_uri_scheme_request_callback, g_object_ref (self), g_object_unref);
#line 208 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	webkit_web_context_set_cache_model (cx, WEBKIT_CACHE_MODEL_DOCUMENT_VIEWER);
#line 199 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_object_unref0 (cx);
#line 199 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return self;
#line 1250 "FakeServer.vala.c"
}


FakeServer* fake_server_new (WebKitWebView* wkview) {
#line 199 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	return fake_server_construct (TYPE_FAKE_SERVER, wkview);
#line 1257 "FakeServer.vala.c"
}


void fake_server_serve (FakeServer* self, WebKitURISchemeRequest* request) {
	WebKitURISchemeRequest* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	FakeServerCache* cdata = NULL;
	WebKitURISchemeRequest* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	WebKitURISchemeRequest* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	FakeServerCache* _tmp6_ = NULL;
	FakeServerCache* _tmp7_ = NULL;
	gint64 _tmp8_ = 0LL;
	WebKitURISchemeRequest* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	FakeServerCache* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	FakeServerCache* _tmp19_ = NULL;
	gint64 _tmp20_ = 0LL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	FakeServerCache* _tmp23_ = NULL;
	guint8* _tmp24_ = NULL;
	gint _tmp24__length1 = 0;
	FakeServerCache* _tmp25_ = NULL;
	WebKitURISchemeRequest* _tmp26_ = NULL;
#line 223 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp0_ = request;
#line 223 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp1_ = webkit_uri_scheme_request_get_path (_tmp0_);
#line 223 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	g_print ("REQ: %s\n", _tmp1_);
#line 224 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp2_ = request;
#line 224 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp3_ = webkit_uri_scheme_request_get_path (_tmp2_);
#line 224 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp4_ = request;
#line 224 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp5_ = webkit_uri_scheme_request_get_scheme (_tmp4_);
#line 224 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp6_ = fake_server_cache_factory (_tmp3_, _tmp5_);
#line 224 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	cdata = _tmp6_;
#line 226 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp7_ = cdata;
#line 226 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp8_ = _tmp7_->size;
#line 226 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	if (_tmp8_ < ((gint64) 1)) {
#line 1309 "FakeServer.vala.c"
		const gchar* _tmp9_ = NULL;
		WebKitURISchemeRequest* _tmp10_ = NULL;
		const gchar* _tmp11_ = NULL;
		WebKitURISchemeRequest* _tmp12_ = NULL;
		GError* _tmp13_ = NULL;
		GError* _tmp14_ = NULL;
#line 227 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp9_ = g_get_home_dir ();
#line 227 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp10_ = request;
#line 227 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp11_ = webkit_uri_scheme_request_get_path (_tmp10_);
#line 227 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		g_print ("Skip file missing = %s/gitlive%s\n", _tmp9_, _tmp11_);
#line 228 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp12_ = request;
#line 228 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp13_ = g_error_new_literal (FAKE_SERVER_ERROR, FAKE_SERVER_ERROR_FILE_DOES_NOT_EXIST, "My error msg");
#line 228 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_tmp14_ = _tmp13_;
#line 228 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		webkit_uri_scheme_request_finish_error (_tmp12_, _tmp14_);
#line 228 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_error_free0 (_tmp14_);
#line 229 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		_g_object_unref0 (cdata);
#line 229 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
		return;
#line 1338 "FakeServer.vala.c"
	}
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp15_ = request;
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp16_ = webkit_uri_scheme_request_get_path (_tmp15_);
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp17_ = cdata;
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp18_ = _tmp17_->content_type;
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp19_ = cdata;
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp20_ = _tmp19_->size;
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp21_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp20_);
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp22_ = _tmp21_;
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp23_ = cdata;
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp24_ = _tmp23_->data;
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp24__length1 = _tmp23_->data_length1;
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	g_print ("Send :%s, %s (%s/%d)", _tmp16_, _tmp18_, _tmp22_, _tmp24__length1);
#line 232 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_free0 (_tmp22_);
#line 234 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp25_ = cdata;
#line 234 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_tmp26_ = request;
#line 234 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	fake_server_cache_run (_tmp25_, _tmp26_, NULL);
#line 219 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_object_unref0 (cdata);
#line 1374 "FakeServer.vala.c"
}


static void fake_server_class_init (FakeServerClass * klass) {
#line 195 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	fake_server_parent_class = g_type_class_peek_parent (klass);
#line 195 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	g_type_class_add_private (klass, sizeof (FakeServerPrivate));
#line 195 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	G_OBJECT_CLASS (klass)->finalize = fake_server_finalize;
#line 1385 "FakeServer.vala.c"
}


static void fake_server_instance_init (FakeServer * self) {
#line 195 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self->priv = FAKE_SERVER_GET_PRIVATE (self);
#line 1392 "FakeServer.vala.c"
}


static void fake_server_finalize (GObject* obj) {
	FakeServer * self;
#line 195 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_FAKE_SERVER, FakeServer);
#line 197 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	_g_object_unref0 (self->priv->view);
#line 195 "/home/alan/gitlive/roobuilder/src/Builder4/FakeServer.vala"
	G_OBJECT_CLASS (fake_server_parent_class)->finalize (obj);
#line 1404 "FakeServer.vala.c"
}


GType fake_server_get_type (void) {
	static volatile gsize fake_server_type_id__volatile = 0;
	if (g_once_init_enter (&fake_server_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FakeServerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fake_server_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FakeServer), 0, (GInstanceInitFunc) fake_server_instance_init, NULL };
		GType fake_server_type_id;
		fake_server_type_id = g_type_register_static (G_TYPE_OBJECT, "FakeServer", &g_define_type_info, 0);
		g_once_init_leave (&fake_server_type_id__volatile, fake_server_type_id);
	}
	return fake_server_type_id__volatile;
}



