/* FakeServer.vala.c generated by valac, the Vala compiler
 * generated from FakeServer.vala, do not modify */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gio/gio.h>
#include <glib/gstdio.h>
#include <webkit/webkit.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_FAKE_SERVER_CACHE (fake_server_cache_get_type ())
#define FAKE_SERVER_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FAKE_SERVER_CACHE, FakeServerCache))
#define FAKE_SERVER_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FAKE_SERVER_CACHE, FakeServerCacheClass))
#define IS_FAKE_SERVER_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FAKE_SERVER_CACHE))
#define IS_FAKE_SERVER_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FAKE_SERVER_CACHE))
#define FAKE_SERVER_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FAKE_SERVER_CACHE, FakeServerCacheClass))

typedef struct _FakeServerCache FakeServerCache;
typedef struct _FakeServerCacheClass FakeServerCacheClass;
typedef struct _FakeServerCachePrivate FakeServerCachePrivate;
enum  {
	FAKE_SERVER_CACHE_0_PROPERTY,
	FAKE_SERVER_CACHE_NUM_PROPERTIES
};
static GParamSpec* fake_server_cache_properties[FAKE_SERVER_CACHE_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_FAKE_SERVER (fake_server_get_type ())
#define FAKE_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FAKE_SERVER, FakeServer))
#define FAKE_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FAKE_SERVER, FakeServerClass))
#define IS_FAKE_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FAKE_SERVER))
#define IS_FAKE_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FAKE_SERVER))
#define FAKE_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FAKE_SERVER, FakeServerClass))

typedef struct _FakeServer FakeServer;
typedef struct _FakeServerClass FakeServerClass;
typedef struct _FakeServerPrivate FakeServerPrivate;
enum  {
	FAKE_SERVER_0_PROPERTY,
	FAKE_SERVER_NUM_PROPERTIES
};
static GParamSpec* fake_server_properties[FAKE_SERVER_NUM_PROPERTIES];
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

/**
 * Originally this was supposed to intercept http calls and redirect them
 * but that is not supported in webkit2 (without using the extension api)
 * 
 * so for now we have modified our server to serve use a base url of xhttp:
 * 
 * so all relative urls are based on that 
 * 
 * Idea is to serve the files from the file system, so no need to setup apache etc...
 * This should work for the static content like css / javascript etc.. but 
 * will cause issues with 'dynamic' xhr files (eg. the php stuff)
 *
 * the idea is nicked from geary.
 * 
 * At present this serves from ~/gitlive/****  - that probably needs more thought..
 * 
 * 
 */
typedef enum  {
	FAKE_SERVER_ERROR_FILE_DOES_NOT_EXIST
} FakeServerError;
#define FAKE_SERVER_ERROR fake_server_error_quark ()
struct _FakeServerCache {
	GObject parent_instance;
	FakeServerCachePrivate * priv;
	gchar* fname;
	guint8* data;
	gint data_length1;
	gchar* content_type;
	gint64 size;
};

struct _FakeServerCacheClass {
	GObjectClass parent_class;
};

struct _FakeServer {
	GObject parent_instance;
	FakeServerPrivate * priv;
};

struct _FakeServerClass {
	GObjectClass parent_class;
};

struct _FakeServerPrivate {
	WebKitWebView* view;
};

static gpointer fake_server_cache_parent_class = NULL;
VALA_EXTERN GeeHashMap* fake_server_cache_cache;
GeeHashMap* fake_server_cache_cache = NULL;
static gint FakeServer_private_offset;
static gpointer fake_server_parent_class = NULL;

VALA_EXTERN GQuark fake_server_error_quark (void);
VALA_EXTERN GType fake_server_cache_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FakeServerCache, g_object_unref)
VALA_EXTERN FakeServerCache* fake_server_cache_factory (const gchar* fname,
                                            const gchar* scheme);
VALA_EXTERN FakeServerCache* fake_server_cache_new_from_resource (const gchar* fname);
VALA_EXTERN FakeServerCache* fake_server_cache_construct_from_resource (GType object_type,
                                                            const gchar* fname);
VALA_EXTERN FakeServerCache* fake_server_cache_new (const gchar* fname);
VALA_EXTERN FakeServerCache* fake_server_cache_construct (GType object_type,
                                              const gchar* fname);
VALA_EXTERN void fake_server_cache_remove (const gchar* fname);
VALA_EXTERN void fake_server_cache_clear (void);
VALA_EXTERN FakeServerCache* fake_server_cache_factory_with_data (const gchar* data);
VALA_EXTERN FakeServerCache* fake_server_cache_new_with_data (const gchar* data);
VALA_EXTERN FakeServerCache* fake_server_cache_construct_with_data (GType object_type,
                                                        const gchar* data);
static guint8* _vala_array_dup1 (guint8* self,
                          gssize length);
VALA_EXTERN gchar* builder_application_configDirectory (void);
static guint8* _vala_array_dup2 (guint8* self,
                          gssize length);
static guint8* _vala_array_dup3 (guint8* self,
                          gssize length);
static guint8* _vala_array_dup4 (guint8* self,
                          gssize length);
static guint8* _vala_array_dup5 (guint8* self,
                          gssize length);
static guint8* _vala_array_dup6 (guint8* self,
                          gssize length);
static guint8* _vala_array_dup7 (guint8* self,
                          gssize length);
VALA_EXTERN void fake_server_cache_run (FakeServerCache* self,
                            WebKitURISchemeRequest* request,
                            GCancellable* cancellable);
static guint8* _vala_array_dup8 (guint8* self,
                          gssize length);
static void _g_free_gdestroy_notify (void* data);
static void fake_server_cache_finalize (GObject * obj);
static GType fake_server_cache_get_type_once (void);
VALA_EXTERN GType fake_server_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FakeServer, g_object_unref)
VALA_EXTERN FakeServer* fake_server_new (WebKitWebView* wkview);
VALA_EXTERN FakeServer* fake_server_construct (GType object_type,
                                   WebKitWebView* wkview);
VALA_EXTERN void fake_server_serve (FakeServer* self,
                        WebKitURISchemeRequest* request);
static void _fake_server_serve_web_kit_uri_scheme_request_callback (WebKitURISchemeRequest* request,
                                                             gpointer self);
static void fake_server_finalize (GObject * obj);
static GType fake_server_get_type_once (void);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

GQuark
fake_server_error_quark (void)
{
	return g_quark_from_static_string ("fake-server-error-quark");
}

FakeServerCache*
fake_server_cache_factory (const gchar* fname,
                           const gchar* scheme)
{
	GeeHashMap* _tmp0_;
	GeeHashMap* _tmp3_;
	FakeServerCache* el = NULL;
	FakeServerCache* _tmp6_;
	GeeHashMap* _tmp7_;
	FakeServerCache* _tmp8_;
	FakeServerCache* result;
#line 34 "FakeServer.vala"
	_tmp0_ = fake_server_cache_cache;
#line 34 "FakeServer.vala"
	if (_tmp0_ == NULL) {
#line 189 "FakeServer.vala.c"
		GeeHashMap* _tmp1_;
#line 35 "FakeServer.vala"
		_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, TYPE_FAKE_SERVER_CACHE, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 35 "FakeServer.vala"
		_g_object_unref0 (fake_server_cache_cache);
#line 35 "FakeServer.vala"
		fake_server_cache_cache = _tmp1_;
#line 197 "FakeServer.vala.c"
	}
#line 39 "FakeServer.vala"
	if (g_strcmp0 (scheme, "resources") == 0) {
#line 201 "FakeServer.vala.c"
		FakeServerCache* _tmp2_;
#line 40 "FakeServer.vala"
		_tmp2_ = fake_server_cache_new_from_resource (fname);
#line 40 "FakeServer.vala"
		result = _tmp2_;
#line 40 "FakeServer.vala"
		return result;
#line 209 "FakeServer.vala.c"
	}
#line 43 "FakeServer.vala"
	_tmp3_ = fake_server_cache_cache;
#line 43 "FakeServer.vala"
	if (gee_abstract_map_has_key ((GeeAbstractMap*) _tmp3_, fname)) {
#line 215 "FakeServer.vala.c"
		GeeHashMap* _tmp4_;
		gpointer _tmp5_;
#line 44 "FakeServer.vala"
		g_print ("CACHE got  %s\n", fname);
#line 45 "FakeServer.vala"
		_tmp4_ = fake_server_cache_cache;
#line 45 "FakeServer.vala"
		_tmp5_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp4_, fname);
#line 45 "FakeServer.vala"
		result = (FakeServerCache*) _tmp5_;
#line 45 "FakeServer.vala"
		return result;
#line 228 "FakeServer.vala.c"
	}
#line 47 "FakeServer.vala"
	g_print ("CACHE create %s\n", fname);
#line 49 "FakeServer.vala"
	_tmp6_ = fake_server_cache_new (fname);
#line 49 "FakeServer.vala"
	el = _tmp6_;
#line 51 "FakeServer.vala"
	_tmp7_ = fake_server_cache_cache;
#line 51 "FakeServer.vala"
	_tmp8_ = el;
#line 51 "FakeServer.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp7_, fname, _tmp8_);
#line 52 "FakeServer.vala"
	result = el;
#line 52 "FakeServer.vala"
	return result;
#line 246 "FakeServer.vala.c"
}

void
fake_server_cache_remove (const gchar* fname)
{
	GeeHashMap* _tmp0_;
	GeeHashMap* _tmp1_;
	FakeServerCache* v = NULL;
	GeeHashMap* _tmp2_;
	gpointer _tmp3_ = NULL;
#line 56 "FakeServer.vala"
	_tmp0_ = fake_server_cache_cache;
#line 56 "FakeServer.vala"
	if (_tmp0_ == NULL) {
#line 57 "FakeServer.vala"
		return;
#line 263 "FakeServer.vala.c"
	}
#line 59 "FakeServer.vala"
	_tmp1_ = fake_server_cache_cache;
#line 59 "FakeServer.vala"
	if (!gee_abstract_map_has_key ((GeeAbstractMap*) _tmp1_, fname)) {
#line 60 "FakeServer.vala"
		return;
#line 271 "FakeServer.vala.c"
	}
#line 66 "FakeServer.vala"
	_tmp2_ = fake_server_cache_cache;
#line 66 "FakeServer.vala"
	gee_abstract_map_unset ((GeeAbstractMap*) _tmp2_, fname, &_tmp3_);
#line 66 "FakeServer.vala"
	_g_object_unref0 (v);
#line 66 "FakeServer.vala"
	v = _tmp3_;
#line 55 "FakeServer.vala"
	_g_object_unref0 (v);
#line 283 "FakeServer.vala.c"
}

void
fake_server_cache_clear (void)
{
	GeeHashMap* _tmp0_;
	GeeHashMap* _tmp1_;
#line 73 "FakeServer.vala"
	_tmp0_ = fake_server_cache_cache;
#line 73 "FakeServer.vala"
	if (_tmp0_ == NULL) {
#line 74 "FakeServer.vala"
		return;
#line 297 "FakeServer.vala.c"
	}
#line 76 "FakeServer.vala"
	_tmp1_ = fake_server_cache_cache;
#line 76 "FakeServer.vala"
	gee_abstract_map_clear ((GeeAbstractMap*) _tmp1_);
#line 303 "FakeServer.vala.c"
}

FakeServerCache*
fake_server_cache_factory_with_data (const gchar* data)
{
	GeeHashMap* _tmp0_;
	FakeServerCache* el = NULL;
	FakeServerCache* _tmp2_;
	const gchar* _tmp3_;
	GeeHashMap* _tmp4_;
	const gchar* _tmp5_;
	FakeServerCache* result;
#line 80 "FakeServer.vala"
	_tmp0_ = fake_server_cache_cache;
#line 80 "FakeServer.vala"
	if (_tmp0_ == NULL) {
#line 320 "FakeServer.vala.c"
		GeeHashMap* _tmp1_;
#line 81 "FakeServer.vala"
		_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, TYPE_FAKE_SERVER_CACHE, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 81 "FakeServer.vala"
		_g_object_unref0 (fake_server_cache_cache);
#line 81 "FakeServer.vala"
		fake_server_cache_cache = _tmp1_;
#line 328 "FakeServer.vala.c"
	}
#line 83 "FakeServer.vala"
	_tmp2_ = fake_server_cache_new_with_data (data);
#line 83 "FakeServer.vala"
	el = _tmp2_;
#line 84 "FakeServer.vala"
	_tmp3_ = el->fname;
#line 84 "FakeServer.vala"
	g_print ("CACHE - store %s\n", _tmp3_);
#line 85 "FakeServer.vala"
	_tmp4_ = fake_server_cache_cache;
#line 85 "FakeServer.vala"
	_tmp5_ = el->fname;
#line 85 "FakeServer.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp4_, _tmp5_, el);
#line 86 "FakeServer.vala"
	result = el;
#line 86 "FakeServer.vala"
	return result;
#line 348 "FakeServer.vala.c"
}

static guint8*
string_get_data (const gchar* self,
                 gint* result_length1)
{
	guint8* result;
	guint8* res = NULL;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	gint _tmp1_;
	guint8* _tmp2_;
	gint _tmp2__length1;
#line 1564 "glib-2.0.vapi"
	res = (guint8*) self;
#line 1564 "glib-2.0.vapi"
	res_length1 = -1;
#line 1564 "glib-2.0.vapi"
	_res_size_ = res_length1;
#line 1565 "glib-2.0.vapi"
	_tmp0_ = strlen (self);
#line 1565 "glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 1565 "glib-2.0.vapi"
	res_length1 = (gint) _tmp1_;
#line 1566 "glib-2.0.vapi"
	_tmp2_ = res;
#line 1566 "glib-2.0.vapi"
	_tmp2__length1 = res_length1;
#line 1566 "glib-2.0.vapi"
	if (result_length1) {
#line 1566 "glib-2.0.vapi"
		*result_length1 = _tmp2__length1;
#line 383 "FakeServer.vala.c"
	}
#line 1566 "glib-2.0.vapi"
	result = _tmp2_;
#line 1566 "glib-2.0.vapi"
	return result;
#line 389 "FakeServer.vala.c"
}

static guint8*
_vala_array_dup1 (guint8* self,
                  gssize length)
{
#line 95 "FakeServer.vala"
	if (length > 0) {
#line 95 "FakeServer.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 400 "FakeServer.vala.c"
	}
#line 95 "FakeServer.vala"
	return NULL;
#line 404 "FakeServer.vala.c"
}

FakeServerCache*
fake_server_cache_construct_with_data (GType object_type,
                                       const gchar* data)
{
	FakeServerCache * self = NULL;
	gint _tmp0_;
	gint _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	guint8* _tmp7_;
	gint _tmp7__length1;
	gint _tmp8_ = 0;
	guint8* _tmp9_;
	gint _tmp9__length1;
	guint8* _tmp10_;
	gint _tmp10__length1;
	gchar* _tmp11_;
	gint _tmp12_;
	gint _tmp13_;
#line 92 "FakeServer.vala"
	self = (FakeServerCache*) g_object_new (object_type, NULL);
#line 94 "FakeServer.vala"
	_tmp0_ = strlen (data);
#line 94 "FakeServer.vala"
	_tmp1_ = _tmp0_;
#line 94 "FakeServer.vala"
	_tmp2_ = g_compute_checksum_for_string (G_CHECKSUM_MD5, data, (gsize) _tmp1_);
#line 94 "FakeServer.vala"
	_tmp3_ = _tmp2_;
#line 94 "FakeServer.vala"
	_tmp4_ = g_strconcat ("/", _tmp3_, NULL);
#line 94 "FakeServer.vala"
	_tmp5_ = _tmp4_;
#line 94 "FakeServer.vala"
	_tmp6_ = g_strconcat (_tmp5_, ".js", NULL);
#line 94 "FakeServer.vala"
	_g_free0 (self->fname);
#line 94 "FakeServer.vala"
	self->fname = _tmp6_;
#line 94 "FakeServer.vala"
	_g_free0 (_tmp5_);
#line 94 "FakeServer.vala"
	_g_free0 (_tmp3_);
#line 95 "FakeServer.vala"
	_tmp7_ = string_get_data (data, &_tmp8_);
#line 95 "FakeServer.vala"
	_tmp7__length1 = _tmp8_;
#line 95 "FakeServer.vala"
	_tmp9_ = _tmp7_;
#line 95 "FakeServer.vala"
	_tmp9__length1 = _tmp7__length1;
#line 95 "FakeServer.vala"
	_tmp10_ = (_tmp9_ != NULL) ? _vala_array_dup1 (_tmp9_, _tmp9__length1) : _tmp9_;
#line 95 "FakeServer.vala"
	_tmp10__length1 = _tmp9__length1;
#line 95 "FakeServer.vala"
	self->data = (g_free (self->data), NULL);
#line 95 "FakeServer.vala"
	self->data = _tmp10_;
#line 95 "FakeServer.vala"
	self->data_length1 = _tmp10__length1;
#line 96 "FakeServer.vala"
	_tmp11_ = g_strdup ("text/javascript;charset=UTF-8");
#line 96 "FakeServer.vala"
	_g_free0 (self->content_type);
#line 96 "FakeServer.vala"
	self->content_type = _tmp11_;
#line 97 "FakeServer.vala"
	_tmp12_ = strlen (data);
#line 97 "FakeServer.vala"
	_tmp13_ = _tmp12_;
#line 97 "FakeServer.vala"
	self->size = (gint64) _tmp13_;
#line 92 "FakeServer.vala"
	return self;
#line 485 "FakeServer.vala.c"
}

FakeServerCache*
fake_server_cache_new_with_data (const gchar* data)
{
#line 92 "FakeServer.vala"
	return fake_server_cache_construct_with_data (TYPE_FAKE_SERVER_CACHE, data);
#line 493 "FakeServer.vala.c"
}

static guint8*
_vala_array_dup2 (guint8* self,
                  gssize length)
{
#line 110 "FakeServer.vala"
	if (length > 0) {
#line 110 "FakeServer.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 504 "FakeServer.vala.c"
	}
#line 110 "FakeServer.vala"
	return NULL;
#line 508 "FakeServer.vala.c"
}

static guint8*
_vala_array_dup3 (guint8* self,
                  gssize length)
{
#line 127 "FakeServer.vala"
	if (length > 0) {
#line 127 "FakeServer.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 519 "FakeServer.vala.c"
	}
#line 127 "FakeServer.vala"
	return NULL;
#line 523 "FakeServer.vala.c"
}

static guint8*
_vala_array_dup4 (guint8* self,
                  gssize length)
{
#line 129 "FakeServer.vala"
	if (length > 0) {
#line 129 "FakeServer.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 534 "FakeServer.vala.c"
	}
#line 129 "FakeServer.vala"
	return NULL;
#line 538 "FakeServer.vala.c"
}

FakeServerCache*
fake_server_cache_construct_from_resource (GType object_type,
                                           const gchar* fname)
{
	FakeServerCache * self = NULL;
	gchar* _tmp0_;
	GFile* file = NULL;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	GFile* _tmp7_;
	GFile* _tmp8_;
	GFile* _tmp9_;
	GError* _inner_error0_ = NULL;
#line 101 "FakeServer.vala"
	self = (FakeServerCache*) g_object_new (object_type, NULL);
#line 106 "FakeServer.vala"
	_tmp0_ = g_strdup (fname);
#line 106 "FakeServer.vala"
	_g_free0 (self->fname);
#line 106 "FakeServer.vala"
	self->fname = _tmp0_;
#line 108 "FakeServer.vala"
	_tmp1_ = builder_application_configDirectory ();
#line 108 "FakeServer.vala"
	_tmp2_ = _tmp1_;
#line 108 "FakeServer.vala"
	_tmp3_ = g_strconcat (_tmp2_, "/resources/", NULL);
#line 108 "FakeServer.vala"
	_tmp4_ = _tmp3_;
#line 108 "FakeServer.vala"
	_tmp5_ = g_strconcat (_tmp4_, fname, NULL);
#line 108 "FakeServer.vala"
	_tmp6_ = _tmp5_;
#line 108 "FakeServer.vala"
	_tmp7_ = g_file_new_for_path (_tmp6_);
#line 108 "FakeServer.vala"
	_tmp8_ = _tmp7_;
#line 108 "FakeServer.vala"
	_g_free0 (_tmp6_);
#line 108 "FakeServer.vala"
	_g_free0 (_tmp4_);
#line 108 "FakeServer.vala"
	_g_free0 (_tmp2_);
#line 108 "FakeServer.vala"
	file = _tmp8_;
#line 109 "FakeServer.vala"
	_tmp9_ = file;
#line 109 "FakeServer.vala"
	if (!g_file_query_exists (_tmp9_, NULL)) {
#line 594 "FakeServer.vala.c"
		guint8* _tmp10_;
		gint _tmp10__length1;
		gint _tmp11_ = 0;
		guint8* _tmp12_;
		gint _tmp12__length1;
		guint8* _tmp13_;
		gint _tmp13__length1;
		gchar* _tmp14_;
#line 110 "FakeServer.vala"
		_tmp10_ = string_get_data ("", &_tmp11_);
#line 110 "FakeServer.vala"
		_tmp10__length1 = _tmp11_;
#line 110 "FakeServer.vala"
		_tmp12_ = _tmp10_;
#line 110 "FakeServer.vala"
		_tmp12__length1 = _tmp10__length1;
#line 110 "FakeServer.vala"
		_tmp13_ = (_tmp12_ != NULL) ? _vala_array_dup2 (_tmp12_, _tmp12__length1) : _tmp12_;
#line 110 "FakeServer.vala"
		_tmp13__length1 = _tmp12__length1;
#line 110 "FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 110 "FakeServer.vala"
		self->data = _tmp13_;
#line 110 "FakeServer.vala"
		self->data_length1 = _tmp13__length1;
#line 111 "FakeServer.vala"
		_tmp14_ = g_strdup ("");
#line 111 "FakeServer.vala"
		_g_free0 (self->content_type);
#line 111 "FakeServer.vala"
		self->content_type = _tmp14_;
#line 112 "FakeServer.vala"
		self->size = (gint64) 0;
#line 113 "FakeServer.vala"
		_g_object_unref0 (file);
#line 113 "FakeServer.vala"
		return self;
#line 633 "FakeServer.vala.c"
	}
	{
		GFileInfo* info = NULL;
		GFile* _tmp15_;
		GFileInfo* _tmp16_;
		GFileInfo* _tmp17_;
		const gchar* _tmp18_;
		gchar* _tmp19_;
		GFileInfo* _tmp20_;
		guint8* data = NULL;
		gint data_length1 = 0;
		gint _data_size_ = 0;
		GFile* _tmp21_;
		gchar* _tmp22_;
		gchar* _tmp23_;
		guint8* _tmp24_ = NULL;
		gsize _tmp25_ = 0;
		guint8* _tmp26_;
		gint _tmp26__length1;
		guint8* _tmp27_;
		gint _tmp27__length1;
#line 116 "FakeServer.vala"
		_tmp15_ = file;
#line 116 "FakeServer.vala"
		_tmp16_ = g_file_query_info (_tmp15_, "standard::*", G_FILE_QUERY_INFO_NONE, NULL, &_inner_error0_);
#line 116 "FakeServer.vala"
		info = _tmp16_;
#line 116 "FakeServer.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 663 "FakeServer.vala.c"
			goto __catch0_g_error;
		}
#line 121 "FakeServer.vala"
		_tmp17_ = info;
#line 121 "FakeServer.vala"
		_tmp18_ = g_file_info_get_content_type (_tmp17_);
#line 121 "FakeServer.vala"
		_tmp19_ = g_strdup (_tmp18_);
#line 121 "FakeServer.vala"
		_g_free0 (self->content_type);
#line 121 "FakeServer.vala"
		self->content_type = _tmp19_;
#line 122 "FakeServer.vala"
		_tmp20_ = info;
#line 122 "FakeServer.vala"
		self->size = g_file_info_get_size (_tmp20_);
#line 126 "FakeServer.vala"
		_tmp21_ = file;
#line 126 "FakeServer.vala"
		_tmp22_ = g_file_get_path (_tmp21_);
#line 126 "FakeServer.vala"
		_tmp23_ = _tmp22_;
#line 126 "FakeServer.vala"
		g_file_get_contents (_tmp23_, (gchar**) (&_tmp24_), &_tmp25_, &_inner_error0_);
#line 126 "FakeServer.vala"
		data = (g_free (data), NULL);
#line 126 "FakeServer.vala"
		data = _tmp24_;
#line 126 "FakeServer.vala"
		data_length1 = _tmp25_;
#line 126 "FakeServer.vala"
		_data_size_ = data_length1;
#line 126 "FakeServer.vala"
		_g_free0 (_tmp23_);
#line 126 "FakeServer.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 126 "FakeServer.vala"
			data = (g_free (data), NULL);
#line 126 "FakeServer.vala"
			_g_object_unref0 (info);
#line 704 "FakeServer.vala.c"
			goto __catch0_g_error;
		}
#line 127 "FakeServer.vala"
		_tmp26_ = data;
#line 127 "FakeServer.vala"
		_tmp26__length1 = data_length1;
#line 127 "FakeServer.vala"
		_tmp27_ = (_tmp26_ != NULL) ? _vala_array_dup3 (_tmp26_, _tmp26__length1) : _tmp26_;
#line 127 "FakeServer.vala"
		_tmp27__length1 = _tmp26__length1;
#line 127 "FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 127 "FakeServer.vala"
		self->data = _tmp27_;
#line 127 "FakeServer.vala"
		self->data_length1 = _tmp27__length1;
#line 115 "FakeServer.vala"
		data = (g_free (data), NULL);
#line 115 "FakeServer.vala"
		_g_object_unref0 (info);
#line 725 "FakeServer.vala.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		guint8* _tmp28_;
		gint _tmp28__length1;
		gint _tmp29_ = 0;
		guint8* _tmp30_;
		gint _tmp30__length1;
		guint8* _tmp31_;
		gint _tmp31__length1;
		gchar* _tmp32_;
#line 115 "FakeServer.vala"
		g_clear_error (&_inner_error0_);
#line 129 "FakeServer.vala"
		_tmp28_ = string_get_data ("", &_tmp29_);
#line 129 "FakeServer.vala"
		_tmp28__length1 = _tmp29_;
#line 129 "FakeServer.vala"
		_tmp30_ = _tmp28_;
#line 129 "FakeServer.vala"
		_tmp30__length1 = _tmp28__length1;
#line 129 "FakeServer.vala"
		_tmp31_ = (_tmp30_ != NULL) ? _vala_array_dup4 (_tmp30_, _tmp30__length1) : _tmp30_;
#line 129 "FakeServer.vala"
		_tmp31__length1 = _tmp30__length1;
#line 129 "FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 129 "FakeServer.vala"
		self->data = _tmp31_;
#line 129 "FakeServer.vala"
		self->data_length1 = _tmp31__length1;
#line 130 "FakeServer.vala"
		self->size = (gint64) 0;
#line 131 "FakeServer.vala"
		_tmp32_ = g_strdup ("");
#line 131 "FakeServer.vala"
		_g_free0 (self->content_type);
#line 131 "FakeServer.vala"
		self->content_type = _tmp32_;
#line 132 "FakeServer.vala"
		_g_object_unref0 (file);
#line 132 "FakeServer.vala"
		return self;
#line 770 "FakeServer.vala.c"
	}
	__finally0:
#line 115 "FakeServer.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 115 "FakeServer.vala"
		_g_object_unref0 (file);
#line 115 "FakeServer.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 115 "FakeServer.vala"
		g_clear_error (&_inner_error0_);
#line 115 "FakeServer.vala"
		return NULL;
#line 783 "FakeServer.vala.c"
	}
#line 101 "FakeServer.vala"
	_g_object_unref0 (file);
#line 101 "FakeServer.vala"
	return self;
#line 789 "FakeServer.vala.c"
}

FakeServerCache*
fake_server_cache_new_from_resource (const gchar* fname)
{
#line 101 "FakeServer.vala"
	return fake_server_cache_construct_from_resource (TYPE_FAKE_SERVER_CACHE, fname);
#line 797 "FakeServer.vala.c"
}

static guint8*
_vala_array_dup5 (guint8* self,
                  gssize length)
{
#line 144 "FakeServer.vala"
	if (length > 0) {
#line 144 "FakeServer.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 808 "FakeServer.vala.c"
	}
#line 144 "FakeServer.vala"
	return NULL;
#line 812 "FakeServer.vala.c"
}

static guint8*
_vala_array_dup6 (guint8* self,
                  gssize length)
{
#line 160 "FakeServer.vala"
	if (length > 0) {
#line 160 "FakeServer.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 823 "FakeServer.vala.c"
	}
#line 160 "FakeServer.vala"
	return NULL;
#line 827 "FakeServer.vala.c"
}

static guint8*
_vala_array_dup7 (guint8* self,
                  gssize length)
{
#line 162 "FakeServer.vala"
	if (length > 0) {
#line 162 "FakeServer.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 838 "FakeServer.vala.c"
	}
#line 162 "FakeServer.vala"
	return NULL;
#line 842 "FakeServer.vala.c"
}

FakeServerCache*
fake_server_cache_construct (GType object_type,
                             const gchar* fname)
{
	FakeServerCache * self = NULL;
	gchar* _tmp0_;
	GFile* file = NULL;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GFile* _tmp6_;
	GFile* _tmp7_;
	GFile* _tmp8_;
	const gchar* _tmp32_;
	gchar* _tmp33_;
	gchar* _tmp34_;
	guint8* _tmp35_;
	gint _tmp35__length1;
	GError* _inner_error0_ = NULL;
#line 138 "FakeServer.vala"
	self = (FakeServerCache*) g_object_new (object_type, NULL);
#line 140 "FakeServer.vala"
	_tmp0_ = g_strdup (fname);
#line 140 "FakeServer.vala"
	_g_free0 (self->fname);
#line 140 "FakeServer.vala"
	self->fname = _tmp0_;
#line 142 "FakeServer.vala"
	_tmp1_ = g_get_home_dir ();
#line 142 "FakeServer.vala"
	_tmp2_ = g_strconcat (_tmp1_, "/gitlive", NULL);
#line 142 "FakeServer.vala"
	_tmp3_ = _tmp2_;
#line 142 "FakeServer.vala"
	_tmp4_ = g_strconcat (_tmp3_, fname, NULL);
#line 142 "FakeServer.vala"
	_tmp5_ = _tmp4_;
#line 142 "FakeServer.vala"
	_tmp6_ = g_file_new_for_path (_tmp5_);
#line 142 "FakeServer.vala"
	_tmp7_ = _tmp6_;
#line 142 "FakeServer.vala"
	_g_free0 (_tmp5_);
#line 142 "FakeServer.vala"
	_g_free0 (_tmp3_);
#line 142 "FakeServer.vala"
	file = _tmp7_;
#line 143 "FakeServer.vala"
	_tmp8_ = file;
#line 143 "FakeServer.vala"
	if (!g_file_query_exists (_tmp8_, NULL)) {
#line 898 "FakeServer.vala.c"
		guint8* _tmp9_;
		gint _tmp9__length1;
		gint _tmp10_ = 0;
		guint8* _tmp11_;
		gint _tmp11__length1;
		guint8* _tmp12_;
		gint _tmp12__length1;
		gchar* _tmp13_;
#line 144 "FakeServer.vala"
		_tmp9_ = string_get_data ("", &_tmp10_);
#line 144 "FakeServer.vala"
		_tmp9__length1 = _tmp10_;
#line 144 "FakeServer.vala"
		_tmp11_ = _tmp9_;
#line 144 "FakeServer.vala"
		_tmp11__length1 = _tmp9__length1;
#line 144 "FakeServer.vala"
		_tmp12_ = (_tmp11_ != NULL) ? _vala_array_dup5 (_tmp11_, _tmp11__length1) : _tmp11_;
#line 144 "FakeServer.vala"
		_tmp12__length1 = _tmp11__length1;
#line 144 "FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 144 "FakeServer.vala"
		self->data = _tmp12_;
#line 144 "FakeServer.vala"
		self->data_length1 = _tmp12__length1;
#line 145 "FakeServer.vala"
		_tmp13_ = g_strdup ("");
#line 145 "FakeServer.vala"
		_g_free0 (self->content_type);
#line 145 "FakeServer.vala"
		self->content_type = _tmp13_;
#line 146 "FakeServer.vala"
		self->size = (gint64) 0;
#line 147 "FakeServer.vala"
		_g_object_unref0 (file);
#line 147 "FakeServer.vala"
		return self;
#line 937 "FakeServer.vala.c"
	}
	{
		GFileInfo* info = NULL;
		GFile* _tmp14_;
		GFileInfo* _tmp15_;
		GFileInfo* _tmp16_;
		const gchar* _tmp17_;
		gchar* _tmp18_;
		GFileInfo* _tmp19_;
		guint8* data = NULL;
		gint data_length1 = 0;
		gint _data_size_ = 0;
		GFile* _tmp20_;
		gchar* _tmp21_;
		gchar* _tmp22_;
		guint8* _tmp23_ = NULL;
		gsize _tmp24_ = 0;
		guint8* _tmp25_;
		gint _tmp25__length1;
		guint8* _tmp26_;
		gint _tmp26__length1;
#line 150 "FakeServer.vala"
		_tmp14_ = file;
#line 150 "FakeServer.vala"
		_tmp15_ = g_file_query_info (_tmp14_, "standard::*", G_FILE_QUERY_INFO_NONE, NULL, &_inner_error0_);
#line 150 "FakeServer.vala"
		info = _tmp15_;
#line 150 "FakeServer.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 967 "FakeServer.vala.c"
			goto __catch0_g_error;
		}
#line 154 "FakeServer.vala"
		_tmp16_ = info;
#line 154 "FakeServer.vala"
		_tmp17_ = g_file_info_get_content_type (_tmp16_);
#line 154 "FakeServer.vala"
		_tmp18_ = g_strdup (_tmp17_);
#line 154 "FakeServer.vala"
		_g_free0 (self->content_type);
#line 154 "FakeServer.vala"
		self->content_type = _tmp18_;
#line 155 "FakeServer.vala"
		_tmp19_ = info;
#line 155 "FakeServer.vala"
		self->size = g_file_info_get_size (_tmp19_);
#line 159 "FakeServer.vala"
		_tmp20_ = file;
#line 159 "FakeServer.vala"
		_tmp21_ = g_file_get_path (_tmp20_);
#line 159 "FakeServer.vala"
		_tmp22_ = _tmp21_;
#line 159 "FakeServer.vala"
		g_file_get_contents (_tmp22_, (gchar**) (&_tmp23_), &_tmp24_, &_inner_error0_);
#line 159 "FakeServer.vala"
		data = (g_free (data), NULL);
#line 159 "FakeServer.vala"
		data = _tmp23_;
#line 159 "FakeServer.vala"
		data_length1 = _tmp24_;
#line 159 "FakeServer.vala"
		_data_size_ = data_length1;
#line 159 "FakeServer.vala"
		_g_free0 (_tmp22_);
#line 159 "FakeServer.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 159 "FakeServer.vala"
			data = (g_free (data), NULL);
#line 159 "FakeServer.vala"
			_g_object_unref0 (info);
#line 1008 "FakeServer.vala.c"
			goto __catch0_g_error;
		}
#line 160 "FakeServer.vala"
		_tmp25_ = data;
#line 160 "FakeServer.vala"
		_tmp25__length1 = data_length1;
#line 160 "FakeServer.vala"
		_tmp26_ = (_tmp25_ != NULL) ? _vala_array_dup6 (_tmp25_, _tmp25__length1) : _tmp25_;
#line 160 "FakeServer.vala"
		_tmp26__length1 = _tmp25__length1;
#line 160 "FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 160 "FakeServer.vala"
		self->data = _tmp26_;
#line 160 "FakeServer.vala"
		self->data_length1 = _tmp26__length1;
#line 149 "FakeServer.vala"
		data = (g_free (data), NULL);
#line 149 "FakeServer.vala"
		_g_object_unref0 (info);
#line 1029 "FakeServer.vala.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		guint8* _tmp27_;
		gint _tmp27__length1;
		gint _tmp28_ = 0;
		guint8* _tmp29_;
		gint _tmp29__length1;
		guint8* _tmp30_;
		gint _tmp30__length1;
		gchar* _tmp31_;
#line 149 "FakeServer.vala"
		g_clear_error (&_inner_error0_);
#line 162 "FakeServer.vala"
		_tmp27_ = string_get_data ("", &_tmp28_);
#line 162 "FakeServer.vala"
		_tmp27__length1 = _tmp28_;
#line 162 "FakeServer.vala"
		_tmp29_ = _tmp27_;
#line 162 "FakeServer.vala"
		_tmp29__length1 = _tmp27__length1;
#line 162 "FakeServer.vala"
		_tmp30_ = (_tmp29_ != NULL) ? _vala_array_dup7 (_tmp29_, _tmp29__length1) : _tmp29_;
#line 162 "FakeServer.vala"
		_tmp30__length1 = _tmp29__length1;
#line 162 "FakeServer.vala"
		self->data = (g_free (self->data), NULL);
#line 162 "FakeServer.vala"
		self->data = _tmp30_;
#line 162 "FakeServer.vala"
		self->data_length1 = _tmp30__length1;
#line 163 "FakeServer.vala"
		self->size = (gint64) 0;
#line 164 "FakeServer.vala"
		_tmp31_ = g_strdup ("");
#line 164 "FakeServer.vala"
		_g_free0 (self->content_type);
#line 164 "FakeServer.vala"
		self->content_type = _tmp31_;
#line 165 "FakeServer.vala"
		_g_object_unref0 (file);
#line 165 "FakeServer.vala"
		return self;
#line 1074 "FakeServer.vala.c"
	}
	__finally0:
#line 149 "FakeServer.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 149 "FakeServer.vala"
		_g_object_unref0 (file);
#line 149 "FakeServer.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 149 "FakeServer.vala"
		g_clear_error (&_inner_error0_);
#line 149 "FakeServer.vala"
		return NULL;
#line 1087 "FakeServer.vala.c"
	}
#line 170 "FakeServer.vala"
	_tmp32_ = self->content_type;
#line 170 "FakeServer.vala"
	_tmp33_ = g_strdup_printf ("%" G_GINT64_FORMAT, self->size);
#line 170 "FakeServer.vala"
	_tmp34_ = _tmp33_;
#line 170 "FakeServer.vala"
	_tmp35_ = self->data;
#line 170 "FakeServer.vala"
	_tmp35__length1 = self->data_length1;
#line 170 "FakeServer.vala"
	g_print ("FakeServerCache :%s, %s (%s/%d)\n", fname, _tmp32_, _tmp34_, _tmp35__length1);
#line 170 "FakeServer.vala"
	_g_free0 (_tmp34_);
#line 138 "FakeServer.vala"
	_g_object_unref0 (file);
#line 138 "FakeServer.vala"
	return self;
#line 1107 "FakeServer.vala.c"
}

FakeServerCache*
fake_server_cache_new (const gchar* fname)
{
#line 138 "FakeServer.vala"
	return fake_server_cache_construct (TYPE_FAKE_SERVER_CACHE, fname);
#line 1115 "FakeServer.vala.c"
}

static guint8*
_vala_array_dup8 (guint8* self,
                  gssize length)
{
#line 179 "FakeServer.vala"
	if (length > 0) {
#line 179 "FakeServer.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 1126 "FakeServer.vala.c"
	}
#line 179 "FakeServer.vala"
	return NULL;
#line 1130 "FakeServer.vala.c"
}

static void
_g_free_gdestroy_notify (void* data)
{
#line 179 "FakeServer.vala"
	g_free (data);
#line 1138 "FakeServer.vala.c"
}

void
fake_server_cache_run (FakeServerCache* self,
                       WebKitURISchemeRequest* request,
                       GCancellable* cancellable)
{
	GMemoryInputStream* stream = NULL;
	guint8* _tmp0_;
	gint _tmp0__length1;
	guint8* _tmp1_;
	gint _tmp1__length1;
	GMemoryInputStream* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	const gchar* _tmp5_;
#line 179 "FakeServer.vala"
	_tmp0_ = self->data;
#line 179 "FakeServer.vala"
	_tmp0__length1 = self->data_length1;
#line 179 "FakeServer.vala"
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup8 (_tmp0_, _tmp0__length1) : _tmp0_;
#line 179 "FakeServer.vala"
	_tmp1__length1 = _tmp0__length1;
#line 179 "FakeServer.vala"
	_tmp2_ = (GMemoryInputStream*) g_memory_input_stream_new_from_data (_tmp1_, _tmp1__length1, _g_free_gdestroy_notify);
#line 179 "FakeServer.vala"
	stream = _tmp2_;
#line 180 "FakeServer.vala"
	_tmp3_ = g_strdup_printf ("%" G_GINT64_FORMAT, self->size);
#line 180 "FakeServer.vala"
	_tmp4_ = _tmp3_;
#line 180 "FakeServer.vala"
	g_print ("SEND %s\nwe", _tmp4_);
#line 180 "FakeServer.vala"
	_g_free0 (_tmp4_);
#line 182 "FakeServer.vala"
	_tmp5_ = self->content_type;
#line 182 "FakeServer.vala"
	webkit_uri_scheme_request_finish (request, (GInputStream*) stream, self->size, _tmp5_);
#line 188 "FakeServer.vala"
	_g_object_unref0 (stream);
#line 188 "FakeServer.vala"
	return;
#line 1183 "FakeServer.vala.c"
}

static void
fake_server_cache_class_init (FakeServerCacheClass * klass,
                              gpointer klass_data)
{
#line 23 "FakeServer.vala"
	fake_server_cache_parent_class = g_type_class_peek_parent (klass);
#line 23 "FakeServer.vala"
	G_OBJECT_CLASS (klass)->finalize = fake_server_cache_finalize;
#line 1194 "FakeServer.vala.c"
}

static void
fake_server_cache_instance_init (FakeServerCache * self,
                                 gpointer klass)
{
}

static void
fake_server_cache_finalize (GObject * obj)
{
	FakeServerCache * self;
#line 23 "FakeServer.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_FAKE_SERVER_CACHE, FakeServerCache);
#line 25 "FakeServer.vala"
	_g_free0 (self->fname);
#line 26 "FakeServer.vala"
	self->data = (g_free (self->data), NULL);
#line 27 "FakeServer.vala"
	_g_free0 (self->content_type);
#line 23 "FakeServer.vala"
	G_OBJECT_CLASS (fake_server_cache_parent_class)->finalize (obj);
#line 1217 "FakeServer.vala.c"
}

static GType
fake_server_cache_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (FakeServerCacheClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fake_server_cache_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FakeServerCache), 0, (GInstanceInitFunc) fake_server_cache_instance_init, NULL };
	GType fake_server_cache_type_id;
	fake_server_cache_type_id = g_type_register_static (G_TYPE_OBJECT, "FakeServerCache", &g_define_type_info, 0);
	return fake_server_cache_type_id;
}

GType
fake_server_cache_get_type (void)
{
	static volatile gsize fake_server_cache_type_id__once = 0;
	if (g_once_init_enter (&fake_server_cache_type_id__once)) {
		GType fake_server_cache_type_id;
		fake_server_cache_type_id = fake_server_cache_get_type_once ();
		g_once_init_leave (&fake_server_cache_type_id__once, fake_server_cache_type_id);
	}
	return fake_server_cache_type_id__once;
}

static inline gpointer
fake_server_get_instance_private (FakeServer* self)
{
	return G_STRUCT_MEMBER_P (self, FakeServer_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 201 "FakeServer.vala"
	return self ? g_object_ref (self) : NULL;
#line 1252 "FakeServer.vala.c"
}

static void
_fake_server_serve_web_kit_uri_scheme_request_callback (WebKitURISchemeRequest* request,
                                                        gpointer self)
{
#line 206 "FakeServer.vala"
	fake_server_serve ((FakeServer*) self, request);
#line 1261 "FakeServer.vala.c"
}

FakeServer*
fake_server_construct (GType object_type,
                       WebKitWebView* wkview)
{
	FakeServer * self = NULL;
	WebKitWebView* _tmp0_;
	WebKitWebContext* cx = NULL;
	WebKitWebContext* _tmp1_;
	WebKitWebContext* _tmp2_;
#line 199 "FakeServer.vala"
	self = (FakeServer*) g_object_new (object_type, NULL);
#line 201 "FakeServer.vala"
	_tmp0_ = _g_object_ref0 (wkview);
#line 201 "FakeServer.vala"
	_g_object_unref0 (self->priv->view);
#line 201 "FakeServer.vala"
	self->priv->view = _tmp0_;
#line 204 "FakeServer.vala"
	_tmp1_ = webkit_web_context_get_default ();
#line 204 "FakeServer.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 204 "FakeServer.vala"
	cx = _tmp2_;
#line 206 "FakeServer.vala"
	webkit_web_context_register_uri_scheme (cx, "xhttp", _fake_server_serve_web_kit_uri_scheme_request_callback, g_object_ref (self), g_object_unref);
#line 207 "FakeServer.vala"
	webkit_web_context_register_uri_scheme (cx, "resources", _fake_server_serve_web_kit_uri_scheme_request_callback, g_object_ref (self), g_object_unref);
#line 208 "FakeServer.vala"
	webkit_web_context_set_cache_model (cx, WEBKIT_CACHE_MODEL_DOCUMENT_VIEWER);
#line 199 "FakeServer.vala"
	_g_object_unref0 (cx);
#line 199 "FakeServer.vala"
	return self;
#line 1297 "FakeServer.vala.c"
}

FakeServer*
fake_server_new (WebKitWebView* wkview)
{
#line 199 "FakeServer.vala"
	return fake_server_construct (TYPE_FAKE_SERVER, wkview);
#line 1305 "FakeServer.vala.c"
}

void
fake_server_serve (FakeServer* self,
                   WebKitURISchemeRequest* request)
{
	const gchar* _tmp0_;
	FakeServerCache* cdata = NULL;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	FakeServerCache* _tmp3_;
	FakeServerCache* _tmp4_;
	const gchar* _tmp9_;
	FakeServerCache* _tmp10_;
	const gchar* _tmp11_;
	FakeServerCache* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	FakeServerCache* _tmp15_;
	guint8* _tmp16_;
	gint _tmp16__length1;
	FakeServerCache* _tmp17_;
#line 223 "FakeServer.vala"
	_tmp0_ = webkit_uri_scheme_request_get_path (request);
#line 223 "FakeServer.vala"
	g_print ("REQ: %s\n", _tmp0_);
#line 224 "FakeServer.vala"
	_tmp1_ = webkit_uri_scheme_request_get_path (request);
#line 224 "FakeServer.vala"
	_tmp2_ = webkit_uri_scheme_request_get_scheme (request);
#line 224 "FakeServer.vala"
	_tmp3_ = fake_server_cache_factory (_tmp1_, _tmp2_);
#line 224 "FakeServer.vala"
	cdata = _tmp3_;
#line 226 "FakeServer.vala"
	_tmp4_ = cdata;
#line 226 "FakeServer.vala"
	if (_tmp4_->size < ((gint64) 1)) {
#line 1344 "FakeServer.vala.c"
		const gchar* _tmp5_;
		const gchar* _tmp6_;
		GError* _tmp7_;
		GError* _tmp8_;
#line 227 "FakeServer.vala"
		_tmp5_ = g_get_home_dir ();
#line 227 "FakeServer.vala"
		_tmp6_ = webkit_uri_scheme_request_get_path (request);
#line 227 "FakeServer.vala"
		g_print ("Skip file missing = %s/gitlive%s\n", _tmp5_, _tmp6_);
#line 228 "FakeServer.vala"
		_tmp7_ = g_error_new_literal (FAKE_SERVER_ERROR, FAKE_SERVER_ERROR_FILE_DOES_NOT_EXIST, "My error msg");
#line 228 "FakeServer.vala"
		_tmp8_ = _tmp7_;
#line 228 "FakeServer.vala"
		webkit_uri_scheme_request_finish_error (request, _tmp8_);
#line 228 "FakeServer.vala"
		_g_error_free0 (_tmp8_);
#line 229 "FakeServer.vala"
		_g_object_unref0 (cdata);
#line 229 "FakeServer.vala"
		return;
#line 1367 "FakeServer.vala.c"
	}
#line 232 "FakeServer.vala"
	_tmp9_ = webkit_uri_scheme_request_get_path (request);
#line 232 "FakeServer.vala"
	_tmp10_ = cdata;
#line 232 "FakeServer.vala"
	_tmp11_ = _tmp10_->content_type;
#line 232 "FakeServer.vala"
	_tmp12_ = cdata;
#line 232 "FakeServer.vala"
	_tmp13_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp12_->size);
#line 232 "FakeServer.vala"
	_tmp14_ = _tmp13_;
#line 232 "FakeServer.vala"
	_tmp15_ = cdata;
#line 232 "FakeServer.vala"
	_tmp16_ = _tmp15_->data;
#line 232 "FakeServer.vala"
	_tmp16__length1 = _tmp15_->data_length1;
#line 232 "FakeServer.vala"
	g_print ("Send :%s, %s (%s/%d)", _tmp9_, _tmp11_, _tmp14_, _tmp16__length1);
#line 232 "FakeServer.vala"
	_g_free0 (_tmp14_);
#line 234 "FakeServer.vala"
	_tmp17_ = cdata;
#line 234 "FakeServer.vala"
	fake_server_cache_run (_tmp17_, request, NULL);
#line 219 "FakeServer.vala"
	_g_object_unref0 (cdata);
#line 1397 "FakeServer.vala.c"
}

static void
fake_server_class_init (FakeServerClass * klass,
                        gpointer klass_data)
{
#line 195 "FakeServer.vala"
	fake_server_parent_class = g_type_class_peek_parent (klass);
#line 195 "FakeServer.vala"
	g_type_class_adjust_private_offset (klass, &FakeServer_private_offset);
#line 195 "FakeServer.vala"
	G_OBJECT_CLASS (klass)->finalize = fake_server_finalize;
#line 1410 "FakeServer.vala.c"
}

static void
fake_server_instance_init (FakeServer * self,
                           gpointer klass)
{
#line 195 "FakeServer.vala"
	self->priv = fake_server_get_instance_private (self);
#line 1419 "FakeServer.vala.c"
}

static void
fake_server_finalize (GObject * obj)
{
	FakeServer * self;
#line 195 "FakeServer.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_FAKE_SERVER, FakeServer);
#line 197 "FakeServer.vala"
	_g_object_unref0 (self->priv->view);
#line 195 "FakeServer.vala"
	G_OBJECT_CLASS (fake_server_parent_class)->finalize (obj);
#line 1432 "FakeServer.vala.c"
}

static GType
fake_server_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (FakeServerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fake_server_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FakeServer), 0, (GInstanceInitFunc) fake_server_instance_init, NULL };
	GType fake_server_type_id;
	fake_server_type_id = g_type_register_static (G_TYPE_OBJECT, "FakeServer", &g_define_type_info, 0);
	FakeServer_private_offset = g_type_add_instance_private (fake_server_type_id, sizeof (FakeServerPrivate));
	return fake_server_type_id;
}

GType
fake_server_get_type (void)
{
	static volatile gsize fake_server_type_id__once = 0;
	if (g_once_init_enter (&fake_server_type_id__once)) {
		GType fake_server_type_id;
		fake_server_type_id = fake_server_get_type_once ();
		g_once_init_leave (&fake_server_type_id__once, fake_server_type_id);
	}
	return fake_server_type_id__once;
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
	if (mem && byte_size != 0) {
		new_mem = g_malloc (byte_size);
		memcpy (new_mem, mem, byte_size);
	} else {
		new_mem = NULL;
	}
	return new_mem;
}

