/* valaccodenewline.vala.c generated by valac, the Vala compiler
 * generated from valaccodenewline.vala, do not modify */

/* valaccodenewline.vala
 *
 * Copyright (C) 2006  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include <glib-object.h>
#include <glib.h>
#include <string.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define VALA_TYPE_CCODE_NODE (vala_ccode_node_get_type ())
#define VALA_CCODE_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_NODE, ValaCCodeNode))
#define VALA_CCODE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_NODE, ValaCCodeNodeClass))
#define VALA_IS_CCODE_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_NODE))
#define VALA_IS_CCODE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_NODE))
#define VALA_CCODE_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_NODE, ValaCCodeNodeClass))

typedef struct _ValaCCodeNode ValaCCodeNode;
typedef struct _ValaCCodeNodeClass ValaCCodeNodeClass;
typedef struct _ValaCCodeNodePrivate ValaCCodeNodePrivate;

#define VALA_TYPE_CCODE_WRITER (vala_ccode_writer_get_type ())
#define VALA_CCODE_WRITER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_WRITER, ValaCCodeWriter))
#define VALA_CCODE_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_WRITER, ValaCCodeWriterClass))
#define VALA_IS_CCODE_WRITER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_WRITER))
#define VALA_IS_CCODE_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_WRITER))
#define VALA_CCODE_WRITER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_WRITER, ValaCCodeWriterClass))

typedef struct _ValaCCodeWriter ValaCCodeWriter;
typedef struct _ValaCCodeWriterClass ValaCCodeWriterClass;

#define VALA_TYPE_CCODE_NEWLINE (vala_ccode_newline_get_type ())
#define VALA_CCODE_NEWLINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_NEWLINE, ValaCCodeNewline))
#define VALA_CCODE_NEWLINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_NEWLINE, ValaCCodeNewlineClass))
#define VALA_IS_CCODE_NEWLINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_NEWLINE))
#define VALA_IS_CCODE_NEWLINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_NEWLINE))
#define VALA_CCODE_NEWLINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_NEWLINE, ValaCCodeNewlineClass))

typedef struct _ValaCCodeNewline ValaCCodeNewline;
typedef struct _ValaCCodeNewlineClass ValaCCodeNewlineClass;
typedef struct _ValaCCodeNewlinePrivate ValaCCodeNewlinePrivate;

struct _ValaCCodeNode {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ValaCCodeNodePrivate * priv;
};

struct _ValaCCodeNodeClass {
	GTypeClass parent_class;
	void (*finalize) (ValaCCodeNode *self);
	void (*write) (ValaCCodeNode* self, ValaCCodeWriter* writer);
	void (*write_declaration) (ValaCCodeNode* self, ValaCCodeWriter* writer);
	void (*write_combined) (ValaCCodeNode* self, ValaCCodeWriter* writer);
};

struct _ValaCCodeNewline {
	ValaCCodeNode parent_instance;
	ValaCCodeNewlinePrivate * priv;
};

struct _ValaCCodeNewlineClass {
	ValaCCodeNodeClass parent_class;
};

static gpointer vala_ccode_newline_parent_class = NULL;

VALA_EXTERN gpointer vala_ccode_node_ref (gpointer instance);
VALA_EXTERN void vala_ccode_node_unref (gpointer instance);
VALA_EXTERN GParamSpec* vala_param_spec_ccode_node (const gchar* name,
                                        const gchar* nick,
                                        const gchar* blurb,
                                        GType object_type,
                                        GParamFlags flags);
VALA_EXTERN void vala_value_set_ccode_node (GValue* value,
                                gpointer v_object);
VALA_EXTERN void vala_value_take_ccode_node (GValue* value,
                                 gpointer v_object);
VALA_EXTERN gpointer vala_value_get_ccode_node (const GValue* value);
VALA_EXTERN GType vala_ccode_node_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ValaCCodeNode, vala_ccode_node_unref)
VALA_EXTERN gpointer vala_ccode_writer_ref (gpointer instance);
VALA_EXTERN void vala_ccode_writer_unref (gpointer instance);
VALA_EXTERN GParamSpec* vala_param_spec_ccode_writer (const gchar* name,
                                          const gchar* nick,
                                          const gchar* blurb,
                                          GType object_type,
                                          GParamFlags flags);
VALA_EXTERN void vala_value_set_ccode_writer (GValue* value,
                                  gpointer v_object);
VALA_EXTERN void vala_value_take_ccode_writer (GValue* value,
                                   gpointer v_object);
VALA_EXTERN gpointer vala_value_get_ccode_writer (const GValue* value);
VALA_EXTERN GType vala_ccode_writer_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ValaCCodeWriter, vala_ccode_writer_unref)
VALA_EXTERN GType vala_ccode_newline_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ValaCCodeNewline, vala_ccode_node_unref)
VALA_EXTERN void vala_ccode_node_write (ValaCCodeNode* self,
                            ValaCCodeWriter* writer);
static void vala_ccode_newline_real_write (ValaCCodeNode* base,
                                    ValaCCodeWriter* writer);
VALA_EXTERN void vala_ccode_writer_write_newline (ValaCCodeWriter* self);
VALA_EXTERN ValaCCodeNewline* vala_ccode_newline_new (void);
VALA_EXTERN ValaCCodeNewline* vala_ccode_newline_construct (GType object_type);
VALA_EXTERN ValaCCodeNode* vala_ccode_node_construct (GType object_type);
static GType vala_ccode_newline_get_type_once (void);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

static void
vala_ccode_newline_real_write (ValaCCodeNode* base,
                               ValaCCodeWriter* writer)
{
	ValaCCodeNewline * self;
#line 29 "valaccodenewline.vala"
	self = (ValaCCodeNewline*) base;
#line 30 "valaccodenewline.vala"
	vala_ccode_writer_write_newline (writer);
#line 149 "valaccodenewline.vala.c"
}

ValaCCodeNewline*
vala_ccode_newline_construct (GType object_type)
{
	ValaCCodeNewline* self = NULL;
#line 28 "valaccodenewline.vala"
	self = (ValaCCodeNewline*) vala_ccode_node_construct (object_type);
#line 28 "valaccodenewline.vala"
	return self;
#line 160 "valaccodenewline.vala.c"
}

ValaCCodeNewline*
vala_ccode_newline_new (void)
{
#line 28 "valaccodenewline.vala"
	return vala_ccode_newline_construct (VALA_TYPE_CCODE_NEWLINE);
#line 168 "valaccodenewline.vala.c"
}

static void
vala_ccode_newline_class_init (ValaCCodeNewlineClass * klass,
                               gpointer klass_data)
{
#line 28 "valaccodenewline.vala"
	vala_ccode_newline_parent_class = g_type_class_peek_parent (klass);
#line 28 "valaccodenewline.vala"
	((ValaCCodeNodeClass *) klass)->write = (void (*) (ValaCCodeNode*, ValaCCodeWriter*)) vala_ccode_newline_real_write;
#line 179 "valaccodenewline.vala.c"
}

static void
vala_ccode_newline_instance_init (ValaCCodeNewline * self,
                                  gpointer klass)
{
}

/**
 * Represents a line break in the C code.
 */
static GType
vala_ccode_newline_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ValaCCodeNewlineClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_ccode_newline_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaCCodeNewline), 0, (GInstanceInitFunc) vala_ccode_newline_instance_init, NULL };
	GType vala_ccode_newline_type_id;
	vala_ccode_newline_type_id = g_type_register_static (VALA_TYPE_CCODE_NODE, "ValaCCodeNewline", &g_define_type_info, 0);
	return vala_ccode_newline_type_id;
}

GType
vala_ccode_newline_get_type (void)
{
	static volatile gsize vala_ccode_newline_type_id__once = 0;
	if (g_once_init_enter (&vala_ccode_newline_type_id__once)) {
		GType vala_ccode_newline_type_id;
		vala_ccode_newline_type_id = vala_ccode_newline_get_type_once ();
		g_once_init_leave (&vala_ccode_newline_type_id__once, vala_ccode_newline_type_id);
	}
	return vala_ccode_newline_type_id__once;
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
	if (mem && byte_size != 0) {
		new_mem = g_malloc (byte_size);
		memcpy (new_mem, mem, byte_size);
	} else {
		new_mem = NULL;
	}
	return new_mem;
}

