/* ChatCall.c generated by valac 0.56.18, the Vala compiler
 * generated from ChatCall.vala, do not modify */

#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>
#include <gio/gio.h>
#include <libsoup/soup.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE (oll_mchat_ollama_ollama_base_get_type ())
#define OLL_MCHAT_OLLAMA_OLLAMA_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE, OLLMchatOllamaOllamaBase))
#define OLL_MCHAT_OLLAMA_OLLAMA_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE, OLLMchatOllamaOllamaBaseClass))
#define OLL_MCHAT_OLLAMA_IS_OLLAMA_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE))
#define OLL_MCHAT_OLLAMA_IS_OLLAMA_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE))
#define OLL_MCHAT_OLLAMA_OLLAMA_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE, OLLMchatOllamaOllamaBaseClass))

typedef struct _OLLMchatOllamaOllamaBase OLLMchatOllamaOllamaBase;
typedef struct _OLLMchatOllamaOllamaBaseClass OLLMchatOllamaOllamaBaseClass;
typedef struct _OLLMchatOllamaOllamaBasePrivate OLLMchatOllamaOllamaBasePrivate;

#define OLL_MCHAT_OLLAMA_TYPE_CLIENT (oll_mchat_ollama_client_get_type ())
#define OLL_MCHAT_OLLAMA_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_CLIENT, OLLMchatOllamaClient))
#define OLL_MCHAT_OLLAMA_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_CLIENT, OLLMchatOllamaClientClass))
#define OLL_MCHAT_OLLAMA_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_CLIENT))
#define OLL_MCHAT_OLLAMA_IS_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_CLIENT))
#define OLL_MCHAT_OLLAMA_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_CLIENT, OLLMchatOllamaClientClass))

typedef struct _OLLMchatOllamaClient OLLMchatOllamaClient;
typedef struct _OLLMchatOllamaClientClass OLLMchatOllamaClientClass;

#define OLL_MCHAT_OLLAMA_TYPE_BASE_CALL (oll_mchat_ollama_base_call_get_type ())
#define OLL_MCHAT_OLLAMA_BASE_CALL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_CALL, OLLMchatOllamaBaseCall))
#define OLL_MCHAT_OLLAMA_BASE_CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_BASE_CALL, OLLMchatOllamaBaseCallClass))
#define OLL_MCHAT_OLLAMA_IS_BASE_CALL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_CALL))
#define OLL_MCHAT_OLLAMA_IS_BASE_CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_BASE_CALL))
#define OLL_MCHAT_OLLAMA_BASE_CALL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_CALL, OLLMchatOllamaBaseCallClass))

typedef struct _OLLMchatOllamaBaseCall OLLMchatOllamaBaseCall;
typedef struct _OLLMchatOllamaBaseCallClass OLLMchatOllamaBaseCallClass;
typedef struct _OLLMchatOllamaBaseCallPrivate OLLMchatOllamaBaseCallPrivate;

#define OLL_MCHAT_OLLAMA_TYPE_MESSAGE_INTERFACE (oll_mchat_ollama_message_interface_get_type ())
#define OLL_MCHAT_OLLAMA_MESSAGE_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_MESSAGE_INTERFACE, OLLMchatOllamaMessageInterface))
#define OLL_MCHAT_OLLAMA_IS_MESSAGE_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_MESSAGE_INTERFACE))
#define OLL_MCHAT_OLLAMA_MESSAGE_INTERFACE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), OLL_MCHAT_OLLAMA_TYPE_MESSAGE_INTERFACE, OLLMchatOllamaMessageInterfaceIface))

typedef struct _OLLMchatOllamaMessageInterface OLLMchatOllamaMessageInterface;
typedef struct _OLLMchatOllamaMessageInterfaceIface OLLMchatOllamaMessageInterfaceIface;

#define OLL_MCHAT_OLLAMA_TYPE_CHAT_CALL (oll_mchat_ollama_chat_call_get_type ())
#define OLL_MCHAT_OLLAMA_CHAT_CALL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_CHAT_CALL, OLLMchatOllamaChatCall))
#define OLL_MCHAT_OLLAMA_CHAT_CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_CHAT_CALL, OLLMchatOllamaChatCallClass))
#define OLL_MCHAT_OLLAMA_IS_CHAT_CALL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_CHAT_CALL))
#define OLL_MCHAT_OLLAMA_IS_CHAT_CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_CHAT_CALL))
#define OLL_MCHAT_OLLAMA_CHAT_CALL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_CHAT_CALL, OLLMchatOllamaChatCallClass))

typedef struct _OLLMchatOllamaChatCall OLLMchatOllamaChatCall;
typedef struct _OLLMchatOllamaChatCallClass OLLMchatOllamaChatCallClass;
typedef struct _OLLMchatOllamaChatCallPrivate OLLMchatOllamaChatCallPrivate;

#define OLL_MCHAT_OLLAMA_TYPE_TOOL (oll_mchat_ollama_tool_get_type ())
#define OLL_MCHAT_OLLAMA_TOOL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_TOOL, OLLMchatOllamaTool))
#define OLL_MCHAT_OLLAMA_TOOL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_TOOL, OLLMchatOllamaToolClass))
#define OLL_MCHAT_OLLAMA_IS_TOOL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_TOOL))
#define OLL_MCHAT_OLLAMA_IS_TOOL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_TOOL))
#define OLL_MCHAT_OLLAMA_TOOL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_TOOL, OLLMchatOllamaToolClass))

typedef struct _OLLMchatOllamaTool OLLMchatOllamaTool;
typedef struct _OLLMchatOllamaToolClass OLLMchatOllamaToolClass;

#define OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE (oll_mchat_ollama_base_response_get_type ())
#define OLL_MCHAT_OLLAMA_BASE_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE, OLLMchatOllamaBaseResponse))
#define OLL_MCHAT_OLLAMA_BASE_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE, OLLMchatOllamaBaseResponseClass))
#define OLL_MCHAT_OLLAMA_IS_BASE_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE))
#define OLL_MCHAT_OLLAMA_IS_BASE_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE))
#define OLL_MCHAT_OLLAMA_BASE_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE, OLLMchatOllamaBaseResponseClass))

typedef struct _OLLMchatOllamaBaseResponse OLLMchatOllamaBaseResponse;
typedef struct _OLLMchatOllamaBaseResponseClass OLLMchatOllamaBaseResponseClass;

#define OLL_MCHAT_OLLAMA_TYPE_CHAT_RESPONSE (oll_mchat_ollama_chat_response_get_type ())
#define OLL_MCHAT_OLLAMA_CHAT_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_CHAT_RESPONSE, OLLMchatOllamaChatResponse))
#define OLL_MCHAT_OLLAMA_CHAT_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_CHAT_RESPONSE, OLLMchatOllamaChatResponseClass))
#define OLL_MCHAT_OLLAMA_IS_CHAT_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_CHAT_RESPONSE))
#define OLL_MCHAT_OLLAMA_IS_CHAT_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_CHAT_RESPONSE))
#define OLL_MCHAT_OLLAMA_CHAT_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_CHAT_RESPONSE, OLLMchatOllamaChatResponseClass))

typedef struct _OLLMchatOllamaChatResponse OLLMchatOllamaChatResponse;
typedef struct _OLLMchatOllamaChatResponseClass OLLMchatOllamaChatResponseClass;
enum  {
	OLL_MCHAT_OLLAMA_CHAT_CALL_0_PROPERTY,
	OLL_MCHAT_OLLAMA_CHAT_CALL_MODEL_PROPERTY,
	OLL_MCHAT_OLLAMA_CHAT_CALL_TOOLS_PROPERTY,
	OLL_MCHAT_OLLAMA_CHAT_CALL_STREAM_PROPERTY,
	OLL_MCHAT_OLLAMA_CHAT_CALL_FORMAT_PROPERTY,
	OLL_MCHAT_OLLAMA_CHAT_CALL_OPTIONS_PROPERTY,
	OLL_MCHAT_OLLAMA_CHAT_CALL_THINK_PROPERTY,
	OLL_MCHAT_OLLAMA_CHAT_CALL_KEEP_ALIVE_PROPERTY,
	OLL_MCHAT_OLLAMA_CHAT_CALL_MESSAGES_PROPERTY,
	OLL_MCHAT_OLLAMA_CHAT_CALL_MESSAGE_PROPERTY,
	OLL_MCHAT_OLLAMA_CHAT_CALL_NUM_PROPERTIES
};
static GParamSpec* oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))

#define OLL_MCHAT_OLLAMA_TYPE_OLLAMA_ERROR (oll_mchat_ollama_ollama_error_get_type ())
typedef void (*OLLMchatOllamaStreamCallback) (const gchar* new_text, OLLMchatOllamaChatResponse* response, gpointer user_data);
typedef struct _OllMchatOllamaChatCallExecChatData OllMchatOllamaChatCallExecChatData;
#define _g_bytes_unref0(var) ((var == NULL) ? NULL : (var = (g_bytes_unref (var), NULL)))
typedef struct _OllMchatOllamaChatCallExecuteNonStreamingData OllMchatOllamaChatCallExecuteNonStreamingData;
typedef void (*OLLMchatOllamaBaseCallStreamingChunkCallback) (JsonObject* chunk, gpointer user_data);
typedef struct _OllMchatOllamaChatCallExecuteStreamingData OllMchatOllamaChatCallExecuteStreamingData;

struct _OLLMchatOllamaOllamaBase {
	GObject parent_instance;
	OLLMchatOllamaOllamaBasePrivate * priv;
	OLLMchatOllamaClient* client;
};

struct _OLLMchatOllamaOllamaBaseClass {
	GObjectClass parent_class;
	JsonNode* (*serialize_property) (OLLMchatOllamaOllamaBase* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
};

struct _OLLMchatOllamaBaseCall {
	OLLMchatOllamaOllamaBase parent_instance;
	OLLMchatOllamaBaseCallPrivate * priv;
	gchar* url_endpoint;
	gchar* http_method;
};

struct _OLLMchatOllamaBaseCallClass {
	OLLMchatOllamaOllamaBaseClass parent_class;
};

struct _OLLMchatOllamaMessageInterfaceIface {
	GTypeInterface parent_iface;
	const gchar* (*get_chat_role) (OLLMchatOllamaMessageInterface* self);
	void (*set_chat_role) (OLLMchatOllamaMessageInterface* self, const gchar* value);
	const gchar* (*get_chat_content) (OLLMchatOllamaMessageInterface* self);
	void (*set_chat_content) (OLLMchatOllamaMessageInterface* self, const gchar* value);
	JsonObject* (*get_message) (OLLMchatOllamaMessageInterface* self);
};

struct _OLLMchatOllamaChatCall {
	OLLMchatOllamaBaseCall parent_instance;
	OLLMchatOllamaChatCallPrivate * priv;
};

struct _OLLMchatOllamaChatCallClass {
	OLLMchatOllamaBaseCallClass parent_class;
};

struct _OLLMchatOllamaChatCallPrivate {
	gchar* _model;
	GeeArrayList* _tools;
	gboolean _stream;
	gchar* _format;
	JsonObject* _options;
	gboolean _think;
	gchar* _keep_alive;
	GeeArrayList* _messages;
	OLLMchatOllamaChatResponse* streaming_response;
};

typedef enum  {
	OLL_MCHAT_OLLAMA_OLLAMA_ERROR_INVALID_ARGUMENT,
	OLL_MCHAT_OLLAMA_OLLAMA_ERROR_FAILED
} OLLMchatOllamaOllamaError;
#define OLL_MCHAT_OLLAMA_OLLAMA_ERROR oll_mchat_ollama_ollama_error_quark ()

struct _OllMchatOllamaChatCallExecChatData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	OLLMchatOllamaChatCall* self;
	OLLMchatOllamaChatResponse* result;
	const gchar* _tmp0_;
	GError* _tmp1_;
	OLLMchatOllamaClient* _tmp2_;
	OLLMchatOllamaStreamCallback _tmp3_;
	gpointer _tmp3__target;
	OLLMchatOllamaStreamCallback _tmp4_;
	gpointer _tmp4__target;
	gboolean _tmp5_;
	OLLMchatOllamaClient* _tmp6_;
	GeeArrayList* _tmp7_;
	GeeArrayList* _tmp8_;
	OLLMchatOllamaClient* _tmp9_;
	GeeArrayList* _tmp10_;
	GeeArrayList* _tmp11_;
	gint _tmp12_;
	gint _tmp13_;
	GeeArrayList* _tmp14_;
	GeeArrayList* _tmp15_;
	GeeArrayList* _tmp16_;
	GeeArrayList* _tool_list;
	OLLMchatOllamaClient* _tmp17_;
	GeeArrayList* _tmp18_;
	GeeArrayList* _tmp19_;
	gint _tool_size;
	GeeArrayList* _tmp20_;
	gint _tmp21_;
	gint _tmp22_;
	gint _tool_index;
	gint _tmp23_;
	gint _tmp24_;
	OLLMchatOllamaTool* tool;
	GeeArrayList* _tmp25_;
	gpointer _tmp26_;
	GeeArrayList* _tmp27_;
	OLLMchatOllamaTool* _tmp28_;
	gboolean _tmp29_;
	OLLMchatOllamaClient* _tmp30_;
	OLLMchatOllamaChatResponse* _tmp31_;
	OLLMchatOllamaChatResponse* _tmp32_;
	OLLMchatOllamaChatResponse* _tmp33_;
	OLLMchatOllamaChatResponse* _tmp34_;
	OLLMchatOllamaChatResponse* _tmp35_;
	OLLMchatOllamaChatResponse* _tmp36_;
	OLLMchatOllamaChatResponse* _tmp37_;
	GError* _inner_error0_;
};

struct _OllMchatOllamaChatCallExecuteNonStreamingData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	OLLMchatOllamaChatCall* self;
	OLLMchatOllamaChatResponse* result;
	GBytes* bytes;
	GBytes* _tmp0_;
	JsonNode* root;
	GBytes* _tmp1_;
	JsonNode* _tmp2_;
	JsonNode* _tmp3_;
	GError* _tmp4_;
	JsonGenerator* generator;
	JsonGenerator* _tmp5_;
	JsonGenerator* _tmp6_;
	JsonNode* _tmp7_;
	gchar* json_str;
	JsonGenerator* _tmp8_;
	gchar* _tmp9_;
	GObject* _tmp10_;
	const gchar* _tmp11_;
	GObject* _tmp12_;
	OLLMchatOllamaChatResponse* response_obj;
	OLLMchatOllamaChatResponse* _tmp13_;
	OLLMchatOllamaChatResponse* _tmp14_;
	GError* _tmp15_;
	OLLMchatOllamaChatResponse* _tmp16_;
	OLLMchatOllamaClient* _tmp17_;
	OLLMchatOllamaClient* _tmp18_;
	GError* _inner_error0_;
};

struct _OllMchatOllamaChatCallExecuteStreamingData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	OLLMchatOllamaChatCall* self;
	OLLMchatOllamaChatResponse* result;
	OLLMchatOllamaChatResponse* _tmp0_;
	GError* _tmp1_;
	gchar* url;
	gchar* _tmp2_;
	SoupSession* session;
	SoupSession* _tmp3_;
	gchar* request_body;
	gchar* _tmp4_;
	SoupMessage* message;
	SoupMessage* _tmp5_;
	gboolean is_json_format;
	const gchar* _tmp6_;
	OLLMchatOllamaChatResponse* _tmp7_;
	OLLMchatOllamaChatResponse* _tmp8_;
	GError* _inner_error0_;
};

static gint OLLMchatOllamaChatCall_private_offset;
static gpointer oll_mchat_ollama_chat_call_parent_class = NULL;
static OLLMchatOllamaMessageInterfaceIface * oll_mchat_ollama_chat_call_oll_mchat_ollama_message_interface_parent_iface = NULL;

VALA_EXTERN GType oll_mchat_ollama_ollama_base_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaOllamaBase, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_client_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaClient, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_base_call_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaBaseCall, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_message_interface_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaMessageInterface, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_chat_call_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaChatCall, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_tool_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaTool, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_base_response_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaBaseResponse, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_chat_response_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaChatResponse, g_object_unref)
VALA_EXTERN JsonNode* oll_mchat_ollama_ollama_base_serialize_property (OLLMchatOllamaOllamaBase* self,
                                                           const gchar* property_name,
                                                           GValue* value,
                                                           GParamSpec* pspec);
VALA_EXTERN OLLMchatOllamaChatCall* oll_mchat_ollama_chat_call_new (OLLMchatOllamaClient* client);
VALA_EXTERN OLLMchatOllamaChatCall* oll_mchat_ollama_chat_call_construct (GType object_type,
                                                              OLLMchatOllamaClient* client);
VALA_EXTERN OLLMchatOllamaBaseCall* oll_mchat_ollama_base_call_construct (GType object_type,
                                                              OLLMchatOllamaClient* client);
VALA_EXTERN void oll_mchat_ollama_chat_call_add_message (OLLMchatOllamaChatCall* self,
                                             OLLMchatOllamaChatResponse* message);
VALA_EXTERN GeeArrayList* oll_mchat_ollama_chat_call_get_messages (OLLMchatOllamaChatCall* self);
static JsonNode* oll_mchat_ollama_chat_call_real_serialize_property (OLLMchatOllamaOllamaBase* base,
                                                              const gchar* property_name,
                                                              GValue* value,
                                                              GParamSpec* pspec);
static void _vala_JsonNode_free (JsonNode* self);
VALA_EXTERN JsonObject* oll_mchat_ollama_message_interface_get_message (OLLMchatOllamaMessageInterface* self);
VALA_EXTERN gboolean oll_mchat_ollama_chat_call_deserialize_property (OLLMchatOllamaChatCall* self,
                                                          const gchar* property_name,
                                                          GValue* value,
                                                          GParamSpec* pspec,
                                                          JsonNode* property_node);
VALA_EXTERN void oll_mchat_ollama_chat_call_set_messages (OLLMchatOllamaChatCall* self,
                                              GeeArrayList* value);
static void oll_mchat_ollama_chat_call_exec_chat_data_free (gpointer _data);
VALA_EXTERN void oll_mchat_ollama_chat_call_exec_chat (OLLMchatOllamaChatCall* self,
                                           GAsyncReadyCallback _callback_,
                                           gpointer _user_data_);
VALA_EXTERN OLLMchatOllamaChatResponse* oll_mchat_ollama_chat_call_exec_chat_finish (OLLMchatOllamaChatCall* self,
                                                                         GAsyncResult* _res_,
                                                                         GError** error);
static gboolean oll_mchat_ollama_chat_call_exec_chat_co (OllMchatOllamaChatCallExecChatData* _data_);
VALA_EXTERN const gchar* oll_mchat_ollama_chat_call_get_model (OLLMchatOllamaChatCall* self);
VALA_EXTERN GQuark oll_mchat_ollama_ollama_error_quark (void);
VALA_EXTERN GType oll_mchat_ollama_ollama_error_get_type (void) G_GNUC_CONST ;
VALA_EXTERN OLLMchatOllamaStreamCallback oll_mchat_ollama_client_get_stream_callback (OLLMchatOllamaClient* self,
                                                                          gpointer* result_target);
VALA_EXTERN void oll_mchat_ollama_chat_call_set_stream (OLLMchatOllamaChatCall* self,
                                            gboolean value);
VALA_EXTERN GeeArrayList* oll_mchat_ollama_client_get_tools (OLLMchatOllamaClient* self);
VALA_EXTERN GeeArrayList* oll_mchat_ollama_chat_call_get_tools (OLLMchatOllamaChatCall* self);
VALA_EXTERN void oll_mchat_ollama_chat_call_set_tools (OLLMchatOllamaChatCall* self,
                                           GeeArrayList* value);
VALA_EXTERN gboolean oll_mchat_ollama_chat_call_get_stream (OLLMchatOllamaChatCall* self);
VALA_EXTERN OLLMchatOllamaChatResponse* oll_mchat_ollama_chat_response_new (OLLMchatOllamaClient* client);
VALA_EXTERN OLLMchatOllamaChatResponse* oll_mchat_ollama_chat_response_construct (GType object_type,
                                                                      OLLMchatOllamaClient* client);
static void oll_mchat_ollama_chat_call_execute_streaming (OLLMchatOllamaChatCall* self,
                                                   GAsyncReadyCallback _callback_,
                                                   gpointer _user_data_);
static OLLMchatOllamaChatResponse* oll_mchat_ollama_chat_call_execute_streaming_finish (OLLMchatOllamaChatCall* self,
                                                                                 GAsyncResult* _res_,
                                                                                 GError** error);
static void oll_mchat_ollama_chat_call_exec_chat_ready (GObject* source_object,
                                                 GAsyncResult* _res_,
                                                 gpointer _user_data_);
static void oll_mchat_ollama_chat_call_execute_non_streaming (OLLMchatOllamaChatCall* self,
                                                       GAsyncReadyCallback _callback_,
                                                       gpointer _user_data_);
static OLLMchatOllamaChatResponse* oll_mchat_ollama_chat_call_execute_non_streaming_finish (OLLMchatOllamaChatCall* self,
                                                                                     GAsyncResult* _res_,
                                                                                     GError** error);
static void oll_mchat_ollama_chat_call_execute_non_streaming_data_free (gpointer _data);
static gboolean oll_mchat_ollama_chat_call_execute_non_streaming_co (OllMchatOllamaChatCallExecuteNonStreamingData* _data_);
VALA_EXTERN void oll_mchat_ollama_base_call_send_request (OLLMchatOllamaBaseCall* self,
                                              gboolean needs_body,
                                              GAsyncReadyCallback _callback_,
                                              gpointer _user_data_);
VALA_EXTERN GBytes* oll_mchat_ollama_base_call_send_request_finish (OLLMchatOllamaBaseCall* self,
                                                        GAsyncResult* _res_,
                                                        GError** error);
static void oll_mchat_ollama_chat_call_execute_non_streaming_ready (GObject* source_object,
                                                             GAsyncResult* _res_,
                                                             gpointer _user_data_);
VALA_EXTERN JsonNode* oll_mchat_ollama_base_call_parse_response (OLLMchatOllamaBaseCall* self,
                                                     GBytes* bytes,
                                                     GError** error);
static void oll_mchat_ollama_chat_call_execute_streaming_data_free (gpointer _data);
static gboolean oll_mchat_ollama_chat_call_execute_streaming_co (OllMchatOllamaChatCallExecuteStreamingData* _data_);
VALA_EXTERN gchar* oll_mchat_ollama_base_call_build_url (OLLMchatOllamaBaseCall* self);
VALA_EXTERN gchar* oll_mchat_ollama_base_call_get_request_body (OLLMchatOllamaBaseCall* self);
static SoupMessage* oll_mchat_ollama_chat_call_create_streaming_message (OLLMchatOllamaChatCall* self,
                                                                  const gchar* url,
                                                                  const gchar* request_body);
VALA_EXTERN const gchar* oll_mchat_ollama_chat_call_get_format (OLLMchatOllamaChatCall* self);
VALA_EXTERN void oll_mchat_ollama_base_call_handle_streaming_response (OLLMchatOllamaBaseCall* self,
                                                           SoupSession* session,
                                                           SoupMessage* message,
                                                           gboolean is_json_format,
                                                           OLLMchatOllamaBaseCallStreamingChunkCallback on_chunk,
                                                           gpointer on_chunk_target,
                                                           GAsyncReadyCallback _callback_,
                                                           gpointer _user_data_);
VALA_EXTERN void oll_mchat_ollama_base_call_handle_streaming_response_finish (OLLMchatOllamaBaseCall* self,
                                                                  GAsyncResult* _res_,
                                                                  GError** error);
static void __lambda4_ (OLLMchatOllamaChatCall* self,
                 JsonObject* chunk);
static void oll_mchat_ollama_chat_call_process_streaming_chunk (OLLMchatOllamaChatCall* self,
                                                         JsonObject* chunk);
static void ___lambda4__oll_mchat_ollama_base_call_streaming_chunk_callback (JsonObject* chunk,
                                                                      gpointer self);
static void oll_mchat_ollama_chat_call_execute_streaming_ready (GObject* source_object,
                                                         GAsyncResult* _res_,
                                                         gpointer _user_data_);
VALA_EXTERN const gchar* oll_mchat_ollama_client_get_api_key (OLLMchatOllamaClient* self);
VALA_EXTERN gchar* oll_mchat_ollama_chat_response_addChunk (OLLMchatOllamaChatResponse* self,
                                                JsonObject* chunk);
VALA_EXTERN void oll_mchat_ollama_chat_call_set_model (OLLMchatOllamaChatCall* self,
                                           const gchar* value);
VALA_EXTERN void oll_mchat_ollama_chat_call_set_format (OLLMchatOllamaChatCall* self,
                                            const gchar* value);
VALA_EXTERN JsonObject* oll_mchat_ollama_chat_call_get_options (OLLMchatOllamaChatCall* self);
VALA_EXTERN void oll_mchat_ollama_chat_call_set_options (OLLMchatOllamaChatCall* self,
                                             JsonObject* value);
VALA_EXTERN gboolean oll_mchat_ollama_chat_call_get_think (OLLMchatOllamaChatCall* self);
VALA_EXTERN void oll_mchat_ollama_chat_call_set_think (OLLMchatOllamaChatCall* self,
                                           gboolean value);
VALA_EXTERN const gchar* oll_mchat_ollama_chat_call_get_keep_alive (OLLMchatOllamaChatCall* self);
VALA_EXTERN void oll_mchat_ollama_chat_call_set_keep_alive (OLLMchatOllamaChatCall* self,
                                                const gchar* value);
VALA_EXTERN const gchar* oll_mchat_ollama_message_interface_get_chat_role (OLLMchatOllamaMessageInterface* self);
VALA_EXTERN const gchar* oll_mchat_ollama_message_interface_get_chat_content (OLLMchatOllamaMessageInterface* self);
VALA_EXTERN const gchar* oll_mchat_ollama_ollama_base_get_chat_role (OLLMchatOllamaOllamaBase* self);
VALA_EXTERN void oll_mchat_ollama_ollama_base_set_chat_role (OLLMchatOllamaOllamaBase* self,
                                                 const gchar* value);
VALA_EXTERN const gchar* oll_mchat_ollama_ollama_base_get_chat_content (OLLMchatOllamaOllamaBase* self);
VALA_EXTERN void oll_mchat_ollama_ollama_base_set_chat_content (OLLMchatOllamaOllamaBase* self,
                                                    const gchar* value);
static void oll_mchat_ollama_chat_call_finalize (GObject * obj);
static GType oll_mchat_ollama_chat_call_get_type_once (void);
static void _vala_oll_mchat_ollama_chat_call_get_property (GObject * object,
                                                    guint property_id,
                                                    GValue * value,
                                                    GParamSpec * pspec);
static void _vala_oll_mchat_ollama_chat_call_set_property (GObject * object,
                                                    guint property_id,
                                                    const GValue * value,
                                                    GParamSpec * pspec);

static inline gpointer
oll_mchat_ollama_chat_call_get_instance_private (OLLMchatOllamaChatCall* self)
{
	return G_STRUCT_MEMBER_P (self, OLLMchatOllamaChatCall_private_offset);
}

OLLMchatOllamaChatCall*
oll_mchat_ollama_chat_call_construct (GType object_type,
                                      OLLMchatOllamaClient* client)
{
	OLLMchatOllamaChatCall * self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (client != NULL, NULL);
	self = (OLLMchatOllamaChatCall*) oll_mchat_ollama_base_call_construct (object_type, client);
	_tmp0_ = g_strdup ("chat");
	_g_free0 (((OLLMchatOllamaBaseCall*) self)->url_endpoint);
	((OLLMchatOllamaBaseCall*) self)->url_endpoint = _tmp0_;
	_tmp1_ = g_strdup ("POST");
	_g_free0 (((OLLMchatOllamaBaseCall*) self)->http_method);
	((OLLMchatOllamaBaseCall*) self)->http_method = _tmp1_;
	return self;
}

OLLMchatOllamaChatCall*
oll_mchat_ollama_chat_call_new (OLLMchatOllamaClient* client)
{
	return oll_mchat_ollama_chat_call_construct (OLL_MCHAT_OLLAMA_TYPE_CHAT_CALL, client);
}

void
oll_mchat_ollama_chat_call_add_message (OLLMchatOllamaChatCall* self,
                                        OLLMchatOllamaChatResponse* message)
{
	GeeArrayList* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (message != NULL);
	_tmp0_ = self->priv->_messages;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, (OLLMchatOllamaMessageInterface*) message);
}

static void
_vala_JsonNode_free (JsonNode* self)
{
	g_boxed_free (json_node_get_type (), self);
}

static gpointer
_json_array_ref0 (gpointer self)
{
	return self ? json_array_ref (self) : NULL;
}

static JsonNode*
oll_mchat_ollama_chat_call_real_serialize_property (OLLMchatOllamaOllamaBase* base,
                                                    const gchar* property_name,
                                                    GValue* value,
                                                    GParamSpec* pspec)
{
	OLLMchatOllamaChatCall * self;
	GValue _tmp20_;
	JsonNode* _tmp21_;
	JsonNode* result;
	self = (OLLMchatOllamaChatCall*) base;
	g_return_val_if_fail (property_name != NULL, NULL);
	g_return_val_if_fail (value != NULL, NULL);
	g_return_val_if_fail (pspec != NULL, NULL);
	if (g_strcmp0 (property_name, "message") == 0) {
		JsonNode* node = NULL;
		JsonNode* _tmp0_;
		_tmp0_ = json_node_new (JSON_NODE_NULL);
		node = _tmp0_;
		result = node;
		return result;
	}
	if (g_strcmp0 (property_name, "messages") == 0) {
		JsonNode* node = NULL;
		JsonNode* _tmp1_;
		JsonNode* _tmp2_;
		JsonArray* _tmp3_;
		JsonArray* _tmp4_;
		JsonArray* array = NULL;
		JsonNode* _tmp5_;
		JsonArray* _tmp6_;
		JsonArray* _tmp7_;
		_tmp1_ = json_node_new (JSON_NODE_ARRAY);
		node = _tmp1_;
		_tmp2_ = node;
		_tmp3_ = json_array_new ();
		_tmp4_ = _tmp3_;
		json_node_init_array (_tmp2_, _tmp4_);
		_json_array_unref0 (_tmp4_);
		_tmp5_ = node;
		_tmp6_ = json_node_get_array (_tmp5_);
		_tmp7_ = _json_array_ref0 (_tmp6_);
		array = _tmp7_;
		{
			GeeArrayList* _m_list = NULL;
			GeeArrayList* _tmp8_;
			gint _m_size = 0;
			GeeArrayList* _tmp9_;
			gint _tmp10_;
			gint _tmp11_;
			gint _m_index = 0;
			_tmp8_ = self->priv->_messages;
			_m_list = _tmp8_;
			_tmp9_ = _m_list;
			_tmp10_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp9_);
			_tmp11_ = _tmp10_;
			_m_size = _tmp11_;
			_m_index = -1;
			while (TRUE) {
				gint _tmp12_;
				gint _tmp13_;
				OLLMchatOllamaMessageInterface* m = NULL;
				GeeArrayList* _tmp14_;
				gpointer _tmp15_;
				JsonArray* _tmp16_;
				OLLMchatOllamaMessageInterface* _tmp17_;
				JsonObject* _tmp18_;
				JsonObject* _tmp19_;
				_m_index = _m_index + 1;
				_tmp12_ = _m_index;
				_tmp13_ = _m_size;
				if (!(_tmp12_ < _tmp13_)) {
					break;
				}
				_tmp14_ = _m_list;
				_tmp15_ = gee_abstract_list_get ((GeeAbstractList*) _tmp14_, _m_index);
				m = (OLLMchatOllamaMessageInterface*) _tmp15_;
				_tmp16_ = array;
				_tmp17_ = m;
				_tmp18_ = oll_mchat_ollama_message_interface_get_message (_tmp17_);
				_tmp19_ = _tmp18_;
				json_array_add_object_element (_tmp16_, _tmp19_);
				_g_object_unref0 (m);
			}
		}
		result = node;
		_json_array_unref0 (array);
		return result;
	}
	_tmp20_ = *value;
	_tmp21_ = OLL_MCHAT_OLLAMA_OLLAMA_BASE_CLASS (oll_mchat_ollama_chat_call_parent_class)->serialize_property ((OLLMchatOllamaOllamaBase*) G_TYPE_CHECK_INSTANCE_CAST (self, OLL_MCHAT_OLLAMA_TYPE_BASE_CALL, OLLMchatOllamaBaseCall), property_name, &_tmp20_, pspec);
	result = _tmp21_;
	return result;
}

gboolean
oll_mchat_ollama_chat_call_deserialize_property (OLLMchatOllamaChatCall* self,
                                                 const gchar* property_name,
                                                 GValue* value,
                                                 GParamSpec* pspec,
                                                 JsonNode* property_node)
{
	GValue _vala_value = {0};
	GValue _tmp4_ = {0};
	gboolean _tmp5_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (property_name != NULL, FALSE);
	g_return_val_if_fail (pspec != NULL, FALSE);
	g_return_val_if_fail (property_node != NULL, FALSE);
	if (g_strcmp0 (property_name, "messages") == 0) {
		GeeArrayList* _tmp0_;
		GeeArrayList* _tmp1_;
		GValue _tmp2_ = {0};
		GeeArrayList* _tmp3_;
		_tmp0_ = gee_array_list_new (OLL_MCHAT_OLLAMA_TYPE_MESSAGE_INTERFACE, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
		_tmp1_ = _tmp0_;
		oll_mchat_ollama_chat_call_set_messages (self, _tmp1_);
		_g_object_unref0 (_tmp1_);
		g_value_init (&_tmp2_, GEE_TYPE_ARRAY_LIST);
		G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
		_vala_value = _tmp2_;
		_tmp3_ = self->priv->_messages;
		g_value_set_object (&_vala_value, (GObject*) _tmp3_);
		result = TRUE;
		if (value) {
			*value = _vala_value;
		} else {
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
		}
		return result;
	}
	_tmp5_ = json_serializable_default_deserialize_property ((JsonSerializable*) self, property_name, &_tmp4_, pspec, property_node);
	G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
	_vala_value = _tmp4_;
	result = _tmp5_;
	if (value) {
		*value = _vala_value;
	} else {
		G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
	}
	return result;
}

static void
oll_mchat_ollama_chat_call_exec_chat_data_free (gpointer _data)
{
	OllMchatOllamaChatCallExecChatData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->result);
	_g_object_unref0 (_data_->self);
	g_slice_free (OllMchatOllamaChatCallExecChatData, _data_);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
oll_mchat_ollama_chat_call_exec_chat (OLLMchatOllamaChatCall* self,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_)
{
	OllMchatOllamaChatCallExecChatData* _data_;
	OLLMchatOllamaChatCall* _tmp0_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (OllMchatOllamaChatCallExecChatData);
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, oll_mchat_ollama_chat_call_exec_chat_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	oll_mchat_ollama_chat_call_exec_chat_co (_data_);
}

OLLMchatOllamaChatResponse*
oll_mchat_ollama_chat_call_exec_chat_finish (OLLMchatOllamaChatCall* self,
                                             GAsyncResult* _res_,
                                             GError** error)
{
	OLLMchatOllamaChatResponse* result;
	OllMchatOllamaChatCallExecChatData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), error);
	if (NULL == _data_) {
		return NULL;
	}
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
oll_mchat_ollama_chat_call_exec_chat_ready (GObject* source_object,
                                            GAsyncResult* _res_,
                                            gpointer _user_data_)
{
	OllMchatOllamaChatCallExecChatData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	oll_mchat_ollama_chat_call_exec_chat_co (_data_);
}

static gboolean
oll_mchat_ollama_chat_call_exec_chat_co (OllMchatOllamaChatCallExecChatData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		case 2:
		goto _state_2;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->_model;
	if (g_strcmp0 (_data_->_tmp0_, "") == 0) {
		_data_->_tmp1_ = g_error_new_literal (OLL_MCHAT_OLLAMA_OLLAMA_ERROR, OLL_MCHAT_OLLAMA_OLLAMA_ERROR_INVALID_ARGUMENT, "Model is required");
		_data_->_inner_error0_ = _data_->_tmp1_;
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp2_ = ((OLLMchatOllamaOllamaBase*) _data_->self)->client;
	_data_->_tmp3_ = NULL;
	_data_->_tmp3__target = NULL;
	_data_->_tmp3_ = oll_mchat_ollama_client_get_stream_callback (_data_->_tmp2_, &_data_->_tmp3__target);
	_data_->_tmp4_ = _data_->_tmp3_;
	_data_->_tmp4__target = _data_->_tmp3__target;
	if (_data_->_tmp4_ != NULL) {
		oll_mchat_ollama_chat_call_set_stream (_data_->self, TRUE);
	}
	_data_->_tmp6_ = ((OLLMchatOllamaOllamaBase*) _data_->self)->client;
	_data_->_tmp7_ = oll_mchat_ollama_client_get_tools (_data_->_tmp6_);
	_data_->_tmp8_ = _data_->_tmp7_;
	if (_data_->_tmp8_ != NULL) {
		_data_->_tmp9_ = ((OLLMchatOllamaOllamaBase*) _data_->self)->client;
		_data_->_tmp10_ = oll_mchat_ollama_client_get_tools (_data_->_tmp9_);
		_data_->_tmp11_ = _data_->_tmp10_;
		_data_->_tmp12_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _data_->_tmp11_);
		_data_->_tmp13_ = _data_->_tmp12_;
		_data_->_tmp5_ = _data_->_tmp13_ > 0;
	} else {
		_data_->_tmp5_ = FALSE;
	}
	if (_data_->_tmp5_) {
		_data_->_tmp14_ = _data_->self->priv->_tools;
		if (_data_->_tmp14_ == NULL) {
			_data_->_tmp15_ = gee_array_list_new (OLL_MCHAT_OLLAMA_TYPE_TOOL, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
			_data_->_tmp16_ = _data_->_tmp15_;
			oll_mchat_ollama_chat_call_set_tools (_data_->self, _data_->_tmp16_);
			_g_object_unref0 (_data_->_tmp16_);
		}
		{
			_data_->_tmp17_ = ((OLLMchatOllamaOllamaBase*) _data_->self)->client;
			_data_->_tmp18_ = oll_mchat_ollama_client_get_tools (_data_->_tmp17_);
			_data_->_tmp19_ = _data_->_tmp18_;
			_data_->_tool_list = _data_->_tmp19_;
			_data_->_tmp20_ = _data_->_tool_list;
			_data_->_tmp21_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _data_->_tmp20_);
			_data_->_tmp22_ = _data_->_tmp21_;
			_data_->_tool_size = _data_->_tmp22_;
			_data_->_tool_index = -1;
			while (TRUE) {
				_data_->_tool_index = _data_->_tool_index + 1;
				_data_->_tmp23_ = _data_->_tool_index;
				_data_->_tmp24_ = _data_->_tool_size;
				if (!(_data_->_tmp23_ < _data_->_tmp24_)) {
					break;
				}
				_data_->_tmp25_ = _data_->_tool_list;
				_data_->_tmp26_ = gee_abstract_list_get ((GeeAbstractList*) _data_->_tmp25_, _data_->_tool_index);
				_data_->tool = (OLLMchatOllamaTool*) _data_->_tmp26_;
				_data_->_tmp27_ = _data_->self->priv->_tools;
				_data_->_tmp28_ = _data_->tool;
				gee_abstract_collection_add ((GeeAbstractCollection*) _data_->_tmp27_, _data_->_tmp28_);
				_g_object_unref0 (_data_->tool);
			}
		}
	}
	_data_->_tmp29_ = _data_->self->priv->_stream;
	if (_data_->_tmp29_) {
		_data_->_tmp30_ = ((OLLMchatOllamaOllamaBase*) _data_->self)->client;
		_data_->_tmp31_ = oll_mchat_ollama_chat_response_new (_data_->_tmp30_);
		_g_object_unref0 (_data_->self->priv->streaming_response);
		_data_->self->priv->streaming_response = _data_->_tmp31_;
		_data_->_state_ = 1;
		oll_mchat_ollama_chat_call_execute_streaming (_data_->self, oll_mchat_ollama_chat_call_exec_chat_ready, _data_);
		return FALSE;
		_state_1:
		_data_->_tmp33_ = oll_mchat_ollama_chat_call_execute_streaming_finish (_data_->self, _data_->_res_, &_data_->_inner_error0_);
		_data_->_tmp32_ = _data_->_tmp33_;
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
			g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
			g_object_unref (_data_->_async_result);
			return FALSE;
		}
		_data_->_tmp34_ = _data_->_tmp32_;
		_data_->_tmp32_ = NULL;
		_data_->result = _data_->_tmp34_;
		_g_object_unref0 (_data_->_tmp32_);
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_state_ = 2;
	oll_mchat_ollama_chat_call_execute_non_streaming (_data_->self, oll_mchat_ollama_chat_call_exec_chat_ready, _data_);
	return FALSE;
	_state_2:
	_data_->_tmp36_ = oll_mchat_ollama_chat_call_execute_non_streaming_finish (_data_->self, _data_->_res_, &_data_->_inner_error0_);
	_data_->_tmp35_ = _data_->_tmp36_;
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp37_ = _data_->_tmp35_;
	_data_->_tmp35_ = NULL;
	_data_->result = _data_->_tmp37_;
	_g_object_unref0 (_data_->_tmp35_);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
oll_mchat_ollama_chat_call_execute_non_streaming_data_free (gpointer _data)
{
	OllMchatOllamaChatCallExecuteNonStreamingData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->result);
	_g_object_unref0 (_data_->self);
	g_slice_free (OllMchatOllamaChatCallExecuteNonStreamingData, _data_);
}

static void
oll_mchat_ollama_chat_call_execute_non_streaming (OLLMchatOllamaChatCall* self,
                                                  GAsyncReadyCallback _callback_,
                                                  gpointer _user_data_)
{
	OllMchatOllamaChatCallExecuteNonStreamingData* _data_;
	OLLMchatOllamaChatCall* _tmp0_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (OllMchatOllamaChatCallExecuteNonStreamingData);
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, oll_mchat_ollama_chat_call_execute_non_streaming_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	oll_mchat_ollama_chat_call_execute_non_streaming_co (_data_);
}

static OLLMchatOllamaChatResponse*
oll_mchat_ollama_chat_call_execute_non_streaming_finish (OLLMchatOllamaChatCall* self,
                                                         GAsyncResult* _res_,
                                                         GError** error)
{
	OLLMchatOllamaChatResponse* result;
	OllMchatOllamaChatCallExecuteNonStreamingData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), error);
	if (NULL == _data_) {
		return NULL;
	}
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
oll_mchat_ollama_chat_call_execute_non_streaming_ready (GObject* source_object,
                                                        GAsyncResult* _res_,
                                                        gpointer _user_data_)
{
	OllMchatOllamaChatCallExecuteNonStreamingData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	oll_mchat_ollama_chat_call_execute_non_streaming_co (_data_);
}

static gboolean
oll_mchat_ollama_chat_call_execute_non_streaming_co (OllMchatOllamaChatCallExecuteNonStreamingData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_state_ = 1;
	oll_mchat_ollama_base_call_send_request ((OLLMchatOllamaBaseCall*) _data_->self, TRUE, oll_mchat_ollama_chat_call_execute_non_streaming_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp0_ = oll_mchat_ollama_base_call_send_request_finish ((OLLMchatOllamaBaseCall*) _data_->self, _data_->_res_, &_data_->_inner_error0_);
	_data_->bytes = _data_->_tmp0_;
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp1_ = _data_->bytes;
	_data_->_tmp2_ = oll_mchat_ollama_base_call_parse_response ((OLLMchatOllamaBaseCall*) _data_->self, _data_->_tmp1_, &_data_->_inner_error0_);
	_data_->root = _data_->_tmp2_;
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		_g_bytes_unref0 (_data_->bytes);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp3_ = _data_->root;
	if (json_node_get_node_type (_data_->_tmp3_) != JSON_NODE_OBJECT) {
		_data_->_tmp4_ = g_error_new_literal (OLL_MCHAT_OLLAMA_OLLAMA_ERROR, OLL_MCHAT_OLLAMA_OLLAMA_ERROR_FAILED, "Invalid JSON response");
		_data_->_inner_error0_ = _data_->_tmp4_;
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		__vala_JsonNode_free0 (_data_->root);
		_g_bytes_unref0 (_data_->bytes);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp5_ = json_generator_new ();
	_data_->generator = _data_->_tmp5_;
	_data_->_tmp6_ = _data_->generator;
	_data_->_tmp7_ = _data_->root;
	json_generator_set_root (_data_->_tmp6_, _data_->_tmp7_);
	_data_->_tmp8_ = _data_->generator;
	_data_->_tmp9_ = json_generator_to_data (_data_->_tmp8_, NULL);
	_data_->json_str = _data_->_tmp9_;
	_data_->_tmp11_ = _data_->json_str;
	_data_->_tmp12_ = json_gobject_from_data (OLL_MCHAT_OLLAMA_TYPE_CHAT_RESPONSE, _data_->_tmp11_, (gssize) -1, &_data_->_inner_error0_);
	_data_->_tmp10_ = _data_->_tmp12_;
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		_g_free0 (_data_->json_str);
		_g_object_unref0 (_data_->generator);
		__vala_JsonNode_free0 (_data_->root);
		_g_bytes_unref0 (_data_->bytes);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp13_ = _g_object_ref0 (OLL_MCHAT_OLLAMA_IS_CHAT_RESPONSE (_data_->_tmp10_) ? ((OLLMchatOllamaChatResponse*) _data_->_tmp10_) : NULL);
	_data_->response_obj = _data_->_tmp13_;
	_data_->_tmp14_ = _data_->response_obj;
	if (_data_->_tmp14_ == NULL) {
		_data_->_tmp15_ = g_error_new_literal (OLL_MCHAT_OLLAMA_OLLAMA_ERROR, OLL_MCHAT_OLLAMA_OLLAMA_ERROR_FAILED, "Failed to parse response");
		_data_->_inner_error0_ = _data_->_tmp15_;
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		_g_object_unref0 (_data_->response_obj);
		_g_object_unref0 (_data_->_tmp10_);
		_g_free0 (_data_->json_str);
		_g_object_unref0 (_data_->generator);
		__vala_JsonNode_free0 (_data_->root);
		_g_bytes_unref0 (_data_->bytes);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp16_ = _data_->response_obj;
	_data_->_tmp17_ = ((OLLMchatOllamaOllamaBase*) _data_->self)->client;
	_data_->_tmp18_ = _g_object_ref0 (_data_->_tmp17_);
	_g_object_unref0 (((OLLMchatOllamaOllamaBase*) _data_->_tmp16_)->client);
	((OLLMchatOllamaOllamaBase*) _data_->_tmp16_)->client = _data_->_tmp18_;
	_data_->result = _data_->response_obj;
	_g_object_unref0 (_data_->_tmp10_);
	_g_free0 (_data_->json_str);
	_g_object_unref0 (_data_->generator);
	__vala_JsonNode_free0 (_data_->root);
	_g_bytes_unref0 (_data_->bytes);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
oll_mchat_ollama_chat_call_execute_streaming_data_free (gpointer _data)
{
	OllMchatOllamaChatCallExecuteStreamingData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->result);
	_g_object_unref0 (_data_->self);
	g_slice_free (OllMchatOllamaChatCallExecuteStreamingData, _data_);
}

static void
oll_mchat_ollama_chat_call_execute_streaming (OLLMchatOllamaChatCall* self,
                                              GAsyncReadyCallback _callback_,
                                              gpointer _user_data_)
{
	OllMchatOllamaChatCallExecuteStreamingData* _data_;
	OLLMchatOllamaChatCall* _tmp0_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (OllMchatOllamaChatCallExecuteStreamingData);
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, oll_mchat_ollama_chat_call_execute_streaming_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	oll_mchat_ollama_chat_call_execute_streaming_co (_data_);
}

static OLLMchatOllamaChatResponse*
oll_mchat_ollama_chat_call_execute_streaming_finish (OLLMchatOllamaChatCall* self,
                                                     GAsyncResult* _res_,
                                                     GError** error)
{
	OLLMchatOllamaChatResponse* result;
	OllMchatOllamaChatCallExecuteStreamingData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), error);
	if (NULL == _data_) {
		return NULL;
	}
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
__lambda4_ (OLLMchatOllamaChatCall* self,
            JsonObject* chunk)
{
	g_return_if_fail (chunk != NULL);
	oll_mchat_ollama_chat_call_process_streaming_chunk (self, chunk);
}

static void
___lambda4__oll_mchat_ollama_base_call_streaming_chunk_callback (JsonObject* chunk,
                                                                 gpointer self)
{
	__lambda4_ ((OLLMchatOllamaChatCall*) self, chunk);
}

static void
oll_mchat_ollama_chat_call_execute_streaming_ready (GObject* source_object,
                                                    GAsyncResult* _res_,
                                                    gpointer _user_data_)
{
	OllMchatOllamaChatCallExecuteStreamingData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	oll_mchat_ollama_chat_call_execute_streaming_co (_data_);
}

static gboolean
oll_mchat_ollama_chat_call_execute_streaming_co (OllMchatOllamaChatCallExecuteStreamingData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->streaming_response;
	if (_data_->_tmp0_ == NULL) {
		_data_->_tmp1_ = g_error_new_literal (OLL_MCHAT_OLLAMA_OLLAMA_ERROR, OLL_MCHAT_OLLAMA_OLLAMA_ERROR_FAILED, "Streaming response not initialized");
		_data_->_inner_error0_ = _data_->_tmp1_;
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp2_ = oll_mchat_ollama_base_call_build_url ((OLLMchatOllamaBaseCall*) _data_->self);
	_data_->url = _data_->_tmp2_;
	_data_->_tmp3_ = soup_session_new ();
	_data_->session = _data_->_tmp3_;
	_data_->_tmp4_ = oll_mchat_ollama_base_call_get_request_body ((OLLMchatOllamaBaseCall*) _data_->self);
	_data_->request_body = _data_->_tmp4_;
	_data_->_tmp5_ = oll_mchat_ollama_chat_call_create_streaming_message (_data_->self, _data_->url, _data_->request_body);
	_data_->message = _data_->_tmp5_;
	g_debug ("ChatCall.vala:131: Request URL: %s", _data_->url);
	g_debug ("ChatCall.vala:132: Request Body: %s", _data_->request_body);
	_data_->_tmp6_ = _data_->self->priv->_format;
	_data_->is_json_format = g_strcmp0 (_data_->_tmp6_, "json") == 0;
	_data_->_state_ = 1;
	oll_mchat_ollama_base_call_handle_streaming_response ((OLLMchatOllamaBaseCall*) _data_->self, _data_->session, _data_->message, _data_->is_json_format, ___lambda4__oll_mchat_ollama_base_call_streaming_chunk_callback, _data_->self, oll_mchat_ollama_chat_call_execute_streaming_ready, _data_);
	return FALSE;
	_state_1:
	oll_mchat_ollama_base_call_handle_streaming_response_finish ((OLLMchatOllamaBaseCall*) _data_->self, _data_->_res_, &_data_->_inner_error0_);
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		_g_object_unref0 (_data_->message);
		_g_free0 (_data_->request_body);
		_g_object_unref0 (_data_->session);
		_g_free0 (_data_->url);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp7_ = _data_->self->priv->streaming_response;
	_data_->_tmp8_ = _g_object_ref0 (_data_->_tmp7_);
	_data_->result = _data_->_tmp8_;
	_g_object_unref0 (_data_->message);
	_g_free0 (_data_->request_body);
	_g_object_unref0 (_data_->session);
	_g_free0 (_data_->url);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static guint8*
string_get_data (const gchar* self,
                 gint* result_length1)
{
	guint8* result;
	guint8* res = NULL;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	gint _tmp1_;
	guint8* _tmp2_;
	gint _tmp2__length1;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res;
	_tmp2__length1 = res_length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	return result;
}

static SoupMessage*
oll_mchat_ollama_chat_call_create_streaming_message (OLLMchatOllamaChatCall* self,
                                                     const gchar* url,
                                                     const gchar* request_body)
{
	SoupMessage* message = NULL;
	const gchar* _tmp0_;
	SoupMessage* _tmp1_;
	gboolean _tmp2_ = FALSE;
	OLLMchatOllamaClient* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	SoupMessage* _tmp18_;
	guint8* _tmp19_;
	gint _tmp19__length1;
	gint _tmp20_ = 0;
	guint8* _tmp21_;
	gint _tmp21__length1;
	GBytes* _tmp22_;
	GBytes* _tmp23_;
	SoupMessage* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (url != NULL, NULL);
	g_return_val_if_fail (request_body != NULL, NULL);
	_tmp0_ = ((OLLMchatOllamaBaseCall*) self)->http_method;
	_tmp1_ = soup_message_new (_tmp0_, url);
	message = _tmp1_;
	_tmp3_ = ((OLLMchatOllamaOllamaBase*) self)->client;
	_tmp4_ = oll_mchat_ollama_client_get_api_key (_tmp3_);
	_tmp5_ = _tmp4_;
	if (_tmp5_ != NULL) {
		OLLMchatOllamaClient* _tmp6_;
		const gchar* _tmp7_;
		const gchar* _tmp8_;
		_tmp6_ = ((OLLMchatOllamaOllamaBase*) self)->client;
		_tmp7_ = oll_mchat_ollama_client_get_api_key (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp2_ = g_strcmp0 (_tmp8_, "") != 0;
	} else {
		_tmp2_ = FALSE;
	}
	if (_tmp2_) {
		SoupMessage* _tmp9_;
		SoupMessageHeaders* _tmp10_;
		SoupMessageHeaders* _tmp11_;
		OLLMchatOllamaClient* _tmp12_;
		const gchar* _tmp13_;
		const gchar* _tmp14_;
		const gchar* _tmp15_;
		gchar* _tmp16_;
		gchar* _tmp17_;
		_tmp9_ = message;
		_tmp10_ = soup_message_get_request_headers (_tmp9_);
		_tmp11_ = _tmp10_;
		_tmp12_ = ((OLLMchatOllamaOllamaBase*) self)->client;
		_tmp13_ = oll_mchat_ollama_client_get_api_key (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp15_ = string_to_string (_tmp14_);
		_tmp16_ = g_strconcat ("Bearer ", _tmp15_, NULL);
		_tmp17_ = _tmp16_;
		soup_message_headers_append (_tmp11_, "Authorization", _tmp17_);
		_g_free0 (_tmp17_);
	}
	_tmp18_ = message;
	_tmp19_ = string_get_data (request_body, &_tmp20_);
	_tmp19__length1 = _tmp20_;
	_tmp21_ = _tmp19_;
	_tmp21__length1 = _tmp19__length1;
	_tmp22_ = g_bytes_new (_tmp21_, _tmp21__length1);
	_tmp23_ = _tmp22_;
	soup_message_set_request_body_from_bytes (_tmp18_, "application/json", _tmp23_);
	_g_bytes_unref0 (_tmp23_);
	result = message;
	return result;
}

static void
oll_mchat_ollama_chat_call_process_streaming_chunk (OLLMchatOllamaChatCall* self,
                                                    JsonObject* chunk)
{
	OLLMchatOllamaChatResponse* _tmp0_;
	gchar* new_text = NULL;
	OLLMchatOllamaChatResponse* _tmp1_;
	gchar* _tmp2_;
	OLLMchatOllamaClient* _tmp3_;
	OLLMchatOllamaStreamCallback _tmp4_ = NULL;
	gpointer _tmp4__target = NULL;
	OLLMchatOllamaStreamCallback _tmp5_;
	gpointer _tmp5__target;
	g_return_if_fail (self != NULL);
	g_return_if_fail (chunk != NULL);
	_tmp0_ = self->priv->streaming_response;
	if (_tmp0_ == NULL) {
		return;
	}
	_tmp1_ = self->priv->streaming_response;
	_tmp2_ = oll_mchat_ollama_chat_response_addChunk (_tmp1_, chunk);
	new_text = _tmp2_;
	_tmp3_ = ((OLLMchatOllamaOllamaBase*) self)->client;
	_tmp4_ = oll_mchat_ollama_client_get_stream_callback (_tmp3_, &_tmp4__target);
	_tmp5_ = _tmp4_;
	_tmp5__target = _tmp4__target;
	if (_tmp5_ != NULL) {
		OLLMchatOllamaClient* _tmp6_;
		OLLMchatOllamaStreamCallback _tmp7_ = NULL;
		gpointer _tmp7__target = NULL;
		OLLMchatOllamaStreamCallback _tmp8_;
		gpointer _tmp8__target;
		const gchar* _tmp9_;
		OLLMchatOllamaChatResponse* _tmp10_;
		_tmp6_ = ((OLLMchatOllamaOllamaBase*) self)->client;
		_tmp7_ = oll_mchat_ollama_client_get_stream_callback (_tmp6_, &_tmp7__target);
		_tmp8_ = _tmp7_;
		_tmp8__target = _tmp7__target;
		_tmp9_ = new_text;
		_tmp10_ = self->priv->streaming_response;
		_tmp8_ (_tmp9_, _tmp10_, _tmp8__target);
	}
	_g_free0 (new_text);
}

const gchar*
oll_mchat_ollama_chat_call_get_model (OLLMchatOllamaChatCall* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_model;
	result = _tmp0_;
	return result;
}

void
oll_mchat_ollama_chat_call_set_model (OLLMchatOllamaChatCall* self,
                                      const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_ollama_chat_call_get_model (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_model);
		self->priv->_model = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_MODEL_PROPERTY]);
	}
}

GeeArrayList*
oll_mchat_ollama_chat_call_get_tools (OLLMchatOllamaChatCall* self)
{
	GeeArrayList* result;
	GeeArrayList* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tools;
	result = _tmp0_;
	return result;
}

void
oll_mchat_ollama_chat_call_set_tools (OLLMchatOllamaChatCall* self,
                                      GeeArrayList* value)
{
	GeeArrayList* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_ollama_chat_call_get_tools (self);
	if (old_value != value) {
		GeeArrayList* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_tools);
		self->priv->_tools = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_TOOLS_PROPERTY]);
	}
}

gboolean
oll_mchat_ollama_chat_call_get_stream (OLLMchatOllamaChatCall* self)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_stream;
	return result;
}

void
oll_mchat_ollama_chat_call_set_stream (OLLMchatOllamaChatCall* self,
                                       gboolean value)
{
	gboolean old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_ollama_chat_call_get_stream (self);
	if (old_value != value) {
		self->priv->_stream = value;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_STREAM_PROPERTY]);
	}
}

const gchar*
oll_mchat_ollama_chat_call_get_format (OLLMchatOllamaChatCall* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_format;
	result = _tmp0_;
	return result;
}

void
oll_mchat_ollama_chat_call_set_format (OLLMchatOllamaChatCall* self,
                                       const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_ollama_chat_call_get_format (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_format);
		self->priv->_format = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_FORMAT_PROPERTY]);
	}
}

JsonObject*
oll_mchat_ollama_chat_call_get_options (OLLMchatOllamaChatCall* self)
{
	JsonObject* result;
	JsonObject* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_options;
	result = _tmp0_;
	return result;
}

static gpointer
_json_object_ref0 (gpointer self)
{
	return self ? json_object_ref (self) : NULL;
}

void
oll_mchat_ollama_chat_call_set_options (OLLMchatOllamaChatCall* self,
                                        JsonObject* value)
{
	JsonObject* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_ollama_chat_call_get_options (self);
	if (old_value != value) {
		JsonObject* _tmp0_;
		_tmp0_ = _json_object_ref0 (value);
		_json_object_unref0 (self->priv->_options);
		self->priv->_options = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_OPTIONS_PROPERTY]);
	}
}

gboolean
oll_mchat_ollama_chat_call_get_think (OLLMchatOllamaChatCall* self)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_think;
	return result;
}

void
oll_mchat_ollama_chat_call_set_think (OLLMchatOllamaChatCall* self,
                                      gboolean value)
{
	gboolean old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_ollama_chat_call_get_think (self);
	if (old_value != value) {
		self->priv->_think = value;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_THINK_PROPERTY]);
	}
}

const gchar*
oll_mchat_ollama_chat_call_get_keep_alive (OLLMchatOllamaChatCall* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_keep_alive;
	result = _tmp0_;
	return result;
}

void
oll_mchat_ollama_chat_call_set_keep_alive (OLLMchatOllamaChatCall* self,
                                           const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_ollama_chat_call_get_keep_alive (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_keep_alive);
		self->priv->_keep_alive = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_KEEP_ALIVE_PROPERTY]);
	}
}

GeeArrayList*
oll_mchat_ollama_chat_call_get_messages (OLLMchatOllamaChatCall* self)
{
	GeeArrayList* result;
	GeeArrayList* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_messages;
	result = _tmp0_;
	return result;
}

void
oll_mchat_ollama_chat_call_set_messages (OLLMchatOllamaChatCall* self,
                                         GeeArrayList* value)
{
	GeeArrayList* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_ollama_chat_call_get_messages (self);
	if (old_value != value) {
		GeeArrayList* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_messages);
		self->priv->_messages = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_MESSAGES_PROPERTY]);
	}
}

static JsonObject*
oll_mchat_ollama_chat_call_real_get_message (OLLMchatOllamaMessageInterface* base)
{
	JsonObject* result;
	OLLMchatOllamaChatCall* self;
	JsonObject* msg_obj = NULL;
	JsonObject* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	self = (OLLMchatOllamaChatCall*) base;
	_tmp0_ = json_object_new ();
	msg_obj = _tmp0_;
	_tmp1_ = oll_mchat_ollama_message_interface_get_chat_role ((OLLMchatOllamaMessageInterface*) self);
	_tmp2_ = _tmp1_;
	json_object_set_string_member (msg_obj, "role", _tmp2_);
	_tmp3_ = oll_mchat_ollama_message_interface_get_chat_content ((OLLMchatOllamaMessageInterface*) self);
	_tmp4_ = _tmp3_;
	json_object_set_string_member (msg_obj, "content", _tmp4_);
	result = msg_obj;
	return result;
}

static void
oll_mchat_ollama_chat_call_class_init (OLLMchatOllamaChatCallClass * klass,
                                       gpointer klass_data)
{
	oll_mchat_ollama_chat_call_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &OLLMchatOllamaChatCall_private_offset);
	((OLLMchatOllamaOllamaBaseClass *) klass)->serialize_property = (JsonNode* (*) (OLLMchatOllamaOllamaBase*, const gchar*, GValue*, GParamSpec*)) oll_mchat_ollama_chat_call_real_serialize_property;
	G_OBJECT_CLASS (klass)->get_property = _vala_oll_mchat_ollama_chat_call_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_oll_mchat_ollama_chat_call_set_property;
	G_OBJECT_CLASS (klass)->finalize = oll_mchat_ollama_chat_call_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_OLLAMA_CHAT_CALL_MODEL_PROPERTY, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_MODEL_PROPERTY] = g_param_spec_string ("model", "model", "model", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_OLLAMA_CHAT_CALL_TOOLS_PROPERTY, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_TOOLS_PROPERTY] = g_param_spec_object ("tools", "tools", "tools", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_OLLAMA_CHAT_CALL_STREAM_PROPERTY, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_STREAM_PROPERTY] = g_param_spec_boolean ("stream", "stream", "stream", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_OLLAMA_CHAT_CALL_FORMAT_PROPERTY, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_FORMAT_PROPERTY] = g_param_spec_string ("format", "format", "format", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_OLLAMA_CHAT_CALL_OPTIONS_PROPERTY, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_OPTIONS_PROPERTY] = g_param_spec_boxed ("options", "options", "options", json_object_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_OLLAMA_CHAT_CALL_THINK_PROPERTY, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_THINK_PROPERTY] = g_param_spec_boolean ("think", "think", "think", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_OLLAMA_CHAT_CALL_KEEP_ALIVE_PROPERTY, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_KEEP_ALIVE_PROPERTY] = g_param_spec_string ("keep-alive", "keep-alive", "keep-alive", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_OLLAMA_CHAT_CALL_MESSAGES_PROPERTY, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_MESSAGES_PROPERTY] = g_param_spec_object ("messages", "messages", "messages", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_OLLAMA_CHAT_CALL_MESSAGE_PROPERTY, oll_mchat_ollama_chat_call_properties[OLL_MCHAT_OLLAMA_CHAT_CALL_MESSAGE_PROPERTY] = g_param_spec_boxed ("message", "message", "message", json_object_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
}

static void
oll_mchat_ollama_chat_call_oll_mchat_ollama_message_interface_interface_init (OLLMchatOllamaMessageInterfaceIface * iface,
                                                                              gpointer iface_data)
{
	oll_mchat_ollama_chat_call_oll_mchat_ollama_message_interface_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_message = oll_mchat_ollama_chat_call_real_get_message;
	iface->get_chat_role = (const gchar* (*) (OLLMchatOllamaOllamaBase*)) oll_mchat_ollama_ollama_base_get_chat_role;
	iface->set_chat_role = (void (*) (OLLMchatOllamaOllamaBase*, const gchar*)) oll_mchat_ollama_ollama_base_set_chat_role;
	iface->get_chat_content = (const gchar* (*) (OLLMchatOllamaOllamaBase*)) oll_mchat_ollama_ollama_base_get_chat_content;
	iface->set_chat_content = (void (*) (OLLMchatOllamaOllamaBase*, const gchar*)) oll_mchat_ollama_ollama_base_set_chat_content;
}

static void
oll_mchat_ollama_chat_call_instance_init (OLLMchatOllamaChatCall * self,
                                          gpointer klass)
{
	gchar* _tmp0_;
	GeeArrayList* _tmp1_;
	self->priv = oll_mchat_ollama_chat_call_get_instance_private (self);
	_tmp0_ = g_strdup ("");
	self->priv->_model = _tmp0_;
	self->priv->_stream = FALSE;
	self->priv->_think = FALSE;
	_tmp1_ = gee_array_list_new (OLL_MCHAT_OLLAMA_TYPE_MESSAGE_INTERFACE, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	self->priv->_messages = _tmp1_;
}

static void
oll_mchat_ollama_chat_call_finalize (GObject * obj)
{
	OLLMchatOllamaChatCall * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, OLL_MCHAT_OLLAMA_TYPE_CHAT_CALL, OLLMchatOllamaChatCall);
	_g_free0 (self->priv->_model);
	_g_object_unref0 (self->priv->_tools);
	_g_free0 (self->priv->_format);
	_json_object_unref0 (self->priv->_options);
	_g_free0 (self->priv->_keep_alive);
	_g_object_unref0 (self->priv->_messages);
	_g_object_unref0 (self->priv->streaming_response);
	G_OBJECT_CLASS (oll_mchat_ollama_chat_call_parent_class)->finalize (obj);
}

 G_GNUC_NO_INLINE static GType
oll_mchat_ollama_chat_call_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (OLLMchatOllamaChatCallClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mchat_ollama_chat_call_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OLLMchatOllamaChatCall), 0, (GInstanceInitFunc) oll_mchat_ollama_chat_call_instance_init, NULL };
	static const GInterfaceInfo oll_mchat_ollama_message_interface_info = { (GInterfaceInitFunc) oll_mchat_ollama_chat_call_oll_mchat_ollama_message_interface_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType oll_mchat_ollama_chat_call_type_id;
	oll_mchat_ollama_chat_call_type_id = g_type_register_static (OLL_MCHAT_OLLAMA_TYPE_BASE_CALL, "OLLMchatOllamaChatCall", &g_define_type_info, 0);
	g_type_add_interface_static (oll_mchat_ollama_chat_call_type_id, OLL_MCHAT_OLLAMA_TYPE_MESSAGE_INTERFACE, &oll_mchat_ollama_message_interface_info);
	OLLMchatOllamaChatCall_private_offset = g_type_add_instance_private (oll_mchat_ollama_chat_call_type_id, sizeof (OLLMchatOllamaChatCallPrivate));
	return oll_mchat_ollama_chat_call_type_id;
}

GType
oll_mchat_ollama_chat_call_get_type (void)
{
	static gsize oll_mchat_ollama_chat_call_type_id__once = 0;
	if (g_once_init_enter (&oll_mchat_ollama_chat_call_type_id__once)) {
		GType oll_mchat_ollama_chat_call_type_id;
		oll_mchat_ollama_chat_call_type_id = oll_mchat_ollama_chat_call_get_type_once ();
		g_once_init_leave (&oll_mchat_ollama_chat_call_type_id__once, oll_mchat_ollama_chat_call_type_id);
	}
	return oll_mchat_ollama_chat_call_type_id__once;
}

static void
_vala_oll_mchat_ollama_chat_call_get_property (GObject * object,
                                               guint property_id,
                                               GValue * value,
                                               GParamSpec * pspec)
{
	OLLMchatOllamaChatCall * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_OLLAMA_TYPE_CHAT_CALL, OLLMchatOllamaChatCall);
	switch (property_id) {
		case OLL_MCHAT_OLLAMA_CHAT_CALL_MODEL_PROPERTY:
		g_value_set_string (value, oll_mchat_ollama_chat_call_get_model (self));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_TOOLS_PROPERTY:
		g_value_set_object (value, oll_mchat_ollama_chat_call_get_tools (self));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_STREAM_PROPERTY:
		g_value_set_boolean (value, oll_mchat_ollama_chat_call_get_stream (self));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_FORMAT_PROPERTY:
		g_value_set_string (value, oll_mchat_ollama_chat_call_get_format (self));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_OPTIONS_PROPERTY:
		g_value_set_boxed (value, oll_mchat_ollama_chat_call_get_options (self));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_THINK_PROPERTY:
		g_value_set_boolean (value, oll_mchat_ollama_chat_call_get_think (self));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_KEEP_ALIVE_PROPERTY:
		g_value_set_string (value, oll_mchat_ollama_chat_call_get_keep_alive (self));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_MESSAGES_PROPERTY:
		g_value_set_object (value, oll_mchat_ollama_chat_call_get_messages (self));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_MESSAGE_PROPERTY:
		g_value_take_boxed (value, oll_mchat_ollama_message_interface_get_message ((OLLMchatOllamaMessageInterface*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_oll_mchat_ollama_chat_call_set_property (GObject * object,
                                               guint property_id,
                                               const GValue * value,
                                               GParamSpec * pspec)
{
	OLLMchatOllamaChatCall * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_OLLAMA_TYPE_CHAT_CALL, OLLMchatOllamaChatCall);
	switch (property_id) {
		case OLL_MCHAT_OLLAMA_CHAT_CALL_MODEL_PROPERTY:
		oll_mchat_ollama_chat_call_set_model (self, g_value_get_string (value));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_TOOLS_PROPERTY:
		oll_mchat_ollama_chat_call_set_tools (self, g_value_get_object (value));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_STREAM_PROPERTY:
		oll_mchat_ollama_chat_call_set_stream (self, g_value_get_boolean (value));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_FORMAT_PROPERTY:
		oll_mchat_ollama_chat_call_set_format (self, g_value_get_string (value));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_OPTIONS_PROPERTY:
		oll_mchat_ollama_chat_call_set_options (self, g_value_get_boxed (value));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_THINK_PROPERTY:
		oll_mchat_ollama_chat_call_set_think (self, g_value_get_boolean (value));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_KEEP_ALIVE_PROPERTY:
		oll_mchat_ollama_chat_call_set_keep_alive (self, g_value_get_string (value));
		break;
		case OLL_MCHAT_OLLAMA_CHAT_CALL_MESSAGES_PROPERTY:
		oll_mchat_ollama_chat_call_set_messages (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

