/* PsCall.vala.c generated by valac 0.56.18, the Vala compiler
 * generated from PsCall.vala, do not modify */

#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <gee.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE (oll_mchat_ollama_ollama_base_get_type ())
#define OLL_MCHAT_OLLAMA_OLLAMA_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE, OLLMchatOllamaOllamaBase))
#define OLL_MCHAT_OLLAMA_OLLAMA_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE, OLLMchatOllamaOllamaBaseClass))
#define OLL_MCHAT_OLLAMA_IS_OLLAMA_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE))
#define OLL_MCHAT_OLLAMA_IS_OLLAMA_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE))
#define OLL_MCHAT_OLLAMA_OLLAMA_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_OLLAMA_BASE, OLLMchatOllamaOllamaBaseClass))

typedef struct _OLLMchatOllamaOllamaBase OLLMchatOllamaOllamaBase;
typedef struct _OLLMchatOllamaOllamaBaseClass OLLMchatOllamaOllamaBaseClass;
typedef struct _OLLMchatOllamaOllamaBasePrivate OLLMchatOllamaOllamaBasePrivate;

#define OLL_MCHAT_OLLAMA_TYPE_CLIENT (oll_mchat_ollama_client_get_type ())
#define OLL_MCHAT_OLLAMA_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_CLIENT, OLLMchatOllamaClient))
#define OLL_MCHAT_OLLAMA_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_CLIENT, OLLMchatOllamaClientClass))
#define OLL_MCHAT_OLLAMA_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_CLIENT))
#define OLL_MCHAT_OLLAMA_IS_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_CLIENT))
#define OLL_MCHAT_OLLAMA_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_CLIENT, OLLMchatOllamaClientClass))

typedef struct _OLLMchatOllamaClient OLLMchatOllamaClient;
typedef struct _OLLMchatOllamaClientClass OLLMchatOllamaClientClass;

#define OLL_MCHAT_OLLAMA_TYPE_BASE_CALL (oll_mchat_ollama_base_call_get_type ())
#define OLL_MCHAT_OLLAMA_BASE_CALL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_CALL, OLLMchatOllamaBaseCall))
#define OLL_MCHAT_OLLAMA_BASE_CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_BASE_CALL, OLLMchatOllamaBaseCallClass))
#define OLL_MCHAT_OLLAMA_IS_BASE_CALL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_CALL))
#define OLL_MCHAT_OLLAMA_IS_BASE_CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_BASE_CALL))
#define OLL_MCHAT_OLLAMA_BASE_CALL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_CALL, OLLMchatOllamaBaseCallClass))

typedef struct _OLLMchatOllamaBaseCall OLLMchatOllamaBaseCall;
typedef struct _OLLMchatOllamaBaseCallClass OLLMchatOllamaBaseCallClass;
typedef struct _OLLMchatOllamaBaseCallPrivate OLLMchatOllamaBaseCallPrivate;

#define OLL_MCHAT_OLLAMA_TYPE_PS_CALL (oll_mchat_ollama_ps_call_get_type ())
#define OLL_MCHAT_OLLAMA_PS_CALL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_PS_CALL, OLLMchatOllamaPsCall))
#define OLL_MCHAT_OLLAMA_PS_CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_PS_CALL, OLLMchatOllamaPsCallClass))
#define OLL_MCHAT_OLLAMA_IS_PS_CALL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_PS_CALL))
#define OLL_MCHAT_OLLAMA_IS_PS_CALL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_PS_CALL))
#define OLL_MCHAT_OLLAMA_PS_CALL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_PS_CALL, OLLMchatOllamaPsCallClass))

typedef struct _OLLMchatOllamaPsCall OLLMchatOllamaPsCall;
typedef struct _OLLMchatOllamaPsCallClass OLLMchatOllamaPsCallClass;
typedef struct _OLLMchatOllamaPsCallPrivate OLLMchatOllamaPsCallPrivate;
enum  {
	OLL_MCHAT_OLLAMA_PS_CALL_0_PROPERTY,
	OLL_MCHAT_OLLAMA_PS_CALL_NUM_PROPERTIES
};
static GParamSpec* oll_mchat_ollama_ps_call_properties[OLL_MCHAT_OLLAMA_PS_CALL_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE (oll_mchat_ollama_base_response_get_type ())
#define OLL_MCHAT_OLLAMA_BASE_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE, OLLMchatOllamaBaseResponse))
#define OLL_MCHAT_OLLAMA_BASE_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE, OLLMchatOllamaBaseResponseClass))
#define OLL_MCHAT_OLLAMA_IS_BASE_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE))
#define OLL_MCHAT_OLLAMA_IS_BASE_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE))
#define OLL_MCHAT_OLLAMA_BASE_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_BASE_RESPONSE, OLLMchatOllamaBaseResponseClass))

typedef struct _OLLMchatOllamaBaseResponse OLLMchatOllamaBaseResponse;
typedef struct _OLLMchatOllamaBaseResponseClass OLLMchatOllamaBaseResponseClass;

#define OLL_MCHAT_OLLAMA_TYPE_MODEL (oll_mchat_ollama_model_get_type ())
#define OLL_MCHAT_OLLAMA_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_OLLAMA_TYPE_MODEL, OLLMchatOllamaModel))
#define OLL_MCHAT_OLLAMA_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_OLLAMA_TYPE_MODEL, OLLMchatOllamaModelClass))
#define OLL_MCHAT_OLLAMA_IS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_OLLAMA_TYPE_MODEL))
#define OLL_MCHAT_OLLAMA_IS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_OLLAMA_TYPE_MODEL))
#define OLL_MCHAT_OLLAMA_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_OLLAMA_TYPE_MODEL, OLLMchatOllamaModelClass))

typedef struct _OLLMchatOllamaModel OLLMchatOllamaModel;
typedef struct _OLLMchatOllamaModelClass OLLMchatOllamaModelClass;
typedef struct _OllMchatOllamaPsCallExecModelsData OllMchatOllamaPsCallExecModelsData;

struct _OLLMchatOllamaOllamaBase {
	GObject parent_instance;
	OLLMchatOllamaOllamaBasePrivate * priv;
	OLLMchatOllamaClient* client;
};

struct _OLLMchatOllamaOllamaBaseClass {
	GObjectClass parent_class;
	JsonNode* (*serialize_property) (OLLMchatOllamaOllamaBase* self, const gchar* property_name, GValue* value, GParamSpec* pspec);
};

struct _OLLMchatOllamaBaseCall {
	OLLMchatOllamaOllamaBase parent_instance;
	OLLMchatOllamaBaseCallPrivate * priv;
	gchar* url_endpoint;
	gchar* http_method;
};

struct _OLLMchatOllamaBaseCallClass {
	OLLMchatOllamaOllamaBaseClass parent_class;
};

struct _OLLMchatOllamaPsCall {
	OLLMchatOllamaBaseCall parent_instance;
	OLLMchatOllamaPsCallPrivate * priv;
};

struct _OLLMchatOllamaPsCallClass {
	OLLMchatOllamaBaseCallClass parent_class;
};

struct _OllMchatOllamaPsCallExecModelsData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	OLLMchatOllamaPsCall* self;
	GeeArrayList* result;
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
	GeeArrayList* _tmp2_;
	GError* _inner_error0_;
};

static gpointer oll_mchat_ollama_ps_call_parent_class = NULL;

VALA_EXTERN GType oll_mchat_ollama_ollama_base_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaOllamaBase, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_client_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaClient, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_base_call_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaBaseCall, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_ps_call_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaPsCall, g_object_unref)
VALA_EXTERN OLLMchatOllamaPsCall* oll_mchat_ollama_ps_call_new (OLLMchatOllamaClient* client);
VALA_EXTERN OLLMchatOllamaPsCall* oll_mchat_ollama_ps_call_construct (GType object_type,
                                                          OLLMchatOllamaClient* client);
VALA_EXTERN OLLMchatOllamaBaseCall* oll_mchat_ollama_base_call_construct (GType object_type,
                                                              OLLMchatOllamaClient* client);
static void oll_mchat_ollama_ps_call_exec_models_data_free (gpointer _data);
VALA_EXTERN GType oll_mchat_ollama_base_response_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaBaseResponse, g_object_unref)
VALA_EXTERN GType oll_mchat_ollama_model_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatOllamaModel, g_object_unref)
VALA_EXTERN void oll_mchat_ollama_ps_call_exec_models (OLLMchatOllamaPsCall* self,
                                           GAsyncReadyCallback _callback_,
                                           gpointer _user_data_);
VALA_EXTERN GeeArrayList* oll_mchat_ollama_ps_call_exec_models_finish (OLLMchatOllamaPsCall* self,
                                                           GAsyncResult* _res_,
                                                           GError** error);
static gboolean oll_mchat_ollama_ps_call_exec_models_co (OllMchatOllamaPsCallExecModelsData* _data_);
VALA_EXTERN void oll_mchat_ollama_base_call_get_models (OLLMchatOllamaBaseCall* self,
                                            const gchar* field_name,
                                            GAsyncReadyCallback _callback_,
                                            gpointer _user_data_);
VALA_EXTERN GeeArrayList* oll_mchat_ollama_base_call_get_models_finish (OLLMchatOllamaBaseCall* self,
                                                            GAsyncResult* _res_,
                                                            GError** error);
static void oll_mchat_ollama_ps_call_exec_models_ready (GObject* source_object,
                                                 GAsyncResult* _res_,
                                                 gpointer _user_data_);
static GType oll_mchat_ollama_ps_call_get_type_once (void);

OLLMchatOllamaPsCall*
oll_mchat_ollama_ps_call_construct (GType object_type,
                                    OLLMchatOllamaClient* client)
{
	OLLMchatOllamaPsCall * self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (client != NULL, NULL);
	self = (OLLMchatOllamaPsCall*) oll_mchat_ollama_base_call_construct (object_type, client);
	_tmp0_ = g_strdup ("ps");
	_g_free0 (((OLLMchatOllamaBaseCall*) self)->url_endpoint);
	((OLLMchatOllamaBaseCall*) self)->url_endpoint = _tmp0_;
	_tmp1_ = g_strdup ("GET");
	_g_free0 (((OLLMchatOllamaBaseCall*) self)->http_method);
	((OLLMchatOllamaBaseCall*) self)->http_method = _tmp1_;
	return self;
}

OLLMchatOllamaPsCall*
oll_mchat_ollama_ps_call_new (OLLMchatOllamaClient* client)
{
	return oll_mchat_ollama_ps_call_construct (OLL_MCHAT_OLLAMA_TYPE_PS_CALL, client);
}

static void
oll_mchat_ollama_ps_call_exec_models_data_free (gpointer _data)
{
	OllMchatOllamaPsCallExecModelsData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->result);
	_g_object_unref0 (_data_->self);
	g_slice_free (OllMchatOllamaPsCallExecModelsData, _data_);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
oll_mchat_ollama_ps_call_exec_models (OLLMchatOllamaPsCall* self,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_)
{
	OllMchatOllamaPsCallExecModelsData* _data_;
	OLLMchatOllamaPsCall* _tmp0_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (OllMchatOllamaPsCallExecModelsData);
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, oll_mchat_ollama_ps_call_exec_models_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	oll_mchat_ollama_ps_call_exec_models_co (_data_);
}

GeeArrayList*
oll_mchat_ollama_ps_call_exec_models_finish (OLLMchatOllamaPsCall* self,
                                             GAsyncResult* _res_,
                                             GError** error)
{
	GeeArrayList* result;
	OllMchatOllamaPsCallExecModelsData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), error);
	if (NULL == _data_) {
		return NULL;
	}
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
oll_mchat_ollama_ps_call_exec_models_ready (GObject* source_object,
                                            GAsyncResult* _res_,
                                            gpointer _user_data_)
{
	OllMchatOllamaPsCallExecModelsData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	oll_mchat_ollama_ps_call_exec_models_co (_data_);
}

static gboolean
oll_mchat_ollama_ps_call_exec_models_co (OllMchatOllamaPsCallExecModelsData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_state_ = 1;
	oll_mchat_ollama_base_call_get_models ((OLLMchatOllamaBaseCall*) _data_->self, "models", oll_mchat_ollama_ps_call_exec_models_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp1_ = oll_mchat_ollama_base_call_get_models_finish ((OLLMchatOllamaBaseCall*) _data_->self, _data_->_res_, &_data_->_inner_error0_);
	_data_->_tmp0_ = _data_->_tmp1_;
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp2_ = _data_->_tmp0_;
	_data_->_tmp0_ = NULL;
	_data_->result = _data_->_tmp2_;
	_g_object_unref0 (_data_->_tmp0_);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
oll_mchat_ollama_ps_call_class_init (OLLMchatOllamaPsCallClass * klass,
                                     gpointer klass_data)
{
	oll_mchat_ollama_ps_call_parent_class = g_type_class_peek_parent (klass);
}

static void
oll_mchat_ollama_ps_call_instance_init (OLLMchatOllamaPsCall * self,
                                        gpointer klass)
{
}

 G_GNUC_NO_INLINE static GType
oll_mchat_ollama_ps_call_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (OLLMchatOllamaPsCallClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mchat_ollama_ps_call_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OLLMchatOllamaPsCall), 0, (GInstanceInitFunc) oll_mchat_ollama_ps_call_instance_init, NULL };
	GType oll_mchat_ollama_ps_call_type_id;
	oll_mchat_ollama_ps_call_type_id = g_type_register_static (OLL_MCHAT_OLLAMA_TYPE_BASE_CALL, "OLLMchatOllamaPsCall", &g_define_type_info, 0);
	return oll_mchat_ollama_ps_call_type_id;
}

GType
oll_mchat_ollama_ps_call_get_type (void)
{
	static gsize oll_mchat_ollama_ps_call_type_id__once = 0;
	if (g_once_init_enter (&oll_mchat_ollama_ps_call_type_id__once)) {
		GType oll_mchat_ollama_ps_call_type_id;
		oll_mchat_ollama_ps_call_type_id = oll_mchat_ollama_ps_call_get_type_once ();
		g_once_init_leave (&oll_mchat_ollama_ps_call_type_id__once, oll_mchat_ollama_ps_call_type_id);
	}
	return oll_mchat_ollama_ps_call_type_id__once;
}

