/* PlainFile.vala.c generated by valac, the Vala compiler
 * generated from PlainFile.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <glib/gstdio.h>
#include <gio/gio.h>


#define JS_RENDER_TYPE_JS_RENDER (js_render_js_render_get_type ())
#define JS_RENDER_JS_RENDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRender))
#define JS_RENDER_JS_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRenderClass))
#define JS_RENDER_IS_JS_RENDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_JS_RENDER))
#define JS_RENDER_IS_JS_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_JS_RENDER))
#define JS_RENDER_JS_RENDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRenderClass))

typedef struct _JsRenderJsRender JsRenderJsRender;
typedef struct _JsRenderJsRenderClass JsRenderJsRenderClass;
typedef struct _JsRenderJsRenderPrivate JsRenderJsRenderPrivate;

#define JS_RENDER_TYPE_NODE (js_render_node_get_type ())
#define JS_RENDER_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_NODE, JsRenderNode))
#define JS_RENDER_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_NODE, JsRenderNodeClass))
#define JS_RENDER_IS_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_NODE))
#define JS_RENDER_IS_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_NODE))
#define JS_RENDER_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_NODE, JsRenderNodeClass))

typedef struct _JsRenderNode JsRenderNode;
typedef struct _JsRenderNodeClass JsRenderNodeClass;

#define PROJECT_TYPE_PROJECT (project_project_get_type ())
#define PROJECT_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROJECT_TYPE_PROJECT, ProjectProject))
#define PROJECT_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROJECT_TYPE_PROJECT, ProjectProjectClass))
#define PROJECT_IS_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROJECT_TYPE_PROJECT))
#define PROJECT_IS_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROJECT_TYPE_PROJECT))
#define PROJECT_PROJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROJECT_TYPE_PROJECT, ProjectProjectClass))

typedef struct _ProjectProject ProjectProject;
typedef struct _ProjectProjectClass ProjectProjectClass;

#define JS_RENDER_TYPE_PLAIN_FILE (js_render_plain_file_get_type ())
#define JS_RENDER_PLAIN_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_PLAIN_FILE, JsRenderPlainFile))
#define JS_RENDER_PLAIN_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_PLAIN_FILE, JsRenderPlainFileClass))
#define JS_RENDER_IS_PLAIN_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_PLAIN_FILE))
#define JS_RENDER_IS_PLAIN_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_PLAIN_FILE))
#define JS_RENDER_PLAIN_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_PLAIN_FILE, JsRenderPlainFileClass))

typedef struct _JsRenderPlainFile JsRenderPlainFile;
typedef struct _JsRenderPlainFileClass JsRenderPlainFileClass;
typedef struct _JsRenderPlainFilePrivate JsRenderPlainFilePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _JsRenderJsRender {
	GObject parent_instance;
	JsRenderJsRenderPrivate * priv;
	GeeArrayList* doubleStringProps;
	gchar* id;
	gchar* name;
	gchar* fullname;
	gchar* path;
	gchar* parent;
	gchar* region;
	gchar* title;
	gchar* build_module;
	gchar* permname;
	gchar* language;
	gchar* content_type;
	gchar* modOrder;
	gchar* xtype;
	guint64 webkit_page_id;
	ProjectProject* project;
	JsRenderNode* tree;
	GList* cn;
	gboolean hasParent;
	gboolean loaded;
	GeeHashMap* transStrings;
};

struct _JsRenderJsRenderClass {
	GObjectClass parent_class;
	void (*loadItems) (JsRenderJsRender* self, GError** error);
	void (*save) (JsRenderJsRender* self);
	void (*saveHTML) (JsRenderJsRender* self, const gchar* html);
	gchar* (*toSource) (JsRenderJsRender* self);
	gchar* (*toSourceCode) (JsRenderJsRender* self);
	void (*setSource) (JsRenderJsRender* self, const gchar* str);
	gchar* (*toSourcePreview) (JsRenderJsRender* self);
	void (*removeFiles) (JsRenderJsRender* self);
	void (*findTransStrings) (JsRenderJsRender* self, JsRenderNode* node);
};

struct _JsRenderPlainFile {
	JsRenderJsRender parent_instance;
	JsRenderPlainFilePrivate * priv;
};

struct _JsRenderPlainFileClass {
	JsRenderJsRenderClass parent_class;
};

struct _JsRenderPlainFilePrivate {
	gchar* contents;
};


extern gint js_render_plid;
gint js_render_plid = 1;
static gpointer js_render_plain_file_parent_class = NULL;

GType js_render_js_render_get_type (void) G_GNUC_CONST;
GType js_render_node_get_type (void) G_GNUC_CONST;
GType project_project_get_type (void) G_GNUC_CONST;
GType js_render_plain_file_get_type (void) G_GNUC_CONST;
#define JS_RENDER_PLAIN_FILE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JS_RENDER_TYPE_PLAIN_FILE, JsRenderPlainFilePrivate))
enum  {
	JS_RENDER_PLAIN_FILE_DUMMY_PROPERTY
};
JsRenderPlainFile* js_render_plain_file_new (ProjectProject* project, const gchar* path);
JsRenderPlainFile* js_render_plain_file_construct (GType object_type, ProjectProject* project, const gchar* path);
JsRenderJsRender* js_render_js_render_construct (GType object_type, ProjectProject* project, const gchar* path);
static void js_render_plain_file_real_removeFiles (JsRenderJsRender* base);
static void js_render_plain_file_real_loadItems (JsRenderJsRender* base, GError** error);
static gchar* js_render_plain_file_real_toSourcePreview (JsRenderJsRender* base);
static void js_render_plain_file_real_setSource (JsRenderJsRender* base, const gchar* str);
static gchar* js_render_plain_file_real_toSource (JsRenderJsRender* base);
static gchar* js_render_plain_file_real_toSourceCode (JsRenderJsRender* base);
static void js_render_plain_file_real_save (JsRenderJsRender* base);
void js_render_js_render_writeFile (JsRenderJsRender* self, const gchar* path, const gchar* contents, GError** error);
static void js_render_plain_file_real_saveHTML (JsRenderJsRender* base, const gchar* html);
static gchar* js_render_plain_file_getHelpUrl (JsRenderPlainFile* self, const gchar* cls);
static void js_render_plain_file_real_findTransStrings (JsRenderJsRender* base, JsRenderNode* node);
static void js_render_plain_file_finalize (GObject* obj);


JsRenderPlainFile* js_render_plain_file_construct (GType object_type, ProjectProject* project, const gchar* path) {
	JsRenderPlainFile * self = NULL;
	ProjectProject* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gint _tmp17_ = 0;
	gchar* _tmp18_ = NULL;
	GError * _inner_error_ = NULL;
#line 24 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp0_ = project;
#line 24 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp1_ = path;
#line 24 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = (JsRenderPlainFile*) js_render_js_render_construct (object_type, _tmp0_, _tmp1_);
#line 25 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp2_ = g_strdup ("PlainFile");
#line 25 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_g_free0 (((JsRenderJsRender*) self)->xtype);
#line 25 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRender*) self)->xtype = _tmp2_;
#line 28 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp3_ = path;
#line 28 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp4_ = g_file_test (_tmp3_, G_FILE_TEST_EXISTS);
#line 28 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	if (_tmp4_) {
#line 172 "PlainFile.vala.c"
		GFile* f = NULL;
		const gchar* _tmp5_ = NULL;
		GFile* _tmp6_ = NULL;
		GFileInfo* info = NULL;
		GFile* _tmp7_ = NULL;
		GFileInfo* _tmp8_ = NULL;
		gchar* ct = NULL;
		GFileInfo* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		const gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
#line 29 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp5_ = path;
#line 29 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp6_ = g_file_new_for_path (_tmp5_);
#line 29 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		f = _tmp6_;
#line 30 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp7_ = f;
#line 30 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp8_ = g_file_query_info (_tmp7_, "standard::*", 0, NULL, &_inner_error_);
#line 30 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		info = _tmp8_;
#line 30 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 30 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
			_g_object_unref0 (f);
#line 30 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 30 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
			g_clear_error (&_inner_error_);
#line 30 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
			return NULL;
#line 207 "PlainFile.vala.c"
		}
#line 31 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp9_ = info;
#line 31 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp10_ = g_file_info_get_content_type (_tmp9_);
#line 31 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp11_ = g_strdup (_tmp10_);
#line 31 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		ct = _tmp11_;
#line 32 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp12_ = ct;
#line 32 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp13_ = g_strdup (_tmp12_);
#line 32 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_g_free0 (((JsRenderJsRender*) self)->content_type);
#line 32 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		((JsRenderJsRender*) self)->content_type = _tmp13_;
#line 28 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_g_free0 (ct);
#line 28 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_g_object_unref0 (info);
#line 28 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_g_object_unref0 (f);
#line 231 "PlainFile.vala.c"
	} else {
		gchar* _tmp14_ = NULL;
#line 34 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp14_ = g_strdup ("text/plain");
#line 34 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_g_free0 (((JsRenderJsRender*) self)->content_type);
#line 34 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		((JsRenderJsRender*) self)->content_type = _tmp14_;
#line 40 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		((JsRenderJsRender*) self)->loaded = TRUE;
#line 242 "PlainFile.vala.c"
	}
#line 45 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp15_ = g_strdup ("");
#line 45 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_g_free0 (((JsRenderJsRender*) self)->language);
#line 45 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRender*) self)->language = _tmp15_;
#line 50 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp16_ = g_strdup ("");
#line 50 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_g_free0 (self->priv->contents);
#line 50 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self->priv->contents = _tmp16_;
#line 53 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp17_ = js_render_plid;
#line 53 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	js_render_plid = _tmp17_ + 1;
#line 53 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp18_ = g_strdup_printf ("file-plain-%d", _tmp17_);
#line 53 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_g_free0 (((JsRenderJsRender*) self)->id);
#line 53 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRender*) self)->id = _tmp18_;
#line 22 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	return self;
#line 268 "PlainFile.vala.c"
}


JsRenderPlainFile* js_render_plain_file_new (ProjectProject* project, const gchar* path) {
#line 22 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	return js_render_plain_file_construct (JS_RENDER_TYPE_PLAIN_FILE, project, path);
#line 275 "PlainFile.vala.c"
}


static void js_render_plain_file_real_removeFiles (JsRenderJsRender* base) {
	JsRenderPlainFile * self;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 78 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = (JsRenderPlainFile*) base;
#line 79 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp0_ = ((JsRenderJsRender*) self)->path;
#line 79 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp1_ = g_file_test (_tmp0_, G_FILE_TEST_EXISTS);
#line 79 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	if (_tmp1_) {
#line 291 "PlainFile.vala.c"
		const gchar* _tmp2_ = NULL;
#line 80 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp2_ = ((JsRenderJsRender*) self)->path;
#line 80 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		g_remove (_tmp2_);
#line 297 "PlainFile.vala.c"
	}
}


static void js_render_plain_file_real_loadItems (JsRenderJsRender* base, GError** error) {
	JsRenderPlainFile * self;
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
#line 85 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = (JsRenderPlainFile*) base;
#line 87 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp0_ = ((JsRenderJsRender*) self)->loaded;
#line 87 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	if (_tmp0_) {
#line 88 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		return;
#line 316 "PlainFile.vala.c"
	}
#line 90 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp1_ = ((JsRenderJsRender*) self)->path;
#line 90 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	g_file_get_contents (_tmp1_, &_tmp2_, NULL, &_inner_error_);
#line 90 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_g_free0 (self->priv->contents);
#line 90 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self->priv->contents = _tmp2_;
#line 90 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 90 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		g_propagate_error (error, _inner_error_);
#line 90 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		return;
#line 332 "PlainFile.vala.c"
	}
#line 91 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRender*) self)->loaded = TRUE;
#line 336 "PlainFile.vala.c"
}


static gchar* js_render_plain_file_real_toSourcePreview (JsRenderJsRender* base) {
	JsRenderPlainFile * self;
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
#line 96 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = (JsRenderPlainFile*) base;
#line 98 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp0_ = g_strdup ("");
#line 98 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	result = _tmp0_;
#line 98 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	return result;
#line 352 "PlainFile.vala.c"
}


static void js_render_plain_file_real_setSource (JsRenderJsRender* base, const gchar* str) {
	JsRenderPlainFile * self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 100 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = (JsRenderPlainFile*) base;
#line 101 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp0_ = str;
#line 101 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 101 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_g_free0 (self->priv->contents);
#line 101 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self->priv->contents = _tmp1_;
#line 370 "PlainFile.vala.c"
}


static gchar* js_render_plain_file_real_toSource (JsRenderJsRender* base) {
	JsRenderPlainFile * self;
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 103 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = (JsRenderPlainFile*) base;
#line 105 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp0_ = self->priv->contents;
#line 105 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 105 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	result = _tmp1_;
#line 105 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	return result;
#line 389 "PlainFile.vala.c"
}


static gchar* js_render_plain_file_real_toSourceCode (JsRenderJsRender* base) {
	JsRenderPlainFile * self;
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 110 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = (JsRenderPlainFile*) base;
#line 112 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp0_ = self->priv->contents;
#line 112 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 112 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	result = _tmp1_;
#line 112 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	return result;
#line 408 "PlainFile.vala.c"
}


static void js_render_plain_file_real_save (JsRenderJsRender* base) {
	JsRenderPlainFile * self;
	gboolean _tmp0_ = FALSE;
	GError * _inner_error_ = NULL;
#line 117 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = (JsRenderPlainFile*) base;
#line 118 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp0_ = ((JsRenderJsRender*) self)->loaded;
#line 118 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	if (!_tmp0_) {
#line 119 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		g_print ("Ignoring Save  - as file was never loaded?\n");
#line 120 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		return;
#line 426 "PlainFile.vala.c"
	}
	{
		const gchar* _tmp1_ = NULL;
		const gchar* _tmp2_ = NULL;
#line 123 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp1_ = ((JsRenderJsRender*) self)->path;
#line 123 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_tmp2_ = self->priv->contents;
#line 123 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		js_render_js_render_writeFile ((JsRenderJsRender*) self, _tmp1_, _tmp2_, &_inner_error_);
#line 123 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 439 "PlainFile.vala.c"
			goto __catch62_g_error;
		}
	}
	goto __finally62;
	__catch62_g_error:
	{
		GError* e = NULL;
#line 122 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		e = _inner_error_;
#line 122 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_inner_error_ = NULL;
#line 122 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		_g_error_free0 (e);
#line 453 "PlainFile.vala.c"
	}
	__finally62:
#line 122 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 122 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 122 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		g_clear_error (&_inner_error_);
#line 122 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
		return;
#line 464 "PlainFile.vala.c"
	}
}


static void js_render_plain_file_real_saveHTML (JsRenderJsRender* base, const gchar* html) {
	JsRenderPlainFile * self;
#line 130 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = (JsRenderPlainFile*) base;
#line 473 "PlainFile.vala.c"
}


/** 
         *  saveJS
         * 
         * save as a javascript file.
         * why is this not save...???
         * 
         */
static gchar* js_render_plain_file_getHelpUrl (JsRenderPlainFile* self, const gchar* cls) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
#line 144 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_tmp0_ = g_strdup ("");
#line 144 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	result = _tmp0_;
#line 144 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	return result;
#line 493 "PlainFile.vala.c"
}


static void js_render_plain_file_real_findTransStrings (JsRenderJsRender* base, JsRenderNode* node) {
	JsRenderPlainFile * self;
#line 146 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = (JsRenderPlainFile*) base;
#line 501 "PlainFile.vala.c"
}


static void js_render_plain_file_class_init (JsRenderPlainFileClass * klass) {
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	js_render_plain_file_parent_class = g_type_class_peek_parent (klass);
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	g_type_class_add_private (klass, sizeof (JsRenderPlainFilePrivate));
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRenderClass *) klass)->removeFiles = js_render_plain_file_real_removeFiles;
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRenderClass *) klass)->loadItems = js_render_plain_file_real_loadItems;
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRenderClass *) klass)->toSourcePreview = js_render_plain_file_real_toSourcePreview;
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRenderClass *) klass)->setSource = js_render_plain_file_real_setSource;
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRenderClass *) klass)->toSource = js_render_plain_file_real_toSource;
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRenderClass *) klass)->toSourceCode = js_render_plain_file_real_toSourceCode;
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRenderClass *) klass)->save = js_render_plain_file_real_save;
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRenderClass *) klass)->saveHTML = js_render_plain_file_real_saveHTML;
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	((JsRenderJsRenderClass *) klass)->findTransStrings = js_render_plain_file_real_findTransStrings;
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	G_OBJECT_CLASS (klass)->finalize = js_render_plain_file_finalize;
#line 530 "PlainFile.vala.c"
}


static void js_render_plain_file_instance_init (JsRenderPlainFile * self) {
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self->priv = JS_RENDER_PLAIN_FILE_GET_PRIVATE (self);
#line 537 "PlainFile.vala.c"
}


static void js_render_plain_file_finalize (GObject* obj) {
	JsRenderPlainFile * self;
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, JS_RENDER_TYPE_PLAIN_FILE, JsRenderPlainFile);
#line 20 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	_g_free0 (self->priv->contents);
#line 18 "/home/alan/gitlive/roobuilder/src/JsRender/PlainFile.vala"
	G_OBJECT_CLASS (js_render_plain_file_parent_class)->finalize (obj);
#line 549 "PlainFile.vala.c"
}


GType js_render_plain_file_get_type (void) {
	static volatile gsize js_render_plain_file_type_id__volatile = 0;
	if (g_once_init_enter (&js_render_plain_file_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JsRenderPlainFileClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) js_render_plain_file_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JsRenderPlainFile), 0, (GInstanceInitFunc) js_render_plain_file_instance_init, NULL };
		GType js_render_plain_file_type_id;
		js_render_plain_file_type_id = g_type_register_static (JS_RENDER_TYPE_JS_RENDER, "JsRenderPlainFile", &g_define_type_info, 0);
		g_once_init_leave (&js_render_plain_file_type_id__volatile, js_render_plain_file_type_id);
	}
	return js_render_plain_file_type_id__volatile;
}



