/* Gir.vala.c generated by valac, the Vala compiler
 * generated from Gir.vala, do not modify */

/* valac -g  --pkg gee-1.0 --pkg libxml-2.0 --pkg gobject-introspection-1.0 --pkg json-glib-1.0  Palete/Gir.vala -o /tmp/Gir*/
/* 
public static int main (string[] args) {
    
    var g = Palete.Gir.factory("Gtk");
var test = g.classes.get("ToolButton");


    var generator = new Json.Generator ();
    var n = new Json.Node(Json.NodeType.OBJECT);
    n.set_object(test.toJSON());
    generator.set_root(n);
    generator.indent = 4;
    generator.pretty = true;
    
    print(generator.to_data(null));
    return 0;
}
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <json-glib/json-glib.h>
#include <vala.h>


#define PALETE_TYPE_GIR_OBJECT (palete_gir_object_get_type ())
#define PALETE_GIR_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_GIR_OBJECT, PaleteGirObject))
#define PALETE_GIR_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_GIR_OBJECT, PaleteGirObjectClass))
#define PALETE_IS_GIR_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_GIR_OBJECT))
#define PALETE_IS_GIR_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_GIR_OBJECT))
#define PALETE_GIR_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_GIR_OBJECT, PaleteGirObjectClass))

typedef struct _PaleteGirObject PaleteGirObject;
typedef struct _PaleteGirObjectClass PaleteGirObjectClass;
typedef struct _PaleteGirObjectPrivate PaleteGirObjectPrivate;

#define PALETE_TYPE_GIR (palete_gir_get_type ())
#define PALETE_GIR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_GIR, PaleteGir))
#define PALETE_GIR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_GIR, PaleteGirClass))
#define PALETE_IS_GIR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_GIR))
#define PALETE_IS_GIR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_GIR))
#define PALETE_GIR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_GIR, PaleteGirClass))

typedef struct _PaleteGir PaleteGir;
typedef struct _PaleteGirClass PaleteGirClass;
typedef struct _PaleteGirPrivate PaleteGirPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block20Data Block20Data;
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))

#define PROJECT_TYPE_PROJECT (project_project_get_type ())
#define PROJECT_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROJECT_TYPE_PROJECT, ProjectProject))
#define PROJECT_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROJECT_TYPE_PROJECT, ProjectProjectClass))
#define PROJECT_IS_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROJECT_TYPE_PROJECT))
#define PROJECT_IS_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROJECT_TYPE_PROJECT))
#define PROJECT_PROJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROJECT_TYPE_PROJECT, ProjectProjectClass))

typedef struct _ProjectProject ProjectProject;
typedef struct _ProjectProjectClass ProjectProjectClass;

#define PROJECT_TYPE_GTK (project_gtk_get_type ())
#define PROJECT_GTK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROJECT_TYPE_GTK, ProjectGtk))
#define PROJECT_GTK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROJECT_TYPE_GTK, ProjectGtkClass))
#define PROJECT_IS_GTK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROJECT_TYPE_GTK))
#define PROJECT_IS_GTK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROJECT_TYPE_GTK))
#define PROJECT_GTK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROJECT_TYPE_GTK, ProjectGtkClass))

typedef struct _ProjectGtk ProjectGtk;
typedef struct _ProjectGtkClass ProjectGtkClass;
typedef struct _ProjectProjectPrivate ProjectProjectPrivate;

#define JS_RENDER_TYPE_JS_RENDER (js_render_js_render_get_type ())
#define JS_RENDER_JS_RENDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRender))
#define JS_RENDER_JS_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRenderClass))
#define JS_RENDER_IS_JS_RENDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JS_RENDER_TYPE_JS_RENDER))
#define JS_RENDER_IS_JS_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JS_RENDER_TYPE_JS_RENDER))
#define JS_RENDER_JS_RENDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JS_RENDER_TYPE_JS_RENDER, JsRenderJsRenderClass))

typedef struct _JsRenderJsRender JsRenderJsRender;
typedef struct _JsRenderJsRenderClass JsRenderJsRenderClass;

#define PALETE_TYPE_ROO_DATABASE (palete_roo_database_get_type ())
#define PALETE_ROO_DATABASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_ROO_DATABASE, PaleteRooDatabase))
#define PALETE_ROO_DATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_ROO_DATABASE, PaleteRooDatabaseClass))
#define PALETE_IS_ROO_DATABASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_ROO_DATABASE))
#define PALETE_IS_ROO_DATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_ROO_DATABASE))
#define PALETE_ROO_DATABASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_ROO_DATABASE, PaleteRooDatabaseClass))

typedef struct _PaleteRooDatabase PaleteRooDatabase;
typedef struct _PaleteRooDatabaseClass PaleteRooDatabaseClass;

#define PALETE_TYPE_PALETE (palete_palete_get_type ())
#define PALETE_PALETE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_PALETE, PaletePalete))
#define PALETE_PALETE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_PALETE, PaletePaleteClass))
#define PALETE_IS_PALETE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_PALETE))
#define PALETE_IS_PALETE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_PALETE))
#define PALETE_PALETE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_PALETE, PaletePaleteClass))

typedef struct _PaletePalete PaletePalete;
typedef struct _PaletePaleteClass PaletePaleteClass;
typedef struct _ProjectGtkPrivate ProjectGtkPrivate;

#define PROJECT_TYPE_GTK_VALA_SETTINGS (project_gtk_vala_settings_get_type ())
#define PROJECT_GTK_VALA_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROJECT_TYPE_GTK_VALA_SETTINGS, ProjectGtkValaSettings))
#define PROJECT_GTK_VALA_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROJECT_TYPE_GTK_VALA_SETTINGS, ProjectGtkValaSettingsClass))
#define PROJECT_IS_GTK_VALA_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROJECT_TYPE_GTK_VALA_SETTINGS))
#define PROJECT_IS_GTK_VALA_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROJECT_TYPE_GTK_VALA_SETTINGS))
#define PROJECT_GTK_VALA_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROJECT_TYPE_GTK_VALA_SETTINGS, ProjectGtkValaSettingsClass))

typedef struct _ProjectGtkValaSettings ProjectGtkValaSettings;
typedef struct _ProjectGtkValaSettingsClass ProjectGtkValaSettingsClass;

#define PALETE_TYPE_VAPI_PARSER (palete_vapi_parser_get_type ())
#define PALETE_VAPI_PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_VAPI_PARSER, PaleteVapiParser))
#define PALETE_VAPI_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_VAPI_PARSER, PaleteVapiParserClass))
#define PALETE_IS_VAPI_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_VAPI_PARSER))
#define PALETE_IS_VAPI_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_VAPI_PARSER))
#define PALETE_VAPI_PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_VAPI_PARSER, PaleteVapiParserClass))

typedef struct _PaleteVapiParser PaleteVapiParser;
typedef struct _PaleteVapiParserClass PaleteVapiParserClass;
#define _vala_code_visitor_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_visitor_unref (var), NULL)))

struct _PaleteGirObject {
	GObject parent_instance;
	PaleteGirObjectPrivate * priv;
	gchar* name;
	gchar* ns;
	gchar* propertyof;
	gchar* type;
	gchar* nodetype;
	gchar* package;
	gchar* direction;
	PaleteGirObject* paramset;
	PaleteGirObject* return_value;
	gboolean is_instance;
	gboolean is_array;
	gboolean is_varargs;
	gboolean ctor_only;
	gchar* parent;
	gchar* value;
	gchar* sig;
	gboolean is_overlaid;
	PaleteGirObject* gparent;
	GeeArrayList* params;
	GeeArrayList* implements;
	GeeArrayList* inherits;
	GeeHashMap* ctors;
	GeeHashMap* methods;
	GeeHashMap* includes;
	GeeHashMap* classes;
	GeeHashMap* props;
	GeeHashMap* consts;
	GeeHashMap* signals;
	GeeArrayList* optvalues;
	gchar* doctxt;
};

struct _PaleteGirObjectClass {
	GObjectClass parent_class;
};

struct _PaleteGir {
	PaleteGirObject parent_instance;
	PaleteGirPrivate * priv;
};

struct _PaleteGirClass {
	PaleteGirObjectClass parent_class;
};

struct _Block20Data {
	int _ref_count_;
	JsonObject* obj;
};

typedef enum  {
	PALETE_GIR_ERROR_INVALID_TYPE,
	PALETE_GIR_ERROR_NEED_IMPLEMENTING,
	PALETE_GIR_ERROR_MISSING_FILE,
	PALETE_GIR_ERROR_INVALID_VALUE,
	PALETE_GIR_ERROR_INVALID_FORMAT
} PaleteGirError;
#define PALETE_GIR_ERROR palete_gir_error_quark ()
struct _ProjectProject {
	GObject parent_instance;
	ProjectProjectPrivate * priv;
	gchar* id;
	gchar* fn;
	gchar* name;
	gchar* runhtml;
	gchar* base_template;
	gchar* rootURL;
	GeeHashMap* paths;
	GeeHashMap* files;
	gchar* xtype;
	JsonObject* json_project_data;
	PaleteRooDatabase* roo_database;
	PaletePalete* palete;
};

struct _ProjectProjectClass {
	GObjectClass parent_class;
};

struct _ProjectGtk {
	ProjectProject parent_instance;
	ProjectGtkPrivate * priv;
	GeeHashMap* gir_cache;
	gboolean gir_cache_loaded;
	GeeHashMap* compilegroups;
};

struct _ProjectGtkClass {
	ProjectProjectClass parent_class;
};


static gpointer palete_gir_parent_class = NULL;
extern gboolean palete_gir_overrides_loaded;
gboolean palete_gir_overrides_loaded = FALSE;
extern GeeHashMap* palete_gir_overrides;
GeeHashMap* palete_gir_overrides = NULL;
extern GeeHashMap* palete_gir_global_cache;
GeeHashMap* palete_gir_global_cache = NULL;

GType palete_gir_object_get_type (void) G_GNUC_CONST;
GType palete_gir_get_type (void) G_GNUC_CONST;
enum  {
	PALETE_GIR_DUMMY_PROPERTY
};
PaleteGir* palete_gir_new (const gchar* ns);
PaleteGir* palete_gir_construct (GType object_type, const gchar* ns);
PaleteGirObject* palete_gir_object_new (const gchar* nodetype, const gchar* n);
PaleteGirObject* palete_gir_object_construct (GType object_type, const gchar* nodetype, const gchar* n);
gchar* palete_gir_doc (PaleteGir* self, const gchar* what);
void palete_gir_checkParamOverride (PaleteGirObject* c);
gchar* palete_gir_fetchOverride (const gchar* cls, const gchar* method, const gchar* param);
void palete_gir_loadOverrides (gboolean force);
static Block20Data* block20_data_ref (Block20Data* _data20_);
static void block20_data_unref (void * _userdata_);
gchar* builder_application_configDirectory (void);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
GQuark palete_gir_error_quark (void);
static void _vala_JsonNode_free (JsonNode* self);
static void __lambda11_ (Block20Data* _data20_, JsonObject* o, const gchar* key, JsonNode* value);
static void ___lambda11__json_object_foreach (JsonObject* object, const gchar* member_name, JsonNode* member_node, gpointer self);
GType project_project_get_type (void) G_GNUC_CONST;
PaleteGir* palete_gir_factory (ProjectProject* project, const gchar* ns);
GType project_gtk_get_type (void) G_GNUC_CONST;
GType js_render_js_render_get_type (void) G_GNUC_CONST;
GType palete_roo_database_get_type (void) G_GNUC_CONST;
GType palete_palete_get_type (void) G_GNUC_CONST;
GType project_gtk_vala_settings_get_type (void) G_GNUC_CONST;
GType palete_vapi_parser_get_type (void) G_GNUC_CONST;
PaleteVapiParser* palete_vapi_parser_new (ProjectGtk* project);
PaleteVapiParser* palete_vapi_parser_construct (GType object_type, ProjectGtk* project);
void palete_vapi_parser_create_valac_tree (PaleteVapiParser* self);
void palete_gir_object_overlayParent (PaleteGirObject* self, ProjectProject* project);
void palete_gir_object_overlayCtorProperties (PaleteGirObject* self);
PaleteGirObject* palete_gir_factoryFqn (ProjectProject* project, const gchar* fqn);
PaleteGirObject* palete_gir_object_fetchByFqn (PaleteGirObject* self, const gchar* fqn);
gchar* palete_gir_fqtypeLookup (ProjectProject* project, const gchar* type, const gchar* ns);
gchar* palete_gir_guessDefaultValueForType (const gchar* type);
static void palete_gir_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


PaleteGir* palete_gir_construct (GType object_type, const gchar* ns) {
	PaleteGir * self = NULL;
	const gchar* _tmp0_ = NULL;
#line 35 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp0_ = ns;
#line 35 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	self = (PaleteGir*) palete_gir_object_construct (object_type, "Package", _tmp0_);
#line 33 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return self;
#line 290 "Gir.vala.c"
}


PaleteGir* palete_gir_new (const gchar* ns) {
#line 33 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return palete_gir_construct (PALETE_TYPE_GIR, ns);
#line 297 "Gir.vala.c"
}


gchar* palete_gir_doc (PaleteGir* self, const gchar* what) {
	gchar* result = NULL;
	gchar** ar = NULL;
	const gchar* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint ar_length1 = 0;
	gint _ar_size_ = 0;
	PaleteGirObject* cls = NULL;
	GeeHashMap* _tmp3_ = NULL;
	gchar** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	const gchar* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
	PaleteGirObject* pr = NULL;
	PaleteGirObject* _tmp14_ = NULL;
	GeeHashMap* _tmp15_ = NULL;
	gchar** _tmp16_ = NULL;
	gint _tmp16__length1 = 0;
	const gchar* _tmp17_ = NULL;
	gpointer _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	PaleteGirObject* _tmp20_ = NULL;
	const gchar* _tmp21_ = NULL;
	gchar* _tmp24_ = NULL;
#line 41 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp0_ = what;
#line 41 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp2_ = _tmp1_ = g_strsplit (_tmp0_, ".", 0);
#line 41 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	ar = _tmp2_;
#line 41 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	ar_length1 = _vala_array_length (_tmp1_);
#line 41 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_ar_size_ = ar_length1;
#line 42 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp3_ = ((PaleteGirObject*) self)->classes;
#line 42 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp4_ = ar;
#line 42 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp4__length1 = ar_length1;
#line 42 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp5_ = _tmp4_[1];
#line 42 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp6_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp3_, _tmp5_);
#line 42 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	cls = (PaleteGirObject*) _tmp6_;
#line 43 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp7_ = ar;
#line 43 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp7__length1 = ar_length1;
#line 43 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp7__length1 == 2) {
#line 356 "Gir.vala.c"
		const gchar* _tmp8_ = NULL;
		PaleteGirObject* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		gchar* _tmp13_ = NULL;
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp9_ = cls;
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp10_ = _tmp9_->doctxt;
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		if (_tmp10_ != NULL) {
#line 367 "Gir.vala.c"
			PaleteGirObject* _tmp11_ = NULL;
			const gchar* _tmp12_ = NULL;
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp11_ = cls;
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp12_ = _tmp11_->doctxt;
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp8_ = _tmp12_;
#line 376 "Gir.vala.c"
		} else {
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp8_ = "";
#line 380 "Gir.vala.c"
		}
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp13_ = g_strdup (_tmp8_);
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		result = _tmp13_;
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (cls);
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		ar = (_vala_array_free (ar, ar_length1, (GDestroyNotify) g_free), NULL);
#line 44 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return result;
#line 392 "Gir.vala.c"
	}
#line 47 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp14_ = cls;
#line 47 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp15_ = _tmp14_->props;
#line 47 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp16_ = ar;
#line 47 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp16__length1 = ar_length1;
#line 47 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp17_ = _tmp16_[2];
#line 47 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp18_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp15_, _tmp17_);
#line 47 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	pr = (PaleteGirObject*) _tmp18_;
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp20_ = pr;
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp21_ = _tmp20_->doctxt;
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp21_ != NULL) {
#line 414 "Gir.vala.c"
		PaleteGirObject* _tmp22_ = NULL;
		const gchar* _tmp23_ = NULL;
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp22_ = pr;
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp23_ = _tmp22_->doctxt;
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp19_ = _tmp23_;
#line 423 "Gir.vala.c"
	} else {
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp19_ = "";
#line 427 "Gir.vala.c"
	}
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp24_ = g_strdup (_tmp19_);
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	result = _tmp24_;
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (pr);
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (cls);
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	ar = (_vala_array_free (ar, ar_length1, (GDestroyNotify) g_free), NULL);
#line 48 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return result;
#line 441 "Gir.vala.c"
}


/**
 * since constructors from the API from gir or vala do not map
 * correctly to properties, we have an Gir.overides file in resources
 * that changes the ctor's for some elements.
 * 
 */
static gpointer _g_object_ref0 (gpointer self) {
#line 62 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return self ? g_object_ref (self) : NULL;
#line 454 "Gir.vala.c"
}


void palete_gir_checkParamOverride (PaleteGirObject* c) {
	PaleteGirObject* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	PaleteGirObject* parset = NULL;
	PaleteGirObject* _tmp2_ = NULL;
	PaleteGirObject* _tmp3_ = NULL;
	PaleteGirObject* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	PaleteGirObject* _tmp6_ = NULL;
	PaleteGirObject* method = NULL;
	PaleteGirObject* _tmp9_ = NULL;
	PaleteGirObject* _tmp10_ = NULL;
	PaleteGirObject* _tmp11_ = NULL;
	PaleteGirObject* _tmp12_ = NULL;
	PaleteGirObject* cls = NULL;
	PaleteGirObject* _tmp13_ = NULL;
	PaleteGirObject* _tmp14_ = NULL;
	PaleteGirObject* _tmp15_ = NULL;
	gboolean _tmp16_ = FALSE;
	PaleteGirObject* _tmp17_ = NULL;
	PaleteGirObject* _tmp20_ = NULL;
	PaleteGirObject* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	PaleteGirObject* _tmp23_ = NULL;
	const gchar* _tmp24_ = NULL;
	PaleteGirObject* _tmp25_ = NULL;
	const gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
#line 61 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp0_ = c;
#line 61 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp1_ = _tmp0_->name;
#line 61 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	g_print ("checkParamOverride :check %s\n", _tmp1_);
#line 62 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp2_ = c;
#line 62 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp3_ = _tmp2_->gparent;
#line 62 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 62 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	parset = _tmp4_;
#line 63 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp6_ = parset;
#line 63 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp6_ == NULL) {
#line 63 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp5_ = TRUE;
#line 506 "Gir.vala.c"
	} else {
		PaleteGirObject* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
#line 63 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp7_ = parset;
#line 63 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp8_ = _tmp7_->nodetype;
#line 63 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp5_ = g_strcmp0 (_tmp8_, "Paramset") != 0;
#line 516 "Gir.vala.c"
	}
#line 63 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp5_) {
#line 64 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		g_print ("skip parent not Paramset\n");
#line 65 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (parset);
#line 65 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return;
#line 526 "Gir.vala.c"
	}
#line 67 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp9_ = parset;
#line 67 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp10_ = _tmp9_->gparent;
#line 67 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp11_ = _g_object_ref0 (_tmp10_);
#line 67 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	method = _tmp11_;
#line 69 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp12_ = method;
#line 69 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp12_ == NULL) {
#line 70 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		g_print ("skip parent.parent is null\n");
#line 71 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (method);
#line 71 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (parset);
#line 71 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return;
#line 548 "Gir.vala.c"
	}
#line 73 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp13_ = method;
#line 73 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp14_ = _tmp13_->gparent;
#line 73 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp15_ = _g_object_ref0 (_tmp14_);
#line 73 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	cls = _tmp15_;
#line 74 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp17_ = cls;
#line 74 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp17_ == NULL) {
#line 74 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp16_ = TRUE;
#line 564 "Gir.vala.c"
	} else {
		PaleteGirObject* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
#line 74 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp18_ = cls;
#line 74 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp19_ = _tmp18_->nodetype;
#line 74 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp16_ = g_strcmp0 (_tmp19_, "Class") != 0;
#line 574 "Gir.vala.c"
	}
#line 74 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp16_) {
#line 76 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (cls);
#line 76 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (method);
#line 76 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (parset);
#line 76 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return;
#line 586 "Gir.vala.c"
	}
#line 81 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp20_ = c;
#line 81 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp21_ = cls;
#line 81 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp22_ = _tmp21_->name;
#line 81 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp23_ = method;
#line 81 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp24_ = _tmp23_->name;
#line 81 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp25_ = c;
#line 81 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp26_ = _tmp25_->name;
#line 81 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp27_ = palete_gir_fetchOverride (_tmp22_, _tmp24_, _tmp26_);
#line 81 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_free0 (_tmp20_->name);
#line 81 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp20_->name = _tmp27_;
#line 58 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (cls);
#line 58 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (method);
#line 58 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (parset);
#line 614 "Gir.vala.c"
}


gchar* palete_gir_fetchOverride (const gchar* cls, const gchar* method, const gchar* param) {
	gchar* result = NULL;
	gchar* key = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GeeHashMap* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	GeeHashMap* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	gpointer _tmp11_ = NULL;
#line 90 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	palete_gir_loadOverrides (FALSE);
#line 91 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp0_ = cls;
#line 91 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp1_ = method;
#line 91 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp2_ = param;
#line 91 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp3_ = g_strdup_printf ("%s.%s.%s", _tmp0_, _tmp1_, _tmp2_);
#line 91 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	key = _tmp3_;
#line 93 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp4_ = palete_gir_overrides;
#line 93 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp5_ = key;
#line 93 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp6_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp4_, _tmp5_);
#line 93 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (!_tmp6_) {
#line 651 "Gir.vala.c"
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
#line 94 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp7_ = param;
#line 94 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp8_ = g_strdup (_tmp7_);
#line 94 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		result = _tmp8_;
#line 94 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_free0 (key);
#line 94 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return result;
#line 664 "Gir.vala.c"
	}
#line 96 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp9_ = palete_gir_overrides;
#line 96 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp10_ = key;
#line 96 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp11_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp9_, _tmp10_);
#line 96 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	result = (gchar*) _tmp11_;
#line 96 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_free0 (key);
#line 96 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return result;
#line 678 "Gir.vala.c"
}


static Block20Data* block20_data_ref (Block20Data* _data20_) {
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	g_atomic_int_inc (&_data20_->_ref_count_);
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return _data20_;
#line 687 "Gir.vala.c"
}


static void block20_data_unref (void * _userdata_) {
	Block20Data* _data20_;
	_data20_ = (Block20Data*) _userdata_;
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (g_atomic_int_dec_and_test (&_data20_->_ref_count_)) {
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_json_object_unref0 (_data20_->obj);
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		g_slice_free (Block20Data, _data20_);
#line 700 "Gir.vala.c"
	}
}


static JsonNode* _vala_JsonNode_copy (JsonNode* self) {
#line 109 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return g_boxed_copy (json_node_get_type (), self);
#line 708 "Gir.vala.c"
}


static gpointer __vala_JsonNode_copy0 (gpointer self) {
#line 109 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return self ? _vala_JsonNode_copy (self) : NULL;
#line 715 "Gir.vala.c"
}


static void _vala_JsonNode_free (JsonNode* self) {
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	g_boxed_free (json_node_get_type (), self);
#line 722 "Gir.vala.c"
}


static gpointer _json_object_ref0 (gpointer self) {
#line 117 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return self ? json_object_ref (self) : NULL;
#line 729 "Gir.vala.c"
}


static void __lambda11_ (Block20Data* _data20_, JsonObject* o, const gchar* key, JsonNode* value) {
	gchar* v = NULL;
	JsonObject* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GeeHashMap* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
#line 122 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp0_ = _data20_->obj;
#line 122 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp1_ = key;
#line 122 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp2_ = json_object_get_string_member (_tmp0_, _tmp1_);
#line 122 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 122 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	v = _tmp3_;
#line 123 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp4_ = palete_gir_overrides;
#line 123 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp5_ = key;
#line 123 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp4_, _tmp5_, v);
#line 120 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_free0 (v);
#line 759 "Gir.vala.c"
}


static void ___lambda11__json_object_foreach (JsonObject* object, const gchar* member_name, JsonNode* member_node, gpointer self) {
#line 120 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	__lambda11_ (self, object, member_name, member_node);
#line 766 "Gir.vala.c"
}


void palete_gir_loadOverrides (gboolean force) {
	Block20Data* _data20_;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	JsonParser* pa = NULL;
	JsonParser* _tmp3_ = NULL;
	JsonParser* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	JsonNode* node = NULL;
	JsonParser* _tmp9_ = NULL;
	JsonNode* _tmp10_ = NULL;
	JsonNode* _tmp11_ = NULL;
	JsonNode* _tmp12_ = NULL;
	JsonNodeType _tmp13_ = 0;
	GeeHashMap* _tmp17_ = NULL;
	JsonNode* _tmp18_ = NULL;
	JsonObject* _tmp19_ = NULL;
	JsonObject* _tmp20_ = NULL;
	JsonObject* _tmp21_ = NULL;
	GError * _inner_error_ = NULL;
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_data20_ = g_slice_new0 (Block20Data);
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_data20_->_ref_count_ = 1;
#line 103 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp1_ = palete_gir_overrides_loaded;
#line 103 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp1_) {
#line 801 "Gir.vala.c"
		gboolean _tmp2_ = FALSE;
#line 103 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp2_ = force;
#line 103 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp0_ = !_tmp2_;
#line 807 "Gir.vala.c"
	} else {
#line 103 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp0_ = FALSE;
#line 811 "Gir.vala.c"
	}
#line 103 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp0_) {
#line 104 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		block20_data_unref (_data20_);
#line 104 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_data20_ = NULL;
#line 104 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return;
#line 821 "Gir.vala.c"
	}
#line 107 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp3_ = json_parser_new ();
#line 107 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	pa = _tmp3_;
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp4_ = pa;
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp5_ = builder_application_configDirectory ();
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp6_ = _tmp5_;
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp7_ = g_strconcat (_tmp6_, "/resources/Gir.overides", NULL);
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp8_ = _tmp7_;
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	json_parser_load_from_file (_tmp4_, _tmp8_, &_inner_error_);
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_free0 (_tmp8_);
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_free0 (_tmp6_);
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (pa);
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		block20_data_unref (_data20_);
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_data20_ = NULL;
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		g_clear_error (&_inner_error_);
#line 108 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return;
#line 857 "Gir.vala.c"
	}
#line 109 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp9_ = pa;
#line 109 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp10_ = json_parser_get_root (_tmp9_);
#line 109 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp11_ = __vala_JsonNode_copy0 (_tmp10_);
#line 109 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	node = _tmp11_;
#line 111 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp12_ = node;
#line 111 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp13_ = json_node_get_node_type (_tmp12_);
#line 111 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp13_ != JSON_NODE_OBJECT) {
#line 873 "Gir.vala.c"
		JsonNode* _tmp14_ = NULL;
		const gchar* _tmp15_ = NULL;
		GError* _tmp16_ = NULL;
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp14_ = node;
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp15_ = json_node_type_name (_tmp14_);
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp16_ = g_error_new (PALETE_GIR_ERROR, PALETE_GIR_ERROR_INVALID_FORMAT, "Error loading gir.overides : Unexpected element type %s", _tmp15_);
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_inner_error_ = _tmp16_;
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		__vala_JsonNode_free0 (node);
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (pa);
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		block20_data_unref (_data20_);
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_data20_ = NULL;
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		g_clear_error (&_inner_error_);
#line 112 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return;
#line 899 "Gir.vala.c"
	}
#line 114 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp17_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
#line 114 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (palete_gir_overrides);
#line 114 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	palete_gir_overrides = _tmp17_;
#line 117 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp18_ = node;
#line 117 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp19_ = json_node_get_object (_tmp18_);
#line 117 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp20_ = _json_object_ref0 (_tmp19_);
#line 117 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_data20_->obj = _tmp20_;
#line 120 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp21_ = _data20_->obj;
#line 120 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	json_object_foreach_member (_tmp21_, ___lambda11__json_object_foreach, _data20_);
#line 126 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	palete_gir_overrides_loaded = TRUE;
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	__vala_JsonNode_free0 (node);
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (pa);
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	block20_data_unref (_data20_);
#line 101 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_data20_ = NULL;
#line 929 "Gir.vala.c"
}


PaleteGir* palete_gir_factory (ProjectProject* project, const gchar* ns) {
	PaleteGir* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* cache = NULL;
	GeeHashMap* _tmp2_ = NULL;
	GeeHashMap* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	ProjectProject* _tmp5_ = NULL;
	PaleteGir* ret = NULL;
	GeeHashMap* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	gpointer _tmp20_ = NULL;
	gboolean _tmp21_ = FALSE;
	PaleteGir* _tmp22_ = NULL;
#line 140 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp0_ = palete_gir_global_cache;
#line 140 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp0_ == NULL) {
#line 951 "Gir.vala.c"
		GeeHashMap* _tmp1_ = NULL;
#line 141 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, PALETE_TYPE_GIR, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 141 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (palete_gir_global_cache);
#line 141 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		palete_gir_global_cache = _tmp1_;
#line 959 "Gir.vala.c"
	}
#line 144 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp2_ = palete_gir_global_cache;
#line 144 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 144 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	cache = _tmp3_;
#line 145 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp5_ = project;
#line 145 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp5_ != NULL) {
#line 971 "Gir.vala.c"
		ProjectProject* _tmp6_ = NULL;
#line 145 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp6_ = project;
#line 145 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp4_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, PROJECT_TYPE_GTK);
#line 977 "Gir.vala.c"
	} else {
#line 145 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp4_ = FALSE;
#line 981 "Gir.vala.c"
	}
#line 145 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp4_) {
#line 985 "Gir.vala.c"
		ProjectGtk* gproj = NULL;
		ProjectProject* _tmp7_ = NULL;
		ProjectGtk* _tmp8_ = NULL;
		ProjectGtk* _tmp9_ = NULL;
		gboolean _tmp10_ = FALSE;
		ProjectGtk* _tmp15_ = NULL;
		GeeHashMap* _tmp16_ = NULL;
		GeeHashMap* _tmp17_ = NULL;
#line 146 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp7_ = project;
#line 146 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp8_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, PROJECT_TYPE_GTK, ProjectGtk));
#line 146 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		gproj = _tmp8_;
#line 147 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp9_ = gproj;
#line 147 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp10_ = _tmp9_->gir_cache_loaded;
#line 147 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		if (!_tmp10_) {
#line 1006 "Gir.vala.c"
			PaleteVapiParser* a = NULL;
			ProjectProject* _tmp11_ = NULL;
			PaleteVapiParser* _tmp12_ = NULL;
			PaleteVapiParser* _tmp13_ = NULL;
			ProjectGtk* _tmp14_ = NULL;
#line 148 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp11_ = project;
#line 148 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp12_ = palete_vapi_parser_new (G_TYPE_CHECK_INSTANCE_CAST (_tmp11_, PROJECT_TYPE_GTK, ProjectGtk));
#line 148 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			a = _tmp12_;
#line 149 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp13_ = a;
#line 149 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			palete_vapi_parser_create_valac_tree (_tmp13_);
#line 150 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp14_ = gproj;
#line 150 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp14_->gir_cache_loaded = TRUE;
#line 147 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_vala_code_visitor_unref0 (a);
#line 1028 "Gir.vala.c"
		}
#line 152 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp15_ = gproj;
#line 152 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp16_ = _tmp15_->gir_cache;
#line 152 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp17_ = _g_object_ref0 (_tmp16_);
#line 152 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (cache);
#line 152 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		cache = _tmp17_;
#line 145 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (gproj);
#line 1042 "Gir.vala.c"
	}
#line 157 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp18_ = cache;
#line 157 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp19_ = ns;
#line 157 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp20_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp18_, _tmp19_);
#line 157 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	ret = (PaleteGir*) _tmp20_;
#line 161 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp22_ = ret;
#line 161 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp22_ != NULL) {
#line 1056 "Gir.vala.c"
		PaleteGir* _tmp23_ = NULL;
		gboolean _tmp24_ = FALSE;
#line 161 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp23_ = ret;
#line 161 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp24_ = ((PaleteGirObject*) _tmp23_)->is_overlaid;
#line 161 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp21_ = !_tmp24_;
#line 1065 "Gir.vala.c"
	} else {
#line 161 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp21_ = FALSE;
#line 1069 "Gir.vala.c"
	}
#line 161 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp21_) {
#line 1073 "Gir.vala.c"
		PaleteGir* _tmp25_ = NULL;
		GeeMapIterator* iter = NULL;
		PaleteGir* _tmp26_ = NULL;
		GeeHashMap* _tmp27_ = NULL;
		GeeMapIterator* _tmp28_ = NULL;
		PaleteGir* _tmp35_ = NULL;
		GeeHashMap* _tmp36_ = NULL;
		GeeMapIterator* _tmp37_ = NULL;
#line 162 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp25_ = ret;
#line 162 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		((PaleteGirObject*) _tmp25_)->is_overlaid = TRUE;
#line 163 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp26_ = ret;
#line 163 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp27_ = ((PaleteGirObject*) _tmp26_)->classes;
#line 163 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp28_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp27_);
#line 163 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		iter = _tmp28_;
#line 164 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		while (TRUE) {
#line 1096 "Gir.vala.c"
			GeeMapIterator* _tmp29_ = NULL;
			gboolean _tmp30_ = FALSE;
			GeeMapIterator* _tmp31_ = NULL;
			gpointer _tmp32_ = NULL;
			PaleteGirObject* _tmp33_ = NULL;
			ProjectProject* _tmp34_ = NULL;
#line 164 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp29_ = iter;
#line 164 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp30_ = gee_map_iterator_next (_tmp29_);
#line 164 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			if (!_tmp30_) {
#line 164 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				break;
#line 1111 "Gir.vala.c"
			}
#line 165 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp31_ = iter;
#line 165 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp32_ = gee_map_iterator_get_value (_tmp31_);
#line 165 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp33_ = (PaleteGirObject*) _tmp32_;
#line 165 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp34_ = project;
#line 165 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			palete_gir_object_overlayParent (_tmp33_, _tmp34_);
#line 165 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_g_object_unref0 (_tmp33_);
#line 1125 "Gir.vala.c"
		}
#line 168 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp35_ = ret;
#line 168 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp36_ = ((PaleteGirObject*) _tmp35_)->classes;
#line 168 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp37_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp36_);
#line 168 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (iter);
#line 168 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		iter = _tmp37_;
#line 169 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		while (TRUE) {
#line 1139 "Gir.vala.c"
			GeeMapIterator* _tmp38_ = NULL;
			gboolean _tmp39_ = FALSE;
			GeeMapIterator* _tmp40_ = NULL;
			gpointer _tmp41_ = NULL;
			PaleteGirObject* _tmp42_ = NULL;
#line 169 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp38_ = iter;
#line 169 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp39_ = gee_map_iterator_next (_tmp38_);
#line 169 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			if (!_tmp39_) {
#line 169 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				break;
#line 1153 "Gir.vala.c"
			}
#line 170 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp40_ = iter;
#line 170 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp41_ = gee_map_iterator_get_value (_tmp40_);
#line 170 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_tmp42_ = (PaleteGirObject*) _tmp41_;
#line 170 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			palete_gir_object_overlayCtorProperties (_tmp42_);
#line 170 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_g_object_unref0 (_tmp42_);
#line 1165 "Gir.vala.c"
		}
#line 161 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (iter);
#line 1169 "Gir.vala.c"
	}
#line 176 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	result = ret;
#line 176 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (cache);
#line 176 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return result;
#line 1177 "Gir.vala.c"
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 1295 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp0_ = str;
#line 1295 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp1_ = maxlen;
#line 1295 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
#line 1295 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	end = _tmp2_;
#line 1296 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp3_ = end;
#line 1296 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	if (_tmp3_ == NULL) {
#line 1200 "Gir.vala.c"
		glong _tmp4_ = 0L;
#line 1297 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp4_ = maxlen;
#line 1297 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		result = _tmp4_;
#line 1297 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		return result;
#line 1208 "Gir.vala.c"
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
#line 1299 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp5_ = end;
#line 1299 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp6_ = str;
#line 1299 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		result = (glong) (_tmp5_ - _tmp6_);
#line 1299 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		return result;
#line 1220 "Gir.vala.c"
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
#line 1308 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp1_ = offset;
#line 1308 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	if (_tmp1_ >= ((glong) 0)) {
#line 1242 "Gir.vala.c"
		glong _tmp2_ = 0L;
#line 1308 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp2_ = len;
#line 1308 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp0_ = _tmp2_ >= ((glong) 0);
#line 1248 "Gir.vala.c"
	} else {
#line 1308 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 1252 "Gir.vala.c"
	}
#line 1308 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	if (_tmp0_) {
#line 1256 "Gir.vala.c"
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
#line 1310 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp3_ = offset;
#line 1310 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp4_ = len;
#line 1310 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
#line 1310 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		string_length = _tmp5_;
#line 1268 "Gir.vala.c"
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
#line 1312 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp6_ = strlen (self);
#line 1312 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp7_ = _tmp6_;
#line 1312 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		string_length = (glong) _tmp7_;
#line 1278 "Gir.vala.c"
	}
#line 1315 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp8_ = offset;
#line 1315 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	if (_tmp8_ < ((glong) 0)) {
#line 1284 "Gir.vala.c"
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
#line 1316 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp9_ = string_length;
#line 1316 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp10_ = offset;
#line 1316 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		offset = _tmp9_ + _tmp10_;
#line 1317 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp11_ = offset;
#line 1317 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
#line 1298 "Gir.vala.c"
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
#line 1319 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp12_ = offset;
#line 1319 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp13_ = string_length;
#line 1319 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
#line 1308 "Gir.vala.c"
	}
#line 1321 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp14_ = len;
#line 1321 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	if (_tmp14_ < ((glong) 0)) {
#line 1314 "Gir.vala.c"
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
#line 1322 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp15_ = string_length;
#line 1322 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		_tmp16_ = offset;
#line 1322 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
		len = _tmp15_ - _tmp16_;
#line 1323 "Gir.vala.c"
	}
#line 1324 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp17_ = offset;
#line 1324 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp18_ = len;
#line 1324 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp19_ = string_length;
#line 1324 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
#line 1325 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp20_ = offset;
#line 1325 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp21_ = len;
#line 1325 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
#line 1325 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	result = _tmp22_;
#line 1325 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	return result;
#line 1343 "Gir.vala.c"
}


PaleteGirObject* palete_gir_factoryFqn (ProjectProject* project, const gchar* fqn) {
	PaleteGirObject* result = NULL;
	gchar** bits = NULL;
	const gchar* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint bits_length1 = 0;
	gint _bits_size_ = 0;
	gchar** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	PaleteGirObject* f = NULL;
	ProjectProject* _tmp4_ = NULL;
	gchar** _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	const gchar* _tmp6_ = NULL;
	PaleteGir* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	gchar** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	PaleteGirObject* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	gchar** _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	const gchar* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	PaleteGirObject* _tmp19_ = NULL;
	PaleteGirObject* _tmp20_ = NULL;
#line 185 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp0_ = fqn;
#line 185 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp2_ = _tmp1_ = g_strsplit (_tmp0_, ".", 0);
#line 185 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	bits = _tmp2_;
#line 185 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	bits_length1 = _vala_array_length (_tmp1_);
#line 185 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_bits_size_ = bits_length1;
#line 186 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp3_ = bits;
#line 186 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp3__length1 = bits_length1;
#line 186 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp3__length1 < 1) {
#line 187 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		result = NULL;
#line 187 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		bits = (_vala_array_free (bits, bits_length1, (GDestroyNotify) g_free), NULL);
#line 187 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return result;
#line 1399 "Gir.vala.c"
	}
#line 190 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp4_ = project;
#line 190 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp5_ = bits;
#line 190 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp5__length1 = bits_length1;
#line 190 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp6_ = _tmp5_[0];
#line 190 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp7_ = palete_gir_factory (_tmp4_, _tmp6_);
#line 190 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	f = G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, PALETE_TYPE_GIR_OBJECT, PaleteGirObject);
#line 192 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp9_ = bits;
#line 192 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp9__length1 = bits_length1;
#line 192 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp9__length1 == 1) {
#line 192 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp8_ = TRUE;
#line 1421 "Gir.vala.c"
	} else {
		PaleteGirObject* _tmp10_ = NULL;
#line 192 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp10_ = f;
#line 192 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp8_ = _tmp10_ == NULL;
#line 1428 "Gir.vala.c"
	}
#line 192 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp8_) {
#line 193 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		result = f;
#line 193 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		bits = (_vala_array_free (bits, bits_length1, (GDestroyNotify) g_free), NULL);
#line 193 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return result;
#line 1438 "Gir.vala.c"
	}
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp11_ = f;
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp12_ = fqn;
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp13_ = bits;
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp13__length1 = bits_length1;
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp14_ = _tmp13_[0];
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp15_ = strlen (_tmp14_);
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp16_ = _tmp15_;
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp17_ = string_substring (_tmp12_, (glong) (_tmp16_ + 1), (glong) -1);
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp18_ = _tmp17_;
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp19_ = palete_gir_object_fetchByFqn (_tmp11_, _tmp18_);
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp20_ = _tmp19_;
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_free0 (_tmp18_);
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	result = _tmp20_;
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (f);
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	bits = (_vala_array_free (bits, bits_length1, (GDestroyNotify) g_free), NULL);
#line 195 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return result;
#line 1472 "Gir.vala.c"
}


/**
 * guess the fqn of a type == eg. gboolean or Widget etc...
 */
gchar* palete_gir_fqtypeLookup (ProjectProject* project, const gchar* type, const gchar* ns) {
	gchar* result = NULL;
	PaleteGir* g = NULL;
	ProjectProject* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	PaleteGir* _tmp2_ = NULL;
	PaleteGir* _tmp3_ = NULL;
	GeeHashMap* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	PaleteGir* _tmp13_ = NULL;
	GeeHashMap* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	gboolean _tmp16_ = FALSE;
	GeeMapIterator* iter = NULL;
	PaleteGir* _tmp23_ = NULL;
	GeeHashMap* _tmp24_ = NULL;
	GeeMapIterator* _tmp25_ = NULL;
	const gchar* _tmp41_ = NULL;
	gchar* _tmp42_ = NULL;
#line 205 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp0_ = project;
#line 205 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp1_ = ns;
#line 205 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp2_ = palete_gir_factory (_tmp0_, _tmp1_);
#line 205 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	g = _tmp2_;
#line 206 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp3_ = g;
#line 206 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp4_ = ((PaleteGirObject*) _tmp3_)->classes;
#line 206 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp5_ = type;
#line 206 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp6_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp4_, _tmp5_);
#line 206 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp6_) {
#line 1517 "Gir.vala.c"
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
#line 207 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp7_ = ns;
#line 207 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp8_ = g_strconcat (_tmp7_, ".", NULL);
#line 207 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp9_ = _tmp8_;
#line 207 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp10_ = type;
#line 207 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp11_ = g_strconcat (_tmp9_, _tmp10_, NULL);
#line 207 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp12_ = _tmp11_;
#line 207 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_free0 (_tmp9_);
#line 207 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		result = _tmp12_;
#line 207 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (g);
#line 207 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return result;
#line 1544 "Gir.vala.c"
	}
#line 210 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp13_ = g;
#line 210 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp14_ = ((PaleteGirObject*) _tmp13_)->consts;
#line 210 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp15_ = type;
#line 210 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp16_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp14_, _tmp15_);
#line 210 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp16_) {
#line 1556 "Gir.vala.c"
		const gchar* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		const gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
#line 211 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp17_ = ns;
#line 211 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp18_ = g_strconcat (_tmp17_, ".", NULL);
#line 211 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp19_ = _tmp18_;
#line 211 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp20_ = type;
#line 211 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp21_ = g_strconcat (_tmp19_, _tmp20_, NULL);
#line 211 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp22_ = _tmp21_;
#line 211 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_free0 (_tmp19_);
#line 211 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		result = _tmp22_;
#line 211 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_object_unref0 (g);
#line 211 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return result;
#line 1583 "Gir.vala.c"
	}
#line 216 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp23_ = g;
#line 216 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp24_ = ((PaleteGirObject*) _tmp23_)->includes;
#line 216 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp25_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp24_);
#line 216 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	iter = _tmp25_;
#line 217 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	while (TRUE) {
#line 1595 "Gir.vala.c"
		GeeMapIterator* _tmp26_ = NULL;
		gboolean _tmp27_ = FALSE;
		GeeMapIterator* _tmp28_ = NULL;
		gpointer _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		gboolean _tmp31_ = FALSE;
		gchar* ret = NULL;
		ProjectProject* _tmp32_ = NULL;
		const gchar* _tmp33_ = NULL;
		GeeMapIterator* _tmp34_ = NULL;
		gpointer _tmp35_ = NULL;
		gchar* _tmp36_ = NULL;
		gchar* _tmp37_ = NULL;
		gchar* _tmp38_ = NULL;
		const gchar* _tmp39_ = NULL;
		const gchar* _tmp40_ = NULL;
#line 217 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp26_ = iter;
#line 217 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp27_ = gee_map_iterator_next (_tmp26_);
#line 217 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		if (!_tmp27_) {
#line 217 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			break;
#line 1620 "Gir.vala.c"
		}
#line 219 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp28_ = iter;
#line 219 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp29_ = gee_map_iterator_get_key (_tmp28_);
#line 219 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp30_ = (gchar*) _tmp29_;
#line 219 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp31_ = g_strcmp0 (_tmp30_, "") == 0;
#line 219 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_free0 (_tmp30_);
#line 219 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		if (_tmp31_) {
#line 220 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			continue;
#line 1636 "Gir.vala.c"
		}
#line 222 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp32_ = project;
#line 222 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp33_ = type;
#line 222 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp34_ = iter;
#line 222 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp35_ = gee_map_iterator_get_key (_tmp34_);
#line 222 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp36_ = (gchar*) _tmp35_;
#line 222 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp37_ = palete_gir_fqtypeLookup (_tmp32_, _tmp33_, _tmp36_);
#line 222 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp38_ = _tmp37_;
#line 222 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_free0 (_tmp36_);
#line 222 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		ret = _tmp38_;
#line 223 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp39_ = ret;
#line 223 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp40_ = type;
#line 223 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		if (g_strcmp0 (_tmp39_, _tmp40_) != 0) {
#line 224 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			result = ret;
#line 224 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_g_object_unref0 (iter);
#line 224 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			_g_object_unref0 (g);
#line 224 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
			return result;
#line 1670 "Gir.vala.c"
		}
#line 217 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_g_free0 (ret);
#line 1674 "Gir.vala.c"
	}
#line 227 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp41_ = type;
#line 227 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp42_ = g_strdup (_tmp41_);
#line 227 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	result = _tmp42_;
#line 227 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (iter);
#line 227 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_g_object_unref0 (g);
#line 227 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	return result;
#line 1688 "Gir.vala.c"
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 1377 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp0_ = needle;
#line 1377 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
#line 1377 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	result = _tmp1_ != NULL;
#line 1377 "/usr/share/vala-0.32/vapi/glib-2.0.vapi"
	return result;
#line 1704 "Gir.vala.c"
}


gchar* palete_gir_guessDefaultValueForType (const gchar* type) {
	gchar* result = NULL;
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GQuark _tmp10_ = 0U;
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	static GQuark _tmp9_label0 = 0;
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	static GQuark _tmp9_label1 = 0;
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	static GQuark _tmp9_label2 = 0;
#line 236 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp1_ = type;
#line 236 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp2_ = strlen (_tmp1_);
#line 236 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp3_ = _tmp2_;
#line 236 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp3_ < 1) {
#line 236 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp0_ = TRUE;
#line 1733 "Gir.vala.c"
	} else {
		const gchar* _tmp4_ = NULL;
		gboolean _tmp5_ = FALSE;
#line 236 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp4_ = type;
#line 236 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp5_ = string_contains (_tmp4_, ".");
#line 236 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp0_ = _tmp5_;
#line 1743 "Gir.vala.c"
	}
#line 236 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp0_) {
#line 1747 "Gir.vala.c"
		gchar* _tmp6_ = NULL;
#line 237 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		_tmp6_ = g_strdup ("null");
#line 237 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		result = _tmp6_;
#line 237 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		return result;
#line 1755 "Gir.vala.c"
	}
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp7_ = type;
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp8_ = _tmp7_;
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	_tmp10_ = (NULL == _tmp8_) ? 0 : g_quark_from_string (_tmp8_);
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	if (_tmp10_ == ((0 != _tmp9_label0) ? _tmp9_label0 : (_tmp9_label0 = g_quark_from_static_string ("gboolean")))) {
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		switch (0) {
#line 1767 "Gir.vala.c"
			default:
			{
				gchar* _tmp11_ = NULL;
#line 241 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				_tmp11_ = g_strdup ("true");
#line 241 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				result = _tmp11_;
#line 241 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				return result;
#line 1777 "Gir.vala.c"
			}
		}
	} else if (_tmp10_ == ((0 != _tmp9_label1) ? _tmp9_label1 : (_tmp9_label1 = g_quark_from_static_string ("guint")))) {
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		switch (0) {
#line 1783 "Gir.vala.c"
			default:
			{
				gchar* _tmp12_ = NULL;
#line 243 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				_tmp12_ = g_strdup ("0");
#line 243 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				result = _tmp12_;
#line 243 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				return result;
#line 1793 "Gir.vala.c"
			}
		}
	} else if (_tmp10_ == ((0 != _tmp9_label2) ? _tmp9_label2 : (_tmp9_label2 = g_quark_from_static_string ("utf8")))) {
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		switch (0) {
#line 1799 "Gir.vala.c"
			default:
			{
				gchar* _tmp13_ = NULL;
#line 245 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				_tmp13_ = g_strdup ("\"\"");
#line 245 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				result = _tmp13_;
#line 245 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				return result;
#line 1809 "Gir.vala.c"
			}
		}
	} else {
#line 239 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
		switch (0) {
#line 1815 "Gir.vala.c"
			default:
			{
				const gchar* _tmp14_ = NULL;
				gchar* _tmp15_ = NULL;
				gchar* _tmp16_ = NULL;
				gchar* _tmp17_ = NULL;
				gchar* _tmp18_ = NULL;
#line 247 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				_tmp14_ = type;
#line 247 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				_tmp15_ = g_strconcat ("?", _tmp14_, NULL);
#line 247 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				_tmp16_ = _tmp15_;
#line 247 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				_tmp17_ = g_strconcat (_tmp16_, "?", NULL);
#line 247 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				_tmp18_ = _tmp17_;
#line 247 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				_g_free0 (_tmp16_);
#line 247 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				result = _tmp18_;
#line 247 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
				return result;
#line 1839 "Gir.vala.c"
			}
		}
	}
}


static void palete_gir_class_init (PaleteGirClass * klass) {
#line 29 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	palete_gir_parent_class = g_type_class_peek_parent (klass);
#line 29 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	G_OBJECT_CLASS (klass)->finalize = palete_gir_finalize;
#line 1851 "Gir.vala.c"
}


static void palete_gir_instance_init (PaleteGir * self) {
}


static void palete_gir_finalize (GObject* obj) {
	PaleteGir * self;
#line 29 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PALETE_TYPE_GIR, PaleteGir);
#line 29 "/home/alan/gitlive/roobuilder/src/Palete/Gir.vala"
	G_OBJECT_CLASS (palete_gir_parent_class)->finalize (obj);
#line 1865 "Gir.vala.c"
}


GType palete_gir_get_type (void) {
	static volatile gsize palete_gir_type_id__volatile = 0;
	if (g_once_init_enter (&palete_gir_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PaleteGirClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) palete_gir_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PaleteGir), 0, (GInstanceInitFunc) palete_gir_instance_init, NULL };
		GType palete_gir_type_id;
		palete_gir_type_id = g_type_register_static (PALETE_TYPE_GIR_OBJECT, "PaleteGir", &g_define_type_info, 0);
		g_once_init_leave (&palete_gir_type_id__volatile, palete_gir_type_id);
	}
	return palete_gir_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
#line 26 "/home/alan/gitlive/roobuilder/src/JsRender/NodeToGtk.vala"
	if ((array != NULL) && (destroy_func != NULL)) {
#line 1884 "Gir.vala.c"
		int i;
#line 26 "/home/alan/gitlive/roobuilder/src/JsRender/NodeToGtk.vala"
		for (i = 0; i < array_length; i = i + 1) {
#line 26 "/home/alan/gitlive/roobuilder/src/JsRender/NodeToGtk.vala"
			if (((gpointer*) array)[i] != NULL) {
#line 26 "/home/alan/gitlive/roobuilder/src/JsRender/NodeToGtk.vala"
				destroy_func (((gpointer*) array)[i]);
#line 1892 "Gir.vala.c"
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
#line 26 "/home/alan/gitlive/roobuilder/src/JsRender/NodeToGtk.vala"
	_vala_array_destroy (array, array_length, destroy_func);
#line 26 "/home/alan/gitlive/roobuilder/src/JsRender/NodeToGtk.vala"
	g_free (array);
#line 1904 "Gir.vala.c"
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
#line 26 "/home/alan/gitlive/roobuilder/src/JsRender/NodeToGtk.vala"
	if (array) {
#line 26 "/home/alan/gitlive/roobuilder/src/JsRender/NodeToGtk.vala"
		while (((gpointer*) array)[length]) {
#line 26 "/home/alan/gitlive/roobuilder/src/JsRender/NodeToGtk.vala"
			length++;
#line 1917 "Gir.vala.c"
		}
	}
#line 26 "/home/alan/gitlive/roobuilder/src/JsRender/NodeToGtk.vala"
	return length;
#line 1922 "Gir.vala.c"
}



