/* Gir.vala.c generated by valac, the Vala compiler
 * generated from Gir.vala, do not modify */

/* valac -g  --pkg gee-1.0 --pkg libxml-2.0 --pkg gobject-introspection-1.0 --pkg json-glib-1.0  Palete/Gir.vala -o /tmp/Gir*/
/* 
public static int main (string[] args) {
    
    var g = Palete.Gir.factory("Gtk");
var test = g.classes.get("ToolButton");


    var generator = new Json.Generator ();
    var n = new Json.Node(Json.NodeType.OBJECT);
    n.set_object(test.toJSON());
    generator.set_root(n);
    generator.indent = 4;
    generator.pretty = true;
    
    print(generator.to_data(null));
    return 0;
}
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>
#include <json-glib/json-glib.h>
#include <vala.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define PALETE_TYPE_GIR_OBJECT (palete_gir_object_get_type ())
#define PALETE_GIR_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_GIR_OBJECT, PaleteGirObject))
#define PALETE_GIR_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_GIR_OBJECT, PaleteGirObjectClass))
#define PALETE_IS_GIR_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_GIR_OBJECT))
#define PALETE_IS_GIR_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_GIR_OBJECT))
#define PALETE_GIR_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_GIR_OBJECT, PaleteGirObjectClass))

typedef struct _PaleteGirObject PaleteGirObject;
typedef struct _PaleteGirObjectClass PaleteGirObjectClass;
typedef struct _PaleteGirObjectPrivate PaleteGirObjectPrivate;

#define PALETE_TYPE_GIR (palete_gir_get_type ())
#define PALETE_GIR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_GIR, PaleteGir))
#define PALETE_GIR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_GIR, PaleteGirClass))
#define PALETE_IS_GIR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_GIR))
#define PALETE_IS_GIR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_GIR))
#define PALETE_GIR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_GIR, PaleteGirClass))

typedef struct _PaleteGir PaleteGir;
typedef struct _PaleteGirClass PaleteGirClass;
typedef struct _PaleteGirPrivate PaleteGirPrivate;
enum  {
	PALETE_GIR_0_PROPERTY,
	PALETE_GIR_NUM_PROPERTIES
};
static GParamSpec* palete_gir_properties[PALETE_GIR_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block14Data Block14Data;
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))

#define PROJECT_TYPE_PROJECT (project_project_get_type ())
#define PROJECT_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROJECT_TYPE_PROJECT, ProjectProject))
#define PROJECT_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROJECT_TYPE_PROJECT, ProjectProjectClass))
#define PROJECT_IS_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROJECT_TYPE_PROJECT))
#define PROJECT_IS_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROJECT_TYPE_PROJECT))
#define PROJECT_PROJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROJECT_TYPE_PROJECT, ProjectProjectClass))

typedef struct _ProjectProject ProjectProject;
typedef struct _ProjectProjectClass ProjectProjectClass;

#define PROJECT_TYPE_GTK (project_gtk_get_type ())
#define PROJECT_GTK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROJECT_TYPE_GTK, ProjectGtk))
#define PROJECT_GTK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROJECT_TYPE_GTK, ProjectGtkClass))
#define PROJECT_IS_GTK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROJECT_TYPE_GTK))
#define PROJECT_IS_GTK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROJECT_TYPE_GTK))
#define PROJECT_GTK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROJECT_TYPE_GTK, ProjectGtkClass))

typedef struct _ProjectGtk ProjectGtk;
typedef struct _ProjectGtkClass ProjectGtkClass;
typedef struct _ProjectProjectPrivate ProjectProjectPrivate;

#define PALETE_TYPE_PALETE (palete_palete_get_type ())
#define PALETE_PALETE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_PALETE, PaletePalete))
#define PALETE_PALETE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_PALETE, PaletePaleteClass))
#define PALETE_IS_PALETE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_PALETE))
#define PALETE_IS_PALETE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_PALETE))
#define PALETE_PALETE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_PALETE, PaletePaleteClass))

typedef struct _PaletePalete PaletePalete;
typedef struct _PaletePaleteClass PaletePaleteClass;
typedef struct _ProjectGtkPrivate ProjectGtkPrivate;

#define PROJECT_TYPE_GTK_VALA_SETTINGS (project_gtk_vala_settings_get_type ())
#define PROJECT_GTK_VALA_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROJECT_TYPE_GTK_VALA_SETTINGS, ProjectGtkValaSettings))
#define PROJECT_GTK_VALA_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROJECT_TYPE_GTK_VALA_SETTINGS, ProjectGtkValaSettingsClass))
#define PROJECT_IS_GTK_VALA_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROJECT_TYPE_GTK_VALA_SETTINGS))
#define PROJECT_IS_GTK_VALA_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROJECT_TYPE_GTK_VALA_SETTINGS))
#define PROJECT_GTK_VALA_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROJECT_TYPE_GTK_VALA_SETTINGS, ProjectGtkValaSettingsClass))

typedef struct _ProjectGtkValaSettings ProjectGtkValaSettings;
typedef struct _ProjectGtkValaSettingsClass ProjectGtkValaSettingsClass;

#define PALETE_TYPE_VAPI_PARSER (palete_vapi_parser_get_type ())
#define PALETE_VAPI_PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PALETE_TYPE_VAPI_PARSER, PaleteVapiParser))
#define PALETE_VAPI_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PALETE_TYPE_VAPI_PARSER, PaleteVapiParserClass))
#define PALETE_IS_VAPI_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PALETE_TYPE_VAPI_PARSER))
#define PALETE_IS_VAPI_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PALETE_TYPE_VAPI_PARSER))
#define PALETE_VAPI_PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PALETE_TYPE_VAPI_PARSER, PaleteVapiParserClass))

typedef struct _PaleteVapiParser PaleteVapiParser;
typedef struct _PaleteVapiParserClass PaleteVapiParserClass;
#define _vala_code_visitor_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_visitor_unref (var), NULL)))

struct _PaleteGirObject {
	GObject parent_instance;
	PaleteGirObjectPrivate * priv;
	gchar* name;
	gchar* ns;
	gchar* propertyof;
	gchar* type;
	gchar* nodetype;
	gchar* package;
	gchar* direction;
	PaleteGirObject* paramset;
	PaleteGirObject* return_value;
	gboolean is_deprecated;
	gboolean is_instance;
	gboolean is_array;
	gboolean is_varargs;
	gboolean ctor_only;
	gboolean is_writable;
	gboolean is_readable;
	gboolean is_abstract;
	gchar* parent;
	gchar* value;
	gchar* sig;
	gboolean is_overlaid;
	PaleteGirObject* gparent;
	GeeArrayList* params;
	GeeArrayList* implements;
	GeeArrayList* implementations;
	GeeArrayList* inherits;
	GeeHashMap* ctors;
	GeeHashMap* methods;
	GeeHashMap* includes;
	GeeHashMap* classes;
	GeeHashMap* props;
	GeeHashMap* consts;
	GeeHashMap* signals;
	GeeArrayList* optvalues;
	GeeArrayList* can_drop_onto;
	GeeArrayList* valid_cn;
	gchar* doctxt;
};

struct _PaleteGirObjectClass {
	GObjectClass parent_class;
};

struct _PaleteGir {
	PaleteGirObject parent_instance;
	PaleteGirPrivate * priv;
};

struct _PaleteGirClass {
	PaleteGirObjectClass parent_class;
};

struct _Block14Data {
	int _ref_count_;
	JsonObject* obj;
};

struct _ProjectProject {
	GObject parent_instance;
	ProjectProjectPrivate * priv;
	gchar* path;
	gchar* xtype;
	PaletePalete* palete;
};

struct _ProjectProjectClass {
	GObjectClass parent_class;
	void (*loadJson) (ProjectProject* self, JsonObject* obj);
	void (*saveJson) (ProjectProject* self, JsonObject* obj);
	void (*initDatabase) (ProjectProject* self);
	void (*initialize) (ProjectProject* self);
};

struct _ProjectGtk {
	ProjectProject parent_instance;
	ProjectGtkPrivate * priv;
	GeeHashMap* gir_cache;
	gboolean gir_cache_loaded;
	GeeHashMap* dropList;
	GeeHashMap* child_list_cache;
	GeeHashMap* child_list_cache_props;
	gchar* compile_flags;
	GeeArrayList* packages;
	GeeArrayList* hidden;
	ProjectGtkValaSettings* active_cg;
	GeeHashMap* compilegroups;
};

struct _ProjectGtkClass {
	ProjectProjectClass parent_class;
};

static gpointer palete_gir_parent_class = NULL;
VALA_EXTERN gboolean palete_gir_overrides_loaded;
gboolean palete_gir_overrides_loaded = FALSE;
VALA_EXTERN GeeHashMap* palete_gir_overrides;
GeeHashMap* palete_gir_overrides = NULL;
VALA_EXTERN GeeHashMap* palete_gir_global_cache;
GeeHashMap* palete_gir_global_cache = NULL;

VALA_EXTERN GType palete_gir_object_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (PaleteGirObject, g_object_unref)
VALA_EXTERN GType palete_gir_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (PaleteGir, g_object_unref)
VALA_EXTERN PaleteGir* palete_gir_new (const gchar* ns);
VALA_EXTERN PaleteGir* palete_gir_construct (GType object_type,
                                 const gchar* ns);
VALA_EXTERN PaleteGirObject* palete_gir_object_new (const gchar* nodetype,
                                        const gchar* n);
VALA_EXTERN PaleteGirObject* palete_gir_object_construct (GType object_type,
                                              const gchar* nodetype,
                                              const gchar* n);
VALA_EXTERN gchar* palete_gir_doc (PaleteGir* self,
                       const gchar* what);
VALA_EXTERN void palete_gir_checkParamOverride (PaleteGirObject* c);
VALA_EXTERN gchar* palete_gir_fetchOverride (const gchar* cls,
                                 const gchar* method,
                                 const gchar* param);
VALA_EXTERN void palete_gir_loadOverrides (gboolean force);
static Block14Data* block14_data_ref (Block14Data* _data14_);
static void block14_data_unref (void * _userdata_);
VALA_EXTERN gchar* builder_application_configDirectory (void);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
static void _vala_JsonNode_free (JsonNode* self);
static void __lambda233_ (Block14Data* _data14_,
                   JsonObject* o,
                   const gchar* key,
                   JsonNode* value);
static void ___lambda233__json_object_foreach (JsonObject* object,
                                        const gchar* member_name,
                                        JsonNode* member_node,
                                        gpointer self);
VALA_EXTERN GType project_project_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProjectProject, g_object_unref)
VALA_EXTERN PaleteGir* palete_gir_factory (ProjectProject* project,
                               const gchar* ns);
VALA_EXTERN GType project_gtk_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProjectGtk, g_object_unref)
VALA_EXTERN GType palete_palete_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (PaletePalete, g_object_unref)
VALA_EXTERN GType project_gtk_vala_settings_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProjectGtkValaSettings, g_object_unref)
VALA_EXTERN GType palete_vapi_parser_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (PaleteVapiParser, vala_code_visitor_unref)
VALA_EXTERN PaleteVapiParser* palete_vapi_parser_new (ProjectGtk* project);
VALA_EXTERN PaleteVapiParser* palete_vapi_parser_construct (GType object_type,
                                                ProjectGtk* project);
VALA_EXTERN void palete_vapi_parser_create_valac_tree (PaleteVapiParser* self);
VALA_EXTERN void palete_gir_object_overlayParent (PaleteGirObject* self,
                                      ProjectProject* project);
VALA_EXTERN void palete_gir_object_overlayCtorProperties (PaleteGirObject* self);
VALA_EXTERN PaleteGirObject* palete_gir_factoryFqn (ProjectProject* project,
                                        const gchar* in_fqn);
VALA_EXTERN PaleteGirObject* palete_gir_object_fetchByFqn (PaleteGirObject* self,
                                               const gchar* fqn);
VALA_EXTERN gchar* palete_gir_fqtypeLookup (ProjectProject* project,
                                const gchar* type,
                                const gchar* ns);
VALA_EXTERN gchar* palete_gir_guessDefaultValueForType (const gchar* type);
static void palete_gir_finalize (GObject * obj);
static GType palete_gir_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

PaleteGir*
palete_gir_construct (GType object_type,
                      const gchar* ns)
{
	PaleteGir * self = NULL;
#line 35 "Gir.vala"
	self = (PaleteGir*) palete_gir_object_construct (object_type, "Package", ns);
#line 33 "Gir.vala"
	return self;
#line 311 "Gir.vala.c"
}

PaleteGir*
palete_gir_new (const gchar* ns)
{
#line 33 "Gir.vala"
	return palete_gir_construct (PALETE_TYPE_GIR, ns);
#line 319 "Gir.vala.c"
}

gchar*
palete_gir_doc (PaleteGir* self,
                const gchar* what)
{
	gchar** ar = NULL;
	gchar** _tmp0_;
	gchar** _tmp1_;
	gint ar_length1;
	gint _ar_size_;
	PaleteGirObject* cls = NULL;
	GeeHashMap* _tmp2_;
	gchar** _tmp3_;
	gint _tmp3__length1;
	const gchar* _tmp4_;
	gpointer _tmp5_;
	gchar** _tmp6_;
	gint _tmp6__length1;
	PaleteGirObject* pr = NULL;
	PaleteGirObject* _tmp13_;
	GeeHashMap* _tmp14_;
	gchar** _tmp15_;
	gint _tmp15__length1;
	const gchar* _tmp16_;
	gpointer _tmp17_;
	const gchar* _tmp18_ = NULL;
	PaleteGirObject* _tmp19_;
	const gchar* _tmp20_;
	gchar* _tmp23_;
	gchar* result;
#line 41 "Gir.vala"
	_tmp1_ = _tmp0_ = g_strsplit (what, ".", 0);
#line 41 "Gir.vala"
	ar = _tmp1_;
#line 41 "Gir.vala"
	ar_length1 = _vala_array_length (_tmp0_);
#line 41 "Gir.vala"
	_ar_size_ = ar_length1;
#line 42 "Gir.vala"
	_tmp2_ = ((PaleteGirObject*) self)->classes;
#line 42 "Gir.vala"
	_tmp3_ = ar;
#line 42 "Gir.vala"
	_tmp3__length1 = ar_length1;
#line 42 "Gir.vala"
	_tmp4_ = _tmp3_[1];
#line 42 "Gir.vala"
	_tmp5_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp2_, _tmp4_);
#line 42 "Gir.vala"
	cls = (PaleteGirObject*) _tmp5_;
#line 43 "Gir.vala"
	_tmp6_ = ar;
#line 43 "Gir.vala"
	_tmp6__length1 = ar_length1;
#line 43 "Gir.vala"
	if (_tmp6__length1 == 2) {
#line 377 "Gir.vala.c"
		const gchar* _tmp7_ = NULL;
		PaleteGirObject* _tmp8_;
		const gchar* _tmp9_;
		gchar* _tmp12_;
#line 44 "Gir.vala"
		_tmp8_ = cls;
#line 44 "Gir.vala"
		_tmp9_ = _tmp8_->doctxt;
#line 44 "Gir.vala"
		if (_tmp9_ != NULL) {
#line 388 "Gir.vala.c"
			PaleteGirObject* _tmp10_;
			const gchar* _tmp11_;
#line 44 "Gir.vala"
			_tmp10_ = cls;
#line 44 "Gir.vala"
			_tmp11_ = _tmp10_->doctxt;
#line 44 "Gir.vala"
			_tmp7_ = _tmp11_;
#line 397 "Gir.vala.c"
		} else {
#line 44 "Gir.vala"
			_tmp7_ = "";
#line 401 "Gir.vala.c"
		}
#line 44 "Gir.vala"
		_tmp12_ = g_strdup (_tmp7_);
#line 44 "Gir.vala"
		result = _tmp12_;
#line 44 "Gir.vala"
		_g_object_unref0 (cls);
#line 44 "Gir.vala"
		ar = (_vala_array_free (ar, ar_length1, (GDestroyNotify) g_free), NULL);
#line 44 "Gir.vala"
		return result;
#line 413 "Gir.vala.c"
	}
#line 47 "Gir.vala"
	_tmp13_ = cls;
#line 47 "Gir.vala"
	_tmp14_ = _tmp13_->props;
#line 47 "Gir.vala"
	_tmp15_ = ar;
#line 47 "Gir.vala"
	_tmp15__length1 = ar_length1;
#line 47 "Gir.vala"
	_tmp16_ = _tmp15_[2];
#line 47 "Gir.vala"
	_tmp17_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp14_, _tmp16_);
#line 47 "Gir.vala"
	pr = (PaleteGirObject*) _tmp17_;
#line 48 "Gir.vala"
	_tmp19_ = pr;
#line 48 "Gir.vala"
	_tmp20_ = _tmp19_->doctxt;
#line 48 "Gir.vala"
	if (_tmp20_ != NULL) {
#line 435 "Gir.vala.c"
		PaleteGirObject* _tmp21_;
		const gchar* _tmp22_;
#line 48 "Gir.vala"
		_tmp21_ = pr;
#line 48 "Gir.vala"
		_tmp22_ = _tmp21_->doctxt;
#line 48 "Gir.vala"
		_tmp18_ = _tmp22_;
#line 444 "Gir.vala.c"
	} else {
#line 48 "Gir.vala"
		_tmp18_ = "";
#line 448 "Gir.vala.c"
	}
#line 48 "Gir.vala"
	_tmp23_ = g_strdup (_tmp18_);
#line 48 "Gir.vala"
	result = _tmp23_;
#line 48 "Gir.vala"
	_g_object_unref0 (pr);
#line 48 "Gir.vala"
	_g_object_unref0 (cls);
#line 48 "Gir.vala"
	ar = (_vala_array_free (ar, ar_length1, (GDestroyNotify) g_free), NULL);
#line 48 "Gir.vala"
	return result;
#line 462 "Gir.vala.c"
}

/**
 * since constructors from the API from gir or vala do not map
 * correctly to properties, we have an Gir.overides file in resources
 * that changes the ctor's for some elements.
 * 
 */
static gpointer
_g_object_ref0 (gpointer self)
{
#line 62 "Gir.vala"
	return self ? g_object_ref (self) : NULL;
#line 476 "Gir.vala.c"
}

void
palete_gir_checkParamOverride (PaleteGirObject* c)
{
	PaleteGirObject* parset = NULL;
	PaleteGirObject* _tmp0_;
	PaleteGirObject* _tmp1_;
	gboolean _tmp2_ = FALSE;
	PaleteGirObject* _tmp3_;
	PaleteGirObject* method = NULL;
	PaleteGirObject* _tmp6_;
	PaleteGirObject* _tmp7_;
	PaleteGirObject* _tmp8_;
	PaleteGirObject* _tmp9_;
	PaleteGirObject* cls = NULL;
	PaleteGirObject* _tmp10_;
	PaleteGirObject* _tmp11_;
	PaleteGirObject* _tmp12_;
	gboolean _tmp13_ = FALSE;
	PaleteGirObject* _tmp14_;
	PaleteGirObject* _tmp17_;
	const gchar* _tmp18_;
	PaleteGirObject* _tmp19_;
	const gchar* _tmp20_;
	const gchar* _tmp21_;
	gchar* _tmp22_;
#line 62 "Gir.vala"
	_tmp0_ = c->gparent;
#line 62 "Gir.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 62 "Gir.vala"
	parset = _tmp1_;
#line 63 "Gir.vala"
	_tmp3_ = parset;
#line 63 "Gir.vala"
	if (_tmp3_ == NULL) {
#line 63 "Gir.vala"
		_tmp2_ = TRUE;
#line 516 "Gir.vala.c"
	} else {
		PaleteGirObject* _tmp4_;
		const gchar* _tmp5_;
#line 63 "Gir.vala"
		_tmp4_ = parset;
#line 63 "Gir.vala"
		_tmp5_ = _tmp4_->nodetype;
#line 63 "Gir.vala"
		_tmp2_ = g_strcmp0 (_tmp5_, "Paramset") != 0;
#line 526 "Gir.vala.c"
	}
#line 63 "Gir.vala"
	if (_tmp2_) {
#line 64 "Gir.vala"
		g_print ("skip parent not Paramset\n");
#line 65 "Gir.vala"
		_g_object_unref0 (parset);
#line 65 "Gir.vala"
		return;
#line 536 "Gir.vala.c"
	}
#line 67 "Gir.vala"
	_tmp6_ = parset;
#line 67 "Gir.vala"
	_tmp7_ = _tmp6_->gparent;
#line 67 "Gir.vala"
	_tmp8_ = _g_object_ref0 (_tmp7_);
#line 67 "Gir.vala"
	method = _tmp8_;
#line 69 "Gir.vala"
	_tmp9_ = method;
#line 69 "Gir.vala"
	if (_tmp9_ == NULL) {
#line 70 "Gir.vala"
		g_print ("skip parent.parent is null\n");
#line 71 "Gir.vala"
		_g_object_unref0 (method);
#line 71 "Gir.vala"
		_g_object_unref0 (parset);
#line 71 "Gir.vala"
		return;
#line 558 "Gir.vala.c"
	}
#line 73 "Gir.vala"
	_tmp10_ = method;
#line 73 "Gir.vala"
	_tmp11_ = _tmp10_->gparent;
#line 73 "Gir.vala"
	_tmp12_ = _g_object_ref0 (_tmp11_);
#line 73 "Gir.vala"
	cls = _tmp12_;
#line 74 "Gir.vala"
	_tmp14_ = cls;
#line 74 "Gir.vala"
	if (_tmp14_ == NULL) {
#line 74 "Gir.vala"
		_tmp13_ = TRUE;
#line 574 "Gir.vala.c"
	} else {
		PaleteGirObject* _tmp15_;
		const gchar* _tmp16_;
#line 74 "Gir.vala"
		_tmp15_ = cls;
#line 74 "Gir.vala"
		_tmp16_ = _tmp15_->nodetype;
#line 74 "Gir.vala"
		_tmp13_ = g_strcmp0 (_tmp16_, "Class") != 0;
#line 584 "Gir.vala.c"
	}
#line 74 "Gir.vala"
	if (_tmp13_) {
#line 76 "Gir.vala"
		_g_object_unref0 (cls);
#line 76 "Gir.vala"
		_g_object_unref0 (method);
#line 76 "Gir.vala"
		_g_object_unref0 (parset);
#line 76 "Gir.vala"
		return;
#line 596 "Gir.vala.c"
	}
#line 81 "Gir.vala"
	_tmp17_ = cls;
#line 81 "Gir.vala"
	_tmp18_ = _tmp17_->name;
#line 81 "Gir.vala"
	_tmp19_ = method;
#line 81 "Gir.vala"
	_tmp20_ = _tmp19_->name;
#line 81 "Gir.vala"
	_tmp21_ = c->name;
#line 81 "Gir.vala"
	_tmp22_ = palete_gir_fetchOverride (_tmp18_, _tmp20_, _tmp21_);
#line 81 "Gir.vala"
	_g_free0 (c->name);
#line 81 "Gir.vala"
	c->name = _tmp22_;
#line 58 "Gir.vala"
	_g_object_unref0 (cls);
#line 58 "Gir.vala"
	_g_object_unref0 (method);
#line 58 "Gir.vala"
	_g_object_unref0 (parset);
#line 620 "Gir.vala.c"
}

gchar*
palete_gir_fetchOverride (const gchar* cls,
                          const gchar* method,
                          const gchar* param)
{
	gchar* key = NULL;
	gchar* _tmp0_;
	GeeHashMap* _tmp1_;
	const gchar* _tmp2_;
	GeeHashMap* _tmp4_;
	const gchar* _tmp5_;
	gpointer _tmp6_;
	gchar* result;
#line 91 "Gir.vala"
	palete_gir_loadOverrides (FALSE);
#line 92 "Gir.vala"
	_tmp0_ = g_strdup_printf ("%s.%s.%s", cls, method, param);
#line 92 "Gir.vala"
	key = _tmp0_;
#line 94 "Gir.vala"
	_tmp1_ = palete_gir_overrides;
#line 94 "Gir.vala"
	_tmp2_ = key;
#line 94 "Gir.vala"
	if (!gee_abstract_map_has_key ((GeeAbstractMap*) _tmp1_, _tmp2_)) {
#line 648 "Gir.vala.c"
		gchar* _tmp3_;
#line 95 "Gir.vala"
		_tmp3_ = g_strdup (param);
#line 95 "Gir.vala"
		result = _tmp3_;
#line 95 "Gir.vala"
		_g_free0 (key);
#line 95 "Gir.vala"
		return result;
#line 658 "Gir.vala.c"
	}
#line 97 "Gir.vala"
	_tmp4_ = palete_gir_overrides;
#line 97 "Gir.vala"
	_tmp5_ = key;
#line 97 "Gir.vala"
	_tmp6_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp4_, _tmp5_);
#line 97 "Gir.vala"
	result = (gchar*) _tmp6_;
#line 97 "Gir.vala"
	_g_free0 (key);
#line 97 "Gir.vala"
	return result;
#line 672 "Gir.vala.c"
}

static Block14Data*
block14_data_ref (Block14Data* _data14_)
{
#line 102 "Gir.vala"
	g_atomic_int_inc (&_data14_->_ref_count_);
#line 102 "Gir.vala"
	return _data14_;
#line 682 "Gir.vala.c"
}

static void
block14_data_unref (void * _userdata_)
{
	Block14Data* _data14_;
	_data14_ = (Block14Data*) _userdata_;
#line 102 "Gir.vala"
	if (g_atomic_int_dec_and_test (&_data14_->_ref_count_)) {
#line 102 "Gir.vala"
		_json_object_unref0 (_data14_->obj);
#line 102 "Gir.vala"
		g_slice_free (Block14Data, _data14_);
#line 696 "Gir.vala.c"
	}
}

static JsonNode*
_vala_JsonNode_copy (JsonNode* self)
{
#line 111 "Gir.vala"
	return g_boxed_copy (json_node_get_type (), self);
#line 705 "Gir.vala.c"
}

static gpointer
__vala_JsonNode_copy0 (gpointer self)
{
#line 111 "Gir.vala"
	return self ? _vala_JsonNode_copy (self) : NULL;
#line 713 "Gir.vala.c"
}

static void
_vala_JsonNode_free (JsonNode* self)
{
#line 111 "Gir.vala"
	g_boxed_free (json_node_get_type (), self);
#line 721 "Gir.vala.c"
}

static gpointer
_json_object_ref0 (gpointer self)
{
#line 125 "Gir.vala"
	return self ? json_object_ref (self) : NULL;
#line 729 "Gir.vala.c"
}

static void
__lambda233_ (Block14Data* _data14_,
              JsonObject* o,
              const gchar* key,
              JsonNode* value)
{
	gchar* v = NULL;
	JsonObject* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	GeeHashMap* _tmp3_;
#line 130 "Gir.vala"
	_tmp0_ = _data14_->obj;
#line 130 "Gir.vala"
	_tmp1_ = json_object_get_string_member (_tmp0_, key);
#line 130 "Gir.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 130 "Gir.vala"
	v = _tmp2_;
#line 131 "Gir.vala"
	_tmp3_ = palete_gir_overrides;
#line 131 "Gir.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp3_, key, v);
#line 128 "Gir.vala"
	_g_free0 (v);
#line 757 "Gir.vala.c"
}

static void
___lambda233__json_object_foreach (JsonObject* object,
                                   const gchar* member_name,
                                   JsonNode* member_node,
                                   gpointer self)
{
#line 128 "Gir.vala"
	__lambda233_ (self, object, member_name, member_node);
#line 768 "Gir.vala.c"
}

void
palete_gir_loadOverrides (gboolean force)
{
	Block14Data* _data14_;
	gboolean _tmp0_ = FALSE;
	JsonNode* node = NULL;
	JsonParser* pa = NULL;
	JsonParser* _tmp1_;
	GeeHashMap* _tmp13_;
	JsonNode* _tmp14_;
	JsonObject* _tmp15_;
	JsonObject* _tmp16_;
	JsonObject* _tmp17_;
	GError* _inner_error0_ = NULL;
#line 102 "Gir.vala"
	_data14_ = g_slice_new0 (Block14Data);
#line 102 "Gir.vala"
	_data14_->_ref_count_ = 1;
#line 104 "Gir.vala"
	if (palete_gir_overrides_loaded) {
#line 104 "Gir.vala"
		_tmp0_ = !force;
#line 793 "Gir.vala.c"
	} else {
#line 104 "Gir.vala"
		_tmp0_ = FALSE;
#line 797 "Gir.vala.c"
	}
#line 104 "Gir.vala"
	if (_tmp0_) {
#line 105 "Gir.vala"
		block14_data_unref (_data14_);
#line 105 "Gir.vala"
		_data14_ = NULL;
#line 105 "Gir.vala"
		return;
#line 807 "Gir.vala.c"
	}
#line 107 "Gir.vala"
	node = NULL;
#line 108 "Gir.vala"
	_tmp1_ = json_parser_new ();
#line 108 "Gir.vala"
	pa = _tmp1_;
#line 815 "Gir.vala.c"
	{
		JsonParser* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		JsonParser* _tmp7_;
		JsonNode* _tmp8_;
		JsonNode* _tmp9_;
		JsonNode* _tmp10_;
#line 110 "Gir.vala"
		_tmp2_ = pa;
#line 110 "Gir.vala"
		_tmp3_ = builder_application_configDirectory ();
#line 110 "Gir.vala"
		_tmp4_ = _tmp3_;
#line 110 "Gir.vala"
		_tmp5_ = g_strconcat (_tmp4_, "/resources/Gir.overides", NULL);
#line 110 "Gir.vala"
		_tmp6_ = _tmp5_;
#line 110 "Gir.vala"
		json_parser_load_from_file (_tmp2_, _tmp6_, &_inner_error0_);
#line 110 "Gir.vala"
		_g_free0 (_tmp6_);
#line 110 "Gir.vala"
		_g_free0 (_tmp4_);
#line 110 "Gir.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 844 "Gir.vala.c"
			goto __catch0_g_error;
		}
#line 111 "Gir.vala"
		_tmp7_ = pa;
#line 111 "Gir.vala"
		_tmp8_ = json_parser_get_root (_tmp7_);
#line 111 "Gir.vala"
		_tmp9_ = __vala_JsonNode_copy0 (_tmp8_);
#line 111 "Gir.vala"
		__vala_JsonNode_free0 (node);
#line 111 "Gir.vala"
		node = _tmp9_;
#line 112 "Gir.vala"
		_tmp10_ = node;
#line 112 "Gir.vala"
		if (json_node_get_node_type (_tmp10_) != JSON_NODE_OBJECT) {
#line 861 "Gir.vala.c"
			JsonNode* _tmp11_;
			const gchar* _tmp12_;
#line 113 "Gir.vala"
			_tmp11_ = node;
#line 113 "Gir.vala"
			_tmp12_ = json_node_type_name (_tmp11_);
#line 113 "Gir.vala"
			g_debug ("Gir.vala:113: Error loading gir.overides : Unexpected element type %s", _tmp12_);
#line 115 "Gir.vala"
			_g_object_unref0 (pa);
#line 115 "Gir.vala"
			__vala_JsonNode_free0 (node);
#line 115 "Gir.vala"
			block14_data_unref (_data14_);
#line 115 "Gir.vala"
			_data14_ = NULL;
#line 115 "Gir.vala"
			return;
#line 880 "Gir.vala.c"
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
#line 109 "Gir.vala"
		g_clear_error (&_inner_error0_);
#line 119 "Gir.vala"
		_g_object_unref0 (pa);
#line 119 "Gir.vala"
		__vala_JsonNode_free0 (node);
#line 119 "Gir.vala"
		block14_data_unref (_data14_);
#line 119 "Gir.vala"
		_data14_ = NULL;
#line 119 "Gir.vala"
		return;
#line 898 "Gir.vala.c"
	}
	__finally0:
#line 109 "Gir.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 109 "Gir.vala"
		_g_object_unref0 (pa);
#line 109 "Gir.vala"
		__vala_JsonNode_free0 (node);
#line 109 "Gir.vala"
		block14_data_unref (_data14_);
#line 109 "Gir.vala"
		_data14_ = NULL;
#line 109 "Gir.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 109 "Gir.vala"
		g_clear_error (&_inner_error0_);
#line 109 "Gir.vala"
		return;
#line 917 "Gir.vala.c"
	}
#line 122 "Gir.vala"
	_tmp13_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 122 "Gir.vala"
	_g_object_unref0 (palete_gir_overrides);
#line 122 "Gir.vala"
	palete_gir_overrides = _tmp13_;
#line 125 "Gir.vala"
	_tmp14_ = node;
#line 125 "Gir.vala"
	_tmp15_ = json_node_get_object (_tmp14_);
#line 125 "Gir.vala"
	_tmp16_ = _json_object_ref0 (_tmp15_);
#line 125 "Gir.vala"
	_data14_->obj = _tmp16_;
#line 128 "Gir.vala"
	_tmp17_ = _data14_->obj;
#line 128 "Gir.vala"
	json_object_foreach_member (_tmp17_, ___lambda233__json_object_foreach, _data14_);
#line 134 "Gir.vala"
	palete_gir_overrides_loaded = TRUE;
#line 102 "Gir.vala"
	_g_object_unref0 (pa);
#line 102 "Gir.vala"
	__vala_JsonNode_free0 (node);
#line 102 "Gir.vala"
	block14_data_unref (_data14_);
#line 102 "Gir.vala"
	_data14_ = NULL;
#line 947 "Gir.vala.c"
}

PaleteGir*
palete_gir_factory (ProjectProject* project,
                    const gchar* ns)
{
	GeeHashMap* _tmp0_;
	GeeHashMap* cache = NULL;
	GeeHashMap* _tmp2_;
	GeeHashMap* _tmp3_;
	gboolean _tmp4_ = FALSE;
	PaleteGir* ret = NULL;
	GeeHashMap* _tmp13_;
	gpointer _tmp14_;
	gboolean _tmp15_ = FALSE;
	PaleteGir* _tmp16_;
	PaleteGir* result;
#line 148 "Gir.vala"
	_tmp0_ = palete_gir_global_cache;
#line 148 "Gir.vala"
	if (_tmp0_ == NULL) {
#line 969 "Gir.vala.c"
		GeeHashMap* _tmp1_;
#line 149 "Gir.vala"
		_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, PALETE_TYPE_GIR, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 149 "Gir.vala"
		_g_object_unref0 (palete_gir_global_cache);
#line 149 "Gir.vala"
		palete_gir_global_cache = _tmp1_;
#line 977 "Gir.vala.c"
	}
#line 152 "Gir.vala"
	_tmp2_ = palete_gir_global_cache;
#line 152 "Gir.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 152 "Gir.vala"
	cache = _tmp3_;
#line 153 "Gir.vala"
	if (project != NULL) {
#line 153 "Gir.vala"
		_tmp4_ = PROJECT_IS_GTK (project);
#line 989 "Gir.vala.c"
	} else {
#line 153 "Gir.vala"
		_tmp4_ = FALSE;
#line 993 "Gir.vala.c"
	}
#line 153 "Gir.vala"
	if (_tmp4_) {
#line 997 "Gir.vala.c"
		ProjectGtk* gproj = NULL;
		ProjectGtk* _tmp5_;
		ProjectGtk* _tmp6_;
		ProjectGtk* _tmp10_;
		GeeHashMap* _tmp11_;
		GeeHashMap* _tmp12_;
#line 154 "Gir.vala"
		_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (project, PROJECT_TYPE_GTK, ProjectGtk));
#line 154 "Gir.vala"
		gproj = _tmp5_;
#line 155 "Gir.vala"
		_tmp6_ = gproj;
#line 155 "Gir.vala"
		if (!_tmp6_->gir_cache_loaded) {
#line 1012 "Gir.vala.c"
			PaleteVapiParser* a = NULL;
			PaleteVapiParser* _tmp7_;
			PaleteVapiParser* _tmp8_;
			ProjectGtk* _tmp9_;
#line 156 "Gir.vala"
			_tmp7_ = palete_vapi_parser_new (G_TYPE_CHECK_INSTANCE_CAST (project, PROJECT_TYPE_GTK, ProjectGtk));
#line 156 "Gir.vala"
			a = _tmp7_;
#line 157 "Gir.vala"
			_tmp8_ = a;
#line 157 "Gir.vala"
			palete_vapi_parser_create_valac_tree (_tmp8_);
#line 158 "Gir.vala"
			_tmp9_ = gproj;
#line 158 "Gir.vala"
			_tmp9_->gir_cache_loaded = TRUE;
#line 155 "Gir.vala"
			_vala_code_visitor_unref0 (a);
#line 1031 "Gir.vala.c"
		}
#line 160 "Gir.vala"
		_tmp10_ = gproj;
#line 160 "Gir.vala"
		_tmp11_ = _tmp10_->gir_cache;
#line 160 "Gir.vala"
		_tmp12_ = _g_object_ref0 (_tmp11_);
#line 160 "Gir.vala"
		_g_object_unref0 (cache);
#line 160 "Gir.vala"
		cache = _tmp12_;
#line 153 "Gir.vala"
		_g_object_unref0 (gproj);
#line 1045 "Gir.vala.c"
	}
#line 165 "Gir.vala"
	_tmp13_ = cache;
#line 165 "Gir.vala"
	_tmp14_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp13_, ns);
#line 165 "Gir.vala"
	ret = (PaleteGir*) _tmp14_;
#line 169 "Gir.vala"
	_tmp16_ = ret;
#line 169 "Gir.vala"
	if (_tmp16_ != NULL) {
#line 1057 "Gir.vala.c"
		PaleteGir* _tmp17_;
#line 169 "Gir.vala"
		_tmp17_ = ret;
#line 169 "Gir.vala"
		_tmp15_ = !((PaleteGirObject*) _tmp17_)->is_overlaid;
#line 1063 "Gir.vala.c"
	} else {
#line 169 "Gir.vala"
		_tmp15_ = FALSE;
#line 1067 "Gir.vala.c"
	}
#line 169 "Gir.vala"
	if (_tmp15_) {
#line 1071 "Gir.vala.c"
		PaleteGir* _tmp18_;
		GeeMapIterator* iter = NULL;
		PaleteGir* _tmp19_;
		GeeHashMap* _tmp20_;
		GeeMapIterator* _tmp21_;
		PaleteGir* _tmp26_;
		GeeHashMap* _tmp27_;
		GeeMapIterator* _tmp28_;
#line 170 "Gir.vala"
		_tmp18_ = ret;
#line 170 "Gir.vala"
		((PaleteGirObject*) _tmp18_)->is_overlaid = TRUE;
#line 171 "Gir.vala"
		_tmp19_ = ret;
#line 171 "Gir.vala"
		_tmp20_ = ((PaleteGirObject*) _tmp19_)->classes;
#line 171 "Gir.vala"
		_tmp21_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp20_);
#line 171 "Gir.vala"
		iter = _tmp21_;
#line 172 "Gir.vala"
		while (TRUE) {
#line 1094 "Gir.vala.c"
			GeeMapIterator* _tmp22_;
			GeeMapIterator* _tmp23_;
			gpointer _tmp24_;
			PaleteGirObject* _tmp25_;
#line 172 "Gir.vala"
			_tmp22_ = iter;
#line 172 "Gir.vala"
			if (!gee_map_iterator_next (_tmp22_)) {
#line 172 "Gir.vala"
				break;
#line 1105 "Gir.vala.c"
			}
#line 173 "Gir.vala"
			_tmp23_ = iter;
#line 173 "Gir.vala"
			_tmp24_ = gee_map_iterator_get_value (_tmp23_);
#line 173 "Gir.vala"
			_tmp25_ = (PaleteGirObject*) _tmp24_;
#line 173 "Gir.vala"
			palete_gir_object_overlayParent (_tmp25_, project);
#line 173 "Gir.vala"
			_g_object_unref0 (_tmp25_);
#line 1117 "Gir.vala.c"
		}
#line 176 "Gir.vala"
		_tmp26_ = ret;
#line 176 "Gir.vala"
		_tmp27_ = ((PaleteGirObject*) _tmp26_)->classes;
#line 176 "Gir.vala"
		_tmp28_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp27_);
#line 176 "Gir.vala"
		_g_object_unref0 (iter);
#line 176 "Gir.vala"
		iter = _tmp28_;
#line 177 "Gir.vala"
		while (TRUE) {
#line 1131 "Gir.vala.c"
			GeeMapIterator* _tmp29_;
			GeeMapIterator* _tmp30_;
			gpointer _tmp31_;
			PaleteGirObject* _tmp32_;
#line 177 "Gir.vala"
			_tmp29_ = iter;
#line 177 "Gir.vala"
			if (!gee_map_iterator_next (_tmp29_)) {
#line 177 "Gir.vala"
				break;
#line 1142 "Gir.vala.c"
			}
#line 178 "Gir.vala"
			_tmp30_ = iter;
#line 178 "Gir.vala"
			_tmp31_ = gee_map_iterator_get_value (_tmp30_);
#line 178 "Gir.vala"
			_tmp32_ = (PaleteGirObject*) _tmp31_;
#line 178 "Gir.vala"
			palete_gir_object_overlayCtorProperties (_tmp32_);
#line 178 "Gir.vala"
			_g_object_unref0 (_tmp32_);
#line 1154 "Gir.vala.c"
		}
#line 169 "Gir.vala"
		_g_object_unref0 (iter);
#line 1158 "Gir.vala.c"
	}
#line 184 "Gir.vala"
	result = ret;
#line 184 "Gir.vala"
	_g_object_unref0 (cache);
#line 184 "Gir.vala"
	return result;
#line 1166 "Gir.vala.c"
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
#line 1455 "glib-2.0.vapi"
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
#line 1455 "glib-2.0.vapi"
	end = _tmp0_;
#line 1456 "glib-2.0.vapi"
	_tmp1_ = end;
#line 1456 "glib-2.0.vapi"
	if (_tmp1_ == NULL) {
#line 1457 "glib-2.0.vapi"
		result = maxlen;
#line 1457 "glib-2.0.vapi"
		return result;
#line 1189 "Gir.vala.c"
	} else {
		gchar* _tmp2_;
#line 1459 "glib-2.0.vapi"
		_tmp2_ = end;
#line 1459 "glib-2.0.vapi"
		result = (glong) (_tmp2_ - str);
#line 1459 "glib-2.0.vapi"
		return result;
#line 1198 "Gir.vala.c"
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
#line 1468 "glib-2.0.vapi"
	if (offset >= ((glong) 0)) {
#line 1468 "glib-2.0.vapi"
		_tmp0_ = len >= ((glong) 0);
#line 1215 "Gir.vala.c"
	} else {
#line 1468 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 1219 "Gir.vala.c"
	}
#line 1468 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1470 "glib-2.0.vapi"
		string_length = string_strnlen ((gchar*) self, offset + len);
#line 1225 "Gir.vala.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 1472 "glib-2.0.vapi"
		_tmp1_ = strlen (self);
#line 1472 "glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1472 "glib-2.0.vapi"
		string_length = (glong) _tmp2_;
#line 1235 "Gir.vala.c"
	}
#line 1475 "glib-2.0.vapi"
	if (offset < ((glong) 0)) {
#line 1476 "glib-2.0.vapi"
		offset = string_length + offset;
#line 1477 "glib-2.0.vapi"
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
#line 1243 "Gir.vala.c"
	} else {
#line 1479 "glib-2.0.vapi"
		g_return_val_if_fail (offset <= string_length, NULL);
#line 1247 "Gir.vala.c"
	}
#line 1481 "glib-2.0.vapi"
	if (len < ((glong) 0)) {
#line 1482 "glib-2.0.vapi"
		len = string_length - offset;
#line 1253 "Gir.vala.c"
	}
#line 1484 "glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
#line 1485 "glib-2.0.vapi"
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
#line 1485 "glib-2.0.vapi"
	result = _tmp3_;
#line 1485 "glib-2.0.vapi"
	return result;
#line 1263 "Gir.vala.c"
}

PaleteGirObject*
palete_gir_factoryFqn (ProjectProject* project,
                       const gchar* in_fqn)
{
	gchar* fqn = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar** bits = NULL;
	const gchar* _tmp2_;
	gchar** _tmp3_;
	gchar** _tmp4_;
	gint bits_length1;
	gint _bits_size_;
	gchar** _tmp5_;
	gint _tmp5__length1;
	PaleteGirObject* f = NULL;
	gchar** _tmp6_;
	gint _tmp6__length1;
	const gchar* _tmp7_;
	PaleteGir* _tmp8_;
	gboolean _tmp9_ = FALSE;
	gchar** _tmp10_;
	gint _tmp10__length1;
	const gchar* _tmp12_;
	gchar** _tmp13_;
	gint _tmp13__length1;
	const gchar* _tmp14_;
	gint _tmp15_;
	gint _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	PaleteGirObject* _tmp19_;
	const gchar* _tmp20_;
	gchar** _tmp21_;
	gint _tmp21__length1;
	const gchar* _tmp22_;
	gint _tmp23_;
	gint _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	PaleteGirObject* _tmp27_;
	PaleteGirObject* _tmp28_;
	PaleteGirObject* result;
#line 193 "Gir.vala"
	_tmp0_ = g_strdup (in_fqn);
#line 193 "Gir.vala"
	fqn = _tmp0_;
#line 196 "Gir.vala"
	_tmp1_ = fqn;
#line 196 "Gir.vala"
	g_debug ("Gir.vala:196: Gir.factoryFqn  search %s", _tmp1_);
#line 197 "Gir.vala"
	_tmp2_ = fqn;
#line 197 "Gir.vala"
	_tmp4_ = _tmp3_ = g_strsplit (_tmp2_, ".", 0);
#line 197 "Gir.vala"
	bits = _tmp4_;
#line 197 "Gir.vala"
	bits_length1 = _vala_array_length (_tmp3_);
#line 197 "Gir.vala"
	_bits_size_ = bits_length1;
#line 198 "Gir.vala"
	_tmp5_ = bits;
#line 198 "Gir.vala"
	_tmp5__length1 = bits_length1;
#line 198 "Gir.vala"
	if (_tmp5__length1 < 1) {
#line 199 "Gir.vala"
		g_debug ("Gir.vala:199: Gir.factoryFqn  fail - missing '.'");
#line 200 "Gir.vala"
		result = NULL;
#line 200 "Gir.vala"
		bits = (_vala_array_free (bits, bits_length1, (GDestroyNotify) g_free), NULL);
#line 200 "Gir.vala"
		_g_free0 (fqn);
#line 200 "Gir.vala"
		return result;
#line 1343 "Gir.vala.c"
	}
#line 203 "Gir.vala"
	_tmp6_ = bits;
#line 203 "Gir.vala"
	_tmp6__length1 = bits_length1;
#line 203 "Gir.vala"
	_tmp7_ = _tmp6_[0];
#line 203 "Gir.vala"
	_tmp8_ = palete_gir_factory (project, _tmp7_);
#line 203 "Gir.vala"
	f = G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, PALETE_TYPE_GIR_OBJECT, PaleteGirObject);
#line 205 "Gir.vala"
	_tmp10_ = bits;
#line 205 "Gir.vala"
	_tmp10__length1 = bits_length1;
#line 205 "Gir.vala"
	if (_tmp10__length1 == 1) {
#line 205 "Gir.vala"
		_tmp9_ = TRUE;
#line 1363 "Gir.vala.c"
	} else {
		PaleteGirObject* _tmp11_;
#line 205 "Gir.vala"
		_tmp11_ = f;
#line 205 "Gir.vala"
		_tmp9_ = _tmp11_ == NULL;
#line 1370 "Gir.vala.c"
	}
#line 205 "Gir.vala"
	if (_tmp9_) {
#line 206 "Gir.vala"
		g_debug ("Gir.vala:206: Gir.factoryFqn  fail - factory failed to load NS");
#line 207 "Gir.vala"
		result = f;
#line 207 "Gir.vala"
		bits = (_vala_array_free (bits, bits_length1, (GDestroyNotify) g_free), NULL);
#line 207 "Gir.vala"
		_g_free0 (fqn);
#line 207 "Gir.vala"
		return result;
#line 1384 "Gir.vala.c"
	}
#line 209 "Gir.vala"
	_tmp12_ = fqn;
#line 209 "Gir.vala"
	_tmp13_ = bits;
#line 209 "Gir.vala"
	_tmp13__length1 = bits_length1;
#line 209 "Gir.vala"
	_tmp14_ = _tmp13_[0];
#line 209 "Gir.vala"
	_tmp15_ = strlen (_tmp14_);
#line 209 "Gir.vala"
	_tmp16_ = _tmp15_;
#line 209 "Gir.vala"
	_tmp17_ = string_substring (_tmp12_, (glong) (_tmp16_ + 1), (glong) -1);
#line 209 "Gir.vala"
	_tmp18_ = _tmp17_;
#line 209 "Gir.vala"
	g_debug ("Gir.vala:209: Gir.factoryFqn  fetching child %s", _tmp18_);
#line 209 "Gir.vala"
	_g_free0 (_tmp18_);
#line 210 "Gir.vala"
	_tmp19_ = f;
#line 210 "Gir.vala"
	_tmp20_ = fqn;
#line 210 "Gir.vala"
	_tmp21_ = bits;
#line 210 "Gir.vala"
	_tmp21__length1 = bits_length1;
#line 210 "Gir.vala"
	_tmp22_ = _tmp21_[0];
#line 210 "Gir.vala"
	_tmp23_ = strlen (_tmp22_);
#line 210 "Gir.vala"
	_tmp24_ = _tmp23_;
#line 210 "Gir.vala"
	_tmp25_ = string_substring (_tmp20_, (glong) (_tmp24_ + 1), (glong) -1);
#line 210 "Gir.vala"
	_tmp26_ = _tmp25_;
#line 210 "Gir.vala"
	_tmp27_ = palete_gir_object_fetchByFqn (_tmp19_, _tmp26_);
#line 210 "Gir.vala"
	_tmp28_ = _tmp27_;
#line 210 "Gir.vala"
	_g_free0 (_tmp26_);
#line 210 "Gir.vala"
	result = _tmp28_;
#line 210 "Gir.vala"
	_g_object_unref0 (f);
#line 210 "Gir.vala"
	bits = (_vala_array_free (bits, bits_length1, (GDestroyNotify) g_free), NULL);
#line 210 "Gir.vala"
	_g_free0 (fqn);
#line 210 "Gir.vala"
	return result;
#line 1440 "Gir.vala.c"
}

/**
 * guess the fqn of a type == eg. gboolean or Widget etc...
 */
gchar*
palete_gir_fqtypeLookup (ProjectProject* project,
                         const gchar* type,
                         const gchar* ns)
{
	PaleteGir* g = NULL;
	PaleteGir* _tmp0_;
	PaleteGir* _tmp1_;
	GeeHashMap* _tmp2_;
	PaleteGir* _tmp7_;
	GeeHashMap* _tmp8_;
	GeeMapIterator* iter = NULL;
	PaleteGir* _tmp13_;
	GeeHashMap* _tmp14_;
	GeeMapIterator* _tmp15_;
	gchar* _tmp27_;
	gchar* result;
#line 220 "Gir.vala"
	_tmp0_ = palete_gir_factory (project, ns);
#line 220 "Gir.vala"
	g = _tmp0_;
#line 221 "Gir.vala"
	_tmp1_ = g;
#line 221 "Gir.vala"
	_tmp2_ = ((PaleteGirObject*) _tmp1_)->classes;
#line 221 "Gir.vala"
	if (gee_abstract_map_has_key ((GeeAbstractMap*) _tmp2_, type)) {
#line 1473 "Gir.vala.c"
		gchar* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
#line 222 "Gir.vala"
		_tmp3_ = g_strconcat (ns, ".", NULL);
#line 222 "Gir.vala"
		_tmp4_ = _tmp3_;
#line 222 "Gir.vala"
		_tmp5_ = g_strconcat (_tmp4_, type, NULL);
#line 222 "Gir.vala"
		_tmp6_ = _tmp5_;
#line 222 "Gir.vala"
		_g_free0 (_tmp4_);
#line 222 "Gir.vala"
		result = _tmp6_;
#line 222 "Gir.vala"
		_g_object_unref0 (g);
#line 222 "Gir.vala"
		return result;
#line 1494 "Gir.vala.c"
	}
#line 225 "Gir.vala"
	_tmp7_ = g;
#line 225 "Gir.vala"
	_tmp8_ = ((PaleteGirObject*) _tmp7_)->consts;
#line 225 "Gir.vala"
	if (gee_abstract_map_has_key ((GeeAbstractMap*) _tmp8_, type)) {
#line 1502 "Gir.vala.c"
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
#line 226 "Gir.vala"
		_tmp9_ = g_strconcat (ns, ".", NULL);
#line 226 "Gir.vala"
		_tmp10_ = _tmp9_;
#line 226 "Gir.vala"
		_tmp11_ = g_strconcat (_tmp10_, type, NULL);
#line 226 "Gir.vala"
		_tmp12_ = _tmp11_;
#line 226 "Gir.vala"
		_g_free0 (_tmp10_);
#line 226 "Gir.vala"
		result = _tmp12_;
#line 226 "Gir.vala"
		_g_object_unref0 (g);
#line 226 "Gir.vala"
		return result;
#line 1523 "Gir.vala.c"
	}
#line 231 "Gir.vala"
	_tmp13_ = g;
#line 231 "Gir.vala"
	_tmp14_ = ((PaleteGirObject*) _tmp13_)->includes;
#line 231 "Gir.vala"
	_tmp15_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp14_);
#line 231 "Gir.vala"
	iter = _tmp15_;
#line 232 "Gir.vala"
	while (TRUE) {
#line 1535 "Gir.vala.c"
		GeeMapIterator* _tmp16_;
		GeeMapIterator* _tmp17_;
		gpointer _tmp18_;
		gchar* _tmp19_;
		gboolean _tmp20_;
		gchar* ret = NULL;
		GeeMapIterator* _tmp21_;
		gpointer _tmp22_;
		gchar* _tmp23_;
		gchar* _tmp24_;
		gchar* _tmp25_;
		const gchar* _tmp26_;
#line 232 "Gir.vala"
		_tmp16_ = iter;
#line 232 "Gir.vala"
		if (!gee_map_iterator_next (_tmp16_)) {
#line 232 "Gir.vala"
			break;
#line 1554 "Gir.vala.c"
		}
#line 234 "Gir.vala"
		_tmp17_ = iter;
#line 234 "Gir.vala"
		_tmp18_ = gee_map_iterator_get_key (_tmp17_);
#line 234 "Gir.vala"
		_tmp19_ = (gchar*) _tmp18_;
#line 234 "Gir.vala"
		_tmp20_ = g_strcmp0 (_tmp19_, "") == 0;
#line 234 "Gir.vala"
		_g_free0 (_tmp19_);
#line 234 "Gir.vala"
		if (_tmp20_) {
#line 235 "Gir.vala"
			continue;
#line 1570 "Gir.vala.c"
		}
#line 237 "Gir.vala"
		_tmp21_ = iter;
#line 237 "Gir.vala"
		_tmp22_ = gee_map_iterator_get_key (_tmp21_);
#line 237 "Gir.vala"
		_tmp23_ = (gchar*) _tmp22_;
#line 237 "Gir.vala"
		_tmp24_ = palete_gir_fqtypeLookup (project, type, _tmp23_);
#line 237 "Gir.vala"
		_tmp25_ = _tmp24_;
#line 237 "Gir.vala"
		_g_free0 (_tmp23_);
#line 237 "Gir.vala"
		ret = _tmp25_;
#line 238 "Gir.vala"
		_tmp26_ = ret;
#line 238 "Gir.vala"
		if (g_strcmp0 (_tmp26_, type) != 0) {
#line 239 "Gir.vala"
			result = ret;
#line 239 "Gir.vala"
			_g_object_unref0 (iter);
#line 239 "Gir.vala"
			_g_object_unref0 (g);
#line 239 "Gir.vala"
			return result;
#line 1598 "Gir.vala.c"
		}
#line 232 "Gir.vala"
		_g_free0 (ret);
#line 1602 "Gir.vala.c"
	}
#line 242 "Gir.vala"
	_tmp27_ = g_strdup (type);
#line 242 "Gir.vala"
	result = _tmp27_;
#line 242 "Gir.vala"
	_g_object_unref0 (iter);
#line 242 "Gir.vala"
	_g_object_unref0 (g);
#line 242 "Gir.vala"
	return result;
#line 1614 "Gir.vala.c"
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gchar* _tmp0_;
	gboolean result;
#line 1539 "glib-2.0.vapi"
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
#line 1539 "glib-2.0.vapi"
	result = _tmp0_ != NULL;
#line 1539 "glib-2.0.vapi"
	return result;
#line 1629 "Gir.vala.c"
}

gchar*
palete_gir_guessDefaultValueForType (const gchar* type)
{
	gboolean _tmp0_ = FALSE;
	gint _tmp1_;
	gint _tmp2_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GQuark _tmp7_ = 0U;
#line 254 "Gir.vala"
	static GQuark _tmp6_label0 = 0;
#line 254 "Gir.vala"
	static GQuark _tmp6_label1 = 0;
#line 254 "Gir.vala"
	static GQuark _tmp6_label2 = 0;
#line 254 "Gir.vala"
	static GQuark _tmp6_label3 = 0;
#line 254 "Gir.vala"
	static GQuark _tmp6_label4 = 0;
#line 254 "Gir.vala"
	static GQuark _tmp6_label5 = 0;
#line 254 "Gir.vala"
	static GQuark _tmp6_label6 = 0;
#line 254 "Gir.vala"
	static GQuark _tmp6_label7 = 0;
#line 1657 "Gir.vala.c"
	gchar* result;
#line 251 "Gir.vala"
	_tmp1_ = strlen (type);
#line 251 "Gir.vala"
	_tmp2_ = _tmp1_;
#line 251 "Gir.vala"
	if (_tmp2_ < 1) {
#line 251 "Gir.vala"
		_tmp0_ = TRUE;
#line 1667 "Gir.vala.c"
	} else {
#line 251 "Gir.vala"
		_tmp0_ = string_contains (type, ".");
#line 1671 "Gir.vala.c"
	}
#line 251 "Gir.vala"
	if (_tmp0_) {
#line 1675 "Gir.vala.c"
		gchar* _tmp3_;
#line 252 "Gir.vala"
		_tmp3_ = g_strdup ("null");
#line 252 "Gir.vala"
		result = _tmp3_;
#line 252 "Gir.vala"
		return result;
#line 1683 "Gir.vala.c"
	}
#line 254 "Gir.vala"
	_tmp4_ = g_utf8_strdown (type, (gssize) -1);
#line 254 "Gir.vala"
	_tmp5_ = _tmp4_;
#line 254 "Gir.vala"
	_tmp7_ = (NULL == _tmp5_) ? 0 : g_quark_from_string (_tmp5_);
#line 254 "Gir.vala"
	g_free (_tmp5_);
#line 254 "Gir.vala"
	if (((_tmp7_ == ((0 != _tmp6_label0) ? _tmp6_label0 : (_tmp6_label0 = g_quark_from_static_string ("boolean")))) || (_tmp7_ == ((0 != _tmp6_label1) ? _tmp6_label1 : (_tmp6_label1 = g_quark_from_static_string ("bool"))))) || (_tmp7_ == ((0 != _tmp6_label2) ? _tmp6_label2 : (_tmp6_label2 = g_quark_from_static_string ("gboolean"))))) {
#line 254 "Gir.vala"
		switch (0) {
#line 1697 "Gir.vala.c"
			default:
			{
				gchar* _tmp8_;
#line 258 "Gir.vala"
				_tmp8_ = g_strdup ("true");
#line 258 "Gir.vala"
				result = _tmp8_;
#line 258 "Gir.vala"
				return result;
#line 1707 "Gir.vala.c"
			}
		}
	} else if ((_tmp7_ == ((0 != _tmp6_label3) ? _tmp6_label3 : (_tmp6_label3 = g_quark_from_static_string ("int")))) || (_tmp7_ == ((0 != _tmp6_label4) ? _tmp6_label4 : (_tmp6_label4 = g_quark_from_static_string ("guint"))))) {
#line 254 "Gir.vala"
		switch (0) {
#line 1713 "Gir.vala.c"
			default:
			{
				gchar* _tmp9_;
#line 261 "Gir.vala"
				_tmp9_ = g_strdup ("0");
#line 261 "Gir.vala"
				result = _tmp9_;
#line 261 "Gir.vala"
				return result;
#line 1723 "Gir.vala.c"
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label5) ? _tmp6_label5 : (_tmp6_label5 = g_quark_from_static_string ("gdouble")))) {
#line 254 "Gir.vala"
		switch (0) {
#line 1729 "Gir.vala.c"
			default:
			{
				gchar* _tmp10_;
#line 263 "Gir.vala"
				_tmp10_ = g_strdup ("0f");
#line 263 "Gir.vala"
				result = _tmp10_;
#line 263 "Gir.vala"
				return result;
#line 1739 "Gir.vala.c"
			}
		}
	} else if ((_tmp7_ == ((0 != _tmp6_label6) ? _tmp6_label6 : (_tmp6_label6 = g_quark_from_static_string ("utf8")))) || (_tmp7_ == ((0 != _tmp6_label7) ? _tmp6_label7 : (_tmp6_label7 = g_quark_from_static_string ("string"))))) {
#line 254 "Gir.vala"
		switch (0) {
#line 1745 "Gir.vala.c"
			default:
			{
				gchar* _tmp11_;
#line 266 "Gir.vala"
				_tmp11_ = g_strdup ("\"\"");
#line 266 "Gir.vala"
				result = _tmp11_;
#line 266 "Gir.vala"
				return result;
#line 1755 "Gir.vala.c"
			}
		}
	} else {
#line 254 "Gir.vala"
		switch (0) {
#line 1761 "Gir.vala.c"
			default:
			{
				gchar* _tmp12_;
				gchar* _tmp13_;
				gchar* _tmp14_;
				gchar* _tmp15_;
#line 268 "Gir.vala"
				_tmp12_ = g_strconcat ("?", type, NULL);
#line 268 "Gir.vala"
				_tmp13_ = _tmp12_;
#line 268 "Gir.vala"
				_tmp14_ = g_strconcat (_tmp13_, "?", NULL);
#line 268 "Gir.vala"
				_tmp15_ = _tmp14_;
#line 268 "Gir.vala"
				_g_free0 (_tmp13_);
#line 268 "Gir.vala"
				result = _tmp15_;
#line 268 "Gir.vala"
				return result;
#line 1782 "Gir.vala.c"
			}
		}
	}
}

static void
palete_gir_class_init (PaleteGirClass * klass,
                       gpointer klass_data)
{
#line 29 "Gir.vala"
	palete_gir_parent_class = g_type_class_peek_parent (klass);
#line 29 "Gir.vala"
	G_OBJECT_CLASS (klass)->finalize = palete_gir_finalize;
#line 1796 "Gir.vala.c"
}

static void
palete_gir_instance_init (PaleteGir * self,
                          gpointer klass)
{
}

static void
palete_gir_finalize (GObject * obj)
{
	PaleteGir * self;
#line 29 "Gir.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PALETE_TYPE_GIR, PaleteGir);
#line 29 "Gir.vala"
	G_OBJECT_CLASS (palete_gir_parent_class)->finalize (obj);
#line 1813 "Gir.vala.c"
}

static GType
palete_gir_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (PaleteGirClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) palete_gir_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PaleteGir), 0, (GInstanceInitFunc) palete_gir_instance_init, NULL };
	GType palete_gir_type_id;
	palete_gir_type_id = g_type_register_static (PALETE_TYPE_GIR_OBJECT, "PaleteGir", &g_define_type_info, 0);
	return palete_gir_type_id;
}

GType
palete_gir_get_type (void)
{
	static volatile gsize palete_gir_type_id__once = 0;
	if (g_once_init_enter (&palete_gir_type_id__once)) {
		GType palete_gir_type_id;
		palete_gir_type_id = palete_gir_get_type_once ();
		g_once_init_leave (&palete_gir_type_id__once, palete_gir_type_id);
	}
	return palete_gir_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
	if (mem && byte_size != 0) {
		new_mem = g_malloc (byte_size);
		memcpy (new_mem, mem, byte_size);
	} else {
		new_mem = NULL;
	}
	return new_mem;
}

